Source/UI/src/EmailDialog.cpp

Fix compile error at EmailDialog

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/TitaniumKit/examples/NativeWindowExample.cpp
Source/TitaniumKit/examples/NativeWindowExample.hpp
Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/Module.cpp
Source/TitaniumKit/src/UI/Window.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/AlertDialog.cpp
Source/UI/src/Button.cpp
Source/UI/src/EmailDialog.cpp
Source/UI/src/ImageView.cpp
Source/UI/src/Label.cpp
Source/UI/src/ListView.cpp
Source/UI/src/ScrollView.cpp
Source/UI/src/Slider.cpp
Source/UI/src/Switch.cpp
Source/UI/src/TableView.cpp
Source/UI/src/TextField.cpp
Source/UI/src/View.cpp
Source/UI/src/WebView.cpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix some layout issues and implement functions.
- [[TIMOB-18785](https://jira.appcelerator.org/browse/TIMOB-18785)] Implement "postlayout" UI event
- [[TIMOB-18787](https://jira.appcelerator.org/browse/TIMOB-18787)] Word wrap does not work for Label
- Disabled `crollViewWithLargeVerticalLayoutChild` test, because it should have not working (because "postlayout" for ScrollView was not implemented[[TIMOB-18785](https://jira.appcelerator.org/browse/TIMOB-18785)]), I think it just "looked" like working before unexpectedly.
- Disabled `sizeFillConflict` test because it is pretty unstable in Release build. It should be tackled by another ticket ([TIMOB-18790](https://jira.appcelerator.org/browse/TIMOB-18790)).
For testing word wrap, use following code
``` …
```

Fix some layout issues & missing functions

---

apidoc/ti_win_yaml.js

- Fixed the YAML whitelist folder structure
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18820)

[TIMOB-18820] Fix whitelist folder structure

---

apidoc/ti_win_yaml.js

- Fix _Titanium.Proxy_ in parity report
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18828)

[TIMOB-18828] Fix Titanium.Proxy in parity report

---

Examples/NG/src/Assets/app.js
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UI/ActivityIndicator.hpp
Source/TitaniumKit/include/Titanium/UI/ActivityIndicatorStyle.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/ActivityIndicator.cpp
Source/TitaniumKit/src/UI/ActivityIndicatorStyle.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/TitaniumKit/test/UITests.cpp
Source/TitaniumKit/xcode/TitaniumKit.xcodeproj/project.pbxproj
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI.hpp
Source/UI/include/TitaniumWindows/UI/ActivityIndicator.hpp
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/ActivityIndicator.cpp
Source/UI/src/Label.cpp

Implement Ti.UI.ActivityIndicator
- [TIMOB-18050](https://jira.appcelerator.org/browse/TIMOB-18050)
- Update NG example to showcase existing components

[TIMOB-18050] Implement Ti.UI.ActivityIndicator

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.window.test.js
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/Window.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UIModule.hpp
Source/UI/src/UIModule.cpp
Source/UI/src/Window.cpp

- [TIMOB-18839](https://jira.appcelerator.org/browse/TIMOB-18839) Implement Ti.UI.setBackgroundColor
- Add Ti.UI methods
- Implement Ti.UI.`currentWindow` and`currentTab`
- Enable unit tests for Ti.UI.Window
- some of them are "skipped", need to be fixed later on

[TIMOB-18839] Implement Ti.UI.setBackgroundColor

---

Examples/NG/src/Assets/app.js
Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Examples/NMocha/src/Assets/ti.network.test.js
Examples/NMocha/src/Assets/ti.ui.activityindicator.test.js
Examples/NMocha/src/Assets/ti.ui.window.test.js
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/Window.cpp

Taking over #224 and fix some crash at NMocha.

TIMOB-18760 Windows: Implement Ti.Network encode and decodeURIComponent

---

Examples/NG/src/Assets/app.js
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UI/2DMatrix.hpp
Source/TitaniumKit/include/Titanium/UI/Animation.hpp
Source/TitaniumKit/include/Titanium/UI/Button.hpp
Source/TitaniumKit/include/Titanium/UI/MatrixCreationDict.hpp
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/2DMatrix.cpp
Source/TitaniumKit/src/UI/Animation.cpp
Source/TitaniumKit/src/UI/Button.cpp
Source/TitaniumKit/src/UI/MatrixCreationDict.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/include/TitaniumWindows/UI.hpp
Source/UI/include/TitaniumWindows/UI/Button.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Button.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

2DMatrix Proxy

---

Source/App/CMakeLists.txt
Source/App/include/TitaniumWindows/App.hpp
Source/App/include/TitaniumWindows/AppModule.hpp
Source/App/src/AppModule.cpp
Source/Titanium/src/TitaniumWindows.cpp
Source/Titanium/src/TitaniumWindows.hpp
Source/TitaniumKit/src/Module.cpp

Implement basic Ti.App events
- `pause`, `paused`
- `resume`, `resumed`
- `keyboardframechanged`

[TIMOB-18758] Implement Ti.App events

---

Source/TitaniumKit/src/UI/Animation.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Animation improvements

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.alertdialog.test.js
Examples/NMocha/src/Assets/ti.ui.optiondialog.test.js
Examples/NMocha/src/Assets/ti.ui.scrollableview.test.js
Source/TitaniumKit/include/Titanium/UI/AlertDialog.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/AlertDialog.cpp
Source/TitaniumKit/src/UI/ScrollableView.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/AlertDialog.hpp
Source/UI/include/TitaniumWindows/UI/ScrollableView.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/AlertDialog.cpp
Source/UI/src/ScrollableView.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Implement Ti.UI.ScrollableView
- Add unit test for OptionDialog, AlertDialog, ProgressBar and ScrollableView
- Refactor AlertDialog
Here's a sample code for ScrollableView:
```javascript
backgroundColor: 'white'
});
var view = Ti.UI.createScrollableView({
backgroundColor: 'black'
});
var page1 = Ti.UI.createView({
});
var page2 = Ti.UI.createView({
});
var page3 = Ti.UI.createView({
});
var title1 = Ti.UI.createLabel({
text: 'Page 1'
});
var title2 = Ti.UI.createLabel({
text: 'Page 2'
});
var title3 = Ti.UI.createLabel({
text: 'Page 3'
});
page1.add(title1);
page2.add(title2);
page3.add(title3);
//view.addView(page1);
//view.addView(page2);
//view.addView(page3);
view.views = [page1, …
```

Implement Ti.UI.ScrollableView

---

Tools/Scripts/module_generator/generate.js
Tools/Scripts/module_generator/module_template/Module/include/TitaniumWindows/Module.hpp
Tools/Scripts/module_generator/module_template/Module/src/Module.cpp
Tools/Scripts/module_generator/module_template/TitaniumKit/include/Titanium/Module.hpp
Tools/Scripts/module_generator/module_template/TitaniumKit/src/Module.cpp

- Multiple fixes to regular expressions
- Fixed Windows header
- Fixes to spacing
- Fixed ```void``` method return
- Improved handling of UI/View classes
- Fix UI subdirectory bug (TIMOB-18519) ✔
- Fix UI header includes (TIMOB-18520) ✔
- Implement UIModule methods (TIMOB-18526) ✔
- Fix TitaniumKit Module.cpp template ✔

Module Generator fixes

---

Source/TitaniumKit/include/Titanium/UI/Animation.hpp
Source/TitaniumKit/src/UI/Animation.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

This just uses boost::optional for spot I needed it badly before: Ti.UI.Animation so we could tell if properties had specific values set by user or not.
https://jira.appcelerator.org/browse/TIMOB-18860

TIMOB-18860 Introduce Nullable type into TitaniumKit

---

Examples/Corporate/src/Package.wp.appxmanifest.in
Examples/NG/src/Package.store.appxmanifest.in
Examples/NG/src/Package.wp.appxmanifest.in
Examples/NMocha/src/Package.store.appxmanifest.in
Examples/NMocha/src/Package.wp.appxmanifest.in
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UI/Notification.hpp
Source/TitaniumKit/include/Titanium/UI/TextArea.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/Constants.cpp
Source/TitaniumKit/src/UI/Notification.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI.hpp
Source/UI/include/TitaniumWindows/UI/Notification.hpp
Source/UI/src/Notification.cpp
templates/build/Package.phone.appxmanifest.in
templates/build/Package.store.appxmanifest.in

https://jira.appcelerator.org/browse/TIMOB-18081

TIMOB-18081 Windows: Implement Ti.UI.Notification

---

Source/TitaniumKit/src/GlobalObject.cpp
Source/TitaniumKit/test/GlobalObjectTests.cpp
cli/commands/_build.js
templates/build/CMakeLists.txt.ejs

[TIMOB-18975](https://jira.appcelerator.org/browse/TIMOB-18975)
CommonJS module support described in [CommonJS Modules in Titanium](https://wiki.appcelerator.org/display/guides2/CommonJS+Modules+in+Titanium).
To test this, extract [commonjs.example.test1.zip](https://dl.dropboxusercontent.com/u/70836820/modules/commonjs.example.test1.zip) into your `YOUR_TITANIUM_SDK/modules/commonjs`.
Sample code:
```
var test = require('commonjs.example.test1');
Ti.API.info(new test.Example().hello());
```
Note that you also need `module` entry in your `tiapp.xml`.
```
<modules>
<module platform="commonjs">commonjs.example.test1'</module>
</modules>
```

[TIMOB-18975] CommonJS module

---

README.md

Update README. I meant to provide a how-to doc for these three types of developers.
. Write How-to doc for app developers
. Write How-to doc for module developers
. Write How-to doc for Ti API developers

[TIMOB-18950] Write How-To documentations

---

Tools/Scripts/build/build.js
Tools/Scripts/build/package.json
Tools/Scripts/build/test.js
cli/commands/_buildModule.js
templates/build/cmake/FindJavaScriptCore.cmake
templates/module/default/hooks/windows-module.js
templates/module/default/template/windows/CMakeLists.txt.ejs
templates/module/default/template/windows/build_and_test.sh.ejs
templates/module/default/template/windows/cmake/{{ModuleName}}_Config.cmake
templates/module/default/template/windows/include/{{ModuleName}}.hpp.ejs
templates/module/default/template/windows/manifest.ejs
templates/module/default/template/windows/src/{{ModuleName}}.cpp.ejs
templates/module/default/template/windows/test/CMakeLists.txt.ejs
templates/module/default/template/windows/timodule.xml

- Change architecture name (Win32->x86) 
- Fix zip archive error

[TIMOB-18937][TIMOB-18938][TIMOB-18939][TIMOB-18942] Add module support to the CLI - WIP

---

Tools/Scripts/build/build.js
Tools/Scripts/build/package.json
Tools/Scripts/build/test.js

Revert to see if this fixes the build error.

Revert Tools/Scripts/build.js

---

.gitignore
Tools/Scripts/build/test.js
cli/commands/_build.js
cli/hooks/wp-package.js
cli/hooks/ws-package.js
cli/hooks/ws-run.js
templates/build/CMakeLists.txt.ejs
templates/build/Package.phone.appxmanifest.in
templates/build/Package.store.appxmanifest.in

Still a WIP but it's working with some hard coded values. Let the sanity
check begin...
To test this at the moment, you'll need to add this to your tiapp.xml:
<property name="ti.windows.publishername" type="string">CN=Dawson Toth</property>
And when prompted during the build, use the password "**testing**" for your certs. A future iteration will prompt you for the password.
I've hacked together the dist-phonestore command:
ti build -p windows -T dist-phonestore
You'll also need the PR on windowslib -- https://github.com/appcelerator/windowslib/pull/16 -- in your node modules.
https://jira.appcelerator.org/browse/TIMOB-18087

[TIMOB-18087] Packaging

---

README.md

Add instruction for module development.

Update module README

---

Source/TitaniumKit/src/UIModule.cpp

Fix for [TIMOB-19012](https://jira.appcelerator.org/browse/TIMOB-19012).

[TIMOB-19012] Fix: TabGroup shows two Window at once

---

templates/module/default/template/windows/src/{{moduleIdAsIdentifier}}.cpp.ejs

Updated module template: SetParent at JSExportInitialize.

Module template: SetParent at JSExportInitialize

---

Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/detail/TiBase.hpp
Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/Module.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp

[TIMOB-19019](https://jira.appcelerator.org/browse/TIMOB-19019)
```javascript
title: 'PUSH'
});
// On Debug build this should cause assertion error,
// because it is guarded by TITANIUM_ASSERT(argument.IsBoolean())
// On Release build this will go through, as runtime tries to convert it to boolean forcibly
Ti.Platform.batteryMonitoring = 'this is not a boolean';
});
win.open();
```

Fix: assertion should not crash the app but show errrors

---

cli/commands/_build.js

Fix for [TIMOB-19029](https://jira.appcelerator.org/browse/TIMOB-19029).

[TIMOB-19029] Report errors on JS parse error

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UI/TextArea.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/TextArea.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI.hpp
Source/UI/include/TitaniumWindows/UI/TextArea.hpp
Source/UI/src/TextArea.cpp
Source/UI/src/TextField.cpp

https://jira.appcelerator.org/browse/TIMOB-19014

TIMOB-19014 Implement Titanium.UI.TextArea

---

Tools/Scripts/package.bat

Wipe the 'dist' and 'build' folders before we start build, to ensure no leftover artifacts

Try to fix build

---

Source/TitaniumKit/src/Filesystem/File.cpp

- Fix ```Ti.Filesystem.File.write()``` parameter validator
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19054)

[TIMOB-19054] Ti.Filesystem.File.write() 'append' parameter should be optional

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/Analytics.hpp
Source/TitaniumKit/src/Analytics.cpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/analytics.js

- Update payloads to Analytics V3
- Start analytics when the application is launched
- Implement ```ti.foreground``` and ```ti.background``` events
- Send ```ti.foreground``` and ```ti.background``` events when the applications resumes and suspends
- Use an event queue instead of database
- Only store events if they could not be sent
- Fix ```Ti.Analytics.lastEvent```
- Uses ```Ti.App.guid``` this means ```_app_info_.json``` must be present
https://github.com/appcelerator/titanium_mobile_windows/pull/313
```Javascript
btn_resume = Ti.UI.createButton({ title: 'Simulate Resume', top: 0}),
btn_pause = Ti.UI.createButton({ title: 'Simulate Suspend', top: 50 }),
btn_feature = Ti.UI.createButton({ title: 'Ti.Analytics.featureEvent()', top: 100 }),
btn_nav = …
```

[TIMOB-18994] Implement analytics - READY

---

Source/UI/src/ListView.cpp
Source/UI/src/TableView.cpp

- Use ```ItemClick``` instead of ```SelectionChanged``` for TableView and ListView
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19037)

[TIMOB-19037] Use ItemClick for TableView and ListView

---

Source/Sensors/include/TitaniumWindows/Geolocation.hpp
Source/Sensors/src/Geolocation.cpp

Fix for [TIMOB-19021](https://jira.appcelerator.org/browse/TIMOB-19021).
- Load `AppxManifest.xml` on startup and search for `location` device capability

Fix: Geolocation module always reporting location services disabled

---

Examples/NMocha/src/Assets/ti.database.test.js
Source/TitaniumKit/src/Database/ResultSet.cpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

Fix for [TIMOB-19078](https://jira.appcelerator.org/browse/TIMOB-19078) and  [TIMOB-19079](https://jira.appcelerator.org/browse/TIMOB-19079).
- TableView.setData throws Catastrophic Failure exception
- Database.ResultSet.fieldByName should be case insensitive
```javascript
var win = Ti.UI.createWindow({ layout: 'vertical' });
var button = Ti.UI.createButton({ title: 'Add' });
var tableData = [{ title: 'Apples' }, { title: 'Bananas' }, { title: 'Carrots' }, { title: 'Potatoes' }];
var table = Ti.UI.createTableView({/* data:tableData */ });
button.addEventListener('click', function () {
table.setData(tableData);
});
win.open();
var db = Ti.Database.open('mydb1Installed');
db.execute('CREATE TABLE IF NOT EXISTS people (name TEXT, phone_number TEXT, city …
```

Fix TableView and Database issue

---

Source/TitaniumKit/src/analytics.js
Source/UI/src/Window.cpp

- Send ```ti.background``` on app close via back button
- Fix analytics ```application/json``` bug
- Only ```Ti.Filesystem.getFile()``` once
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19082)

[TIMOB-19082] Fix analytics

---

cli/commands/_build/config/pfxPassword.js
cli/commands/_build/config/wsCert.js
cli/hooks/ws-package.js

https://jira.appcelerator.org/browse/TIMOB-19086
https://jira.appcelerator.org/browse/TIMOB-19091
https://jira.appcelerator.org/browse/TIMOB-19092
https://jira.appcelerator.org/browse/TIMOB-19093

[TIMOB-19086] [TIMOB-19091] [TIMOB-19092] [TIMOB-19093] Various PFX Fixes

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UI/Tab.hpp
Source/TitaniumKit/include/Titanium/UI/TabGroup.hpp
Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/Tab.cpp
Source/TitaniumKit/src/UI/TabGroup.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/include/TitaniumWindows/UI/TabGroup.hpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Tab.cpp
Source/UI/src/TabGroup.cpp
Source/UI/src/Window.cpp

READY FOR MERGE
- [TIMOB-18745](https://jira.appcelerator.org/browse/TIMOB-18745) Use Pivot and PivotItem for Tab and TabGroup UI proxies
- [TIMOB-19061](https://jira.appcelerator.org/browse/TIMOB-19061) TabGroup should be a subclass of Ti.UI.View
- [TIMOB-19062](https://jira.appcelerator.org/browse/TIMOB-19062) CommandBar does not work with TabGroup
```javascript
// this sets the background color of the master UIView (when there are no windows/tab groups on it)
Titanium.UI.setBackgroundColor('#000');
// create tab group
var tabGroup = Titanium.UI.createTabGroup();
//
// create base UI tab and root window
//
title: 'Tab 1',
});
var tab1 = Titanium.UI.createTab({
icon: 'KS_nav_views.png',
title: 'Tab 1',
window: win1
});
var …
```

Use Pivot and PivotItem for Tab and TabGroup

---

Source/TitaniumKit/src/ApplicationBuilder.cpp

https://jira.appcelerator.org/browse/TIMOB-19125

[TIMOB-19125] Windows: console.debug is not implemented

---

Examples/NMocha/src/Assets/ti.filesystem.test.js
Source/Titanium/include/TitaniumWindows/File.hpp
Source/Titanium/src/File.cpp
Source/TitaniumKit/src/FilesystemModule.cpp

https://jira.appcelerator.org/browse/TIMOB-19128
```javascript
var btn = Ti.UI.createButton({
title: 'Click'
});
btn.addEventListener('click', function (e) {
var dir1 = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'dir1');
dir1.createDirectory();
console.info('Working fine');
var dir2 = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'sub', 'dir2');
dir2.createDirectory();
console.info('Will have crashed on Windows');
});
win.add(btn);
win.open();
```

Fix TIMOB-19128 Windows: Ti.Filesystem.File.createDirectory will fail if parent directory does not exist

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

Addition to https://github.com/appcelerator/titanium_mobile_windows/pull/349
- Scale PPI in accordance to dpiX/dpiY

[TIMOB-19119] Fix layout PPI value

---

Source/TitaniumKit/src/analytics.js

- Fix timestamp difference calculation for seconds
- Fix ```data``` object in event
[TIMOB-19083](https://jira.appcelerator.org/browse/TIMOB-19083)
[TIMOB-19179](https://jira.appcelerator.org/browse/TIMOB-19179)

[TIMOB-19083][TIMOB-19179] Fix analytics

---

apidoc/WindowsOnly/Titanium.UI.Windows.AppBarButton.yml
apidoc/WindowsOnly/Titanium.UI.Windows.AppBarSeparator.yml
apidoc/WindowsOnly/Titanium.UI.Windows.AppBarToggleButton.yml
apidoc/WindowsOnly/Titanium.UI.Windows.CommandBar.yml
apidoc/WindowsOnly/Titanium.UI.Windows.SystemIcon.yml
apidoc/WindowsOnly/Titanium.UI.Windows.yml

Addresses TIDOC-2243, TIDOC-2244 and TIDOC-2246

[TIDOC-224x] Improvements for AppBarSeparator and SystemIcons

---

Source/TitaniumKit/include/Titanium/App.hpp
Source/TitaniumKit/src/App.cpp

- If ```_app_info_.json``` does not exist, don't keep attempting to load it
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19186)

[TIMOB-19186] Optimize getAppInfo()

---

Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp
Source/TitaniumKit/src/UI/TextField.cpp

Fix for [TIMOB-19124](https://jira.appcelerator.org/browse/TIMOB-19124).
```javascript
win.add(Ti.UI.createTextField({
top: 100,
height: 50,
value: undefined
}));
win.open();
```

Fix: Ti.UI.TextField.value = undefined will display value as text

---

Source/TitaniumKit/src/UI/Label.cpp

- Fix ```Ti.UI.Label``` ```undefined``` properties
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19188)

[TIMOB-19188] Fix Ti.UI.Label 'undefined' fields

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/Analytics.hpp
Source/TitaniumKit/src/Analytics.cpp
Source/TitaniumKit/src/analytics.js

- Delay app suspension to allow analytics to receive a response from the server
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19176)

[TIMOB-19176] Allow analytics to receive a response before suspending

---

Source/UI/include/TitaniumWindows/UI/TableViewRow.hpp
Source/UI/src/TableViewRow.cpp

Fix for [TIMOB-19142](https://jira.appcelerator.org/browse/TIMOB-19142).
```javascript
data: [{
title: 'Title',
color: 'red'
}]
});
table.appendRow(Ti.UI.createTableViewRow({
title: 'Another',
color: 'red'
}));
win.open();
```

Fix: Ti.UI.TableViewRow.color does not work

---

cli/hooks/wp-run.js

Fix for [TIMOB-19077](https://jira.appcelerator.org/browse/TIMOB-19077).

Fix: Logging does not work when using device

---

Tools/Scripts/module_generator/generate.js
Tools/Scripts/module_generator/module_template/TitaniumKit/src/Module.cpp

- Fix ```TitaniumWindows.cpp``` regex signature
- Fixes to ```TitaniumKit``` ```Module.cpp``` template

Update module generator

---

Source/LayoutEngine/include/LayoutEngine/LayoutEngine.hpp
Source/LayoutEngine/src/Element.cpp
Source/LayoutEngine/src/Node.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewInsertOrReplaceParams.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewInsertOrReplaceParams.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-19355](https://jira.appcelerator.org/browse/TIMOB-19355).
```javascript
var win = Ti.UI.createWindow({backgroundColor:'black'});
top: 0, left: 0,
width: 100, height: 100
});
top: 30, left: 30,
width: 100, height: 100
});
top: 60, left: 60,
width: 100, height: 100
});
win.add(view3);
var commandBar = Ti.UI.createView({
width: Ti.UI.FILL, height: '10%',
bottom: 0, left: 0,
layout:'horizontal'
});
var view1Top = Ti.UI.createButton({ title: ' insert ',   width: '30%'});
var view2Top = Ti.UI.createButton({ title: ' replace ', width: '30%' });
var view3Top …
```

Fix: Ti.UI.View.insertAt and replaceAt not working

---

Source/TitaniumKit/src/GlobalObject.cpp

`require` should have been enclosed by anonymous function.

Fix: require should not pollute global object

---

Source/TitaniumKit/include/Titanium/UI/Switch.hpp
Source/TitaniumKit/src/UI/Switch.cpp
Source/UI/include/TitaniumWindows/UI/Switch.hpp
Source/UI/src/Switch.cpp

https://jira.appcelerator.org/browse/TIMOB-19131
Also added enabled, color properties.

TIMOB-19131 Implement Ti.UI.Switch.titleOff and Ti.UI.Switch.titleOn

---

Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-19368](https://jira.appcelerator.org/browse/TIMOB-19368)
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });
backgroundImage:'http://image.tmdb.org/t/p/w780//3FweBee0xZoY77uO1bhUOlQorNH.jpg',
width: '50%', height:'50%'
});
win.add(view);
win.open()
```

Add: backgroundImage for View subclasses

---

README.md

Update README with respect to [AC-290](https://jira.appcelerator.org/browse/AC-290).

Update Visual Studio requirement

---

Examples/Movies/src/Assets/alloy/controllers/views/list_cell.js
Examples/Movies/src/Assets/youtube.js
Source/TitaniumKit/src/UI/Animation.cpp
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fixes to make Movies app work. Fix for [TIMOB-19426](https://jira.appcelerator.org/browse/TIMOB-19426) and [TIMOB-19438](https://jira.appcelerator.org/browse/TIMOB-19438)
- Fix: animate doesn't work when duration < 1 sec
- Fix: Movie home animation
- Fix: ScrollView contentOffset doesn't work
- Fix: VideoView requires new Window

Fix Movies app layout issue

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.stream.test.js
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/Blob.hpp
Source/TitaniumKit/include/Titanium/BlobStream.hpp
Source/TitaniumKit/include/Titanium/Buffer.hpp
Source/TitaniumKit/include/Titanium/BufferStream.hpp
Source/TitaniumKit/include/Titanium/Filesystem/FileStream.hpp
Source/TitaniumKit/include/Titanium/IOStream.hpp
Source/TitaniumKit/include/Titanium/Stream.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/Blob.cpp
Source/TitaniumKit/src/BlobStream.cpp
Source/TitaniumKit/src/Buffer.cpp
Source/TitaniumKit/src/BufferStream.cpp
Source/TitaniumKit/src/Filesystem/FileStream.cpp
Source/TitaniumKit/src/IOStream.cpp
Source/TitaniumKit/src/Stream.cpp

[TIMOB-19493](https://jira.appcelerator.org/browse/TIMOB-19493), [TIMOB-19495](https://jira.appcelerator.org/browse/TIMOB-19495), [TIMOB-19494](https://jira.appcelerator.org/browse/TIMOB-19494) and [TIMOB-19496](https://jira.appcelerator.org/browse/TIMOB-19496).

Implement Ti.Stream, IOStream, BufferStream and BlobStream

---

Source/Ti/include/TitaniumWindows/AppModule.hpp
Source/Ti/src/AppModule.cpp
Source/TitaniumKit/include/Titanium/App.hpp
Source/TitaniumKit/src/App.cpp

- Implement _hidden_ API ```Titanium.App._restart()``` to exit application.
```Javascript
var win = Ti.UI.createWindow({}),
btn = Ti.UI.createButton({title: 'EXIT'});
btn.addEventListener('click', function(e) {
Ti.App._restart();
});
win.add(btn);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19122)

[TIMOB-19122] Implement Ti.App._restart()

---

cli/lib/templates/js_to_native_class.cpp

Handle conversion to Platform::Object slightly special and check if the JSValue is a JSString and convert to Platform::String rather than try to unwrap in that case. This is a more general fix than just hacking the Content property for ContentControl.  There's certainly possible other cases where users pass in JSDates or Numbers or generic JSObjects that aren't handled, but I think that they may be pretty rare.
https://jira.appcelerator.org/browse/TIMOB-19516
The important/fix below is setting the button.Content to a string value - which previously broke.
```c++
var Window = require('Windows.UI.Xaml.Window'),
TextBlock = require('Windows.UI.Xaml.Controls.TextBlock'),
Button = require('Windows.UI.Xaml.Controls.Button'),
Canvas = require('Windows.UI.Xaml.Controls.Canvas'),
window = …
```

TIMOB-19516 Windows: Support setting Content property of ContentControl subclasses with a simple string content

---

Examples/NG/CMakeLists.txt
Examples/NG/src/Package.win10.appxmanifest.in
Source/Global/src/GlobalObject.cpp
Source/Media/src/Media.cpp
Source/Media/src/Media/AudioRecorder.cpp
Source/Network/src/HTTPClient.cpp
Source/Sensors/src/Geolocation.cpp
Source/Sensors/src/ShakeGestureHelper.cpp
Source/Ti/include/TitaniumWindows/Contacts/Group.hpp
Source/Ti/include/TitaniumWindows/Contacts/Person.hpp
Source/Ti/src/Codec.cpp
Source/Ti/src/Contacts.cpp
Source/Ti/src/Contacts/Group.cpp
Source/Ti/src/Contacts/Person.cpp
Source/Ti/src/Platform.cpp
Source/Titanium/src/File.cpp
Source/TitaniumKit/include/Titanium/detail/TiBase.hpp
Source/UI/src/ActivityIndicator.cpp
Source/UI/src/Clipboard.cpp
Source/UI/src/ProgressBar.cpp
Source/UI/src/ScrollView.cpp
Source/Utility/src/Utility.cpp
Tools/Scripts/generate_project.js
cli/commands/_build/generate.js
templates/build/CMakeLists.txt.ejs
templates/build/Package.win10.appxmanifest.in.ejs

[TIMOB-19677](https://jira.appcelerator.org/browse/TIMOB-19677) and [TIMOB-19678](https://jira.appcelerator.org/browse/TIMOB-19678)
Fix compile error when targeting Windows 10 Store App.

Fix: compile targeting Windows 10 Store

---

Tools/Scripts/setup.js

- Update to ```JavaScriptCore-Windows-1439837221.zip``` in ```setup.js```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19719)

[TIMOB-19719] Update JavaScriptCore in setup.js

---

templates/build/Package.phone.appxmanifest.in.ejs

Remove unused capability from phone package

---

Tools/Scripts/build/package.json
Tools/Scripts/build/test.js

- Try to always use a Windows Phone 8.1 Emulator for running tests
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19856)

[TIMOB-19856] Select 8.1 emulator for running tests

---

Source/UI/src/Window.cpp

- Support the input of arrays into ```Titanium.UI.Window.add();```
```Javascript
var win = Titanium.UI.createWindow(),
data = [
{
'top': 100,
'text': 'label 1'
},
{
'top': 200,
'text': 'label 2'
}
],
labels = [];
function createLabel(data) {
text: data.text,
color: '#999',
top: data.top
});
return label;
}
for (var i = 0; i < data.length; i++) {
labels.push(createLabel(data[i]));
}
win.add(labels);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19394)

[TIMOB-19394] Allow array input for Ti.UI.Window.add()

---

Tools/Scripts/build/build.js
cli/commands/_build/generate.js
templates/build/CMakeLists.txt.ejs

https://jira.appcelerator.org/browse/TIMOB-20050
https://jira.appcelerator.org/browse/TIMOB-20051

Build Windows 10 libraries to separate distribution folder, use those libraries for Win 10 app builds

---

cli/commands/_build/config/vstarget.js

https://jira.appcelerator.org/browse/TIMOB-20057

TIMOB-20057 Windows: Unable to build for any platform if there is no Visual Studio installed

---

cli/lib/info.js

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19045)
* Remove unnecessary nesting of Windows data which broke Studios ability to parse Windows info
```
{
"windows": {
"tisdk": "5.1.2.v20151208161231",
"windows": {
"detectVersion": "3.0",
"issues": [],
}
}
}
```
is now 
````
{
"windows": {
"detectVersion": "3.0",
"issues": [],
"assemblies": {
}
}
````
* Change the render method due to the above changes

[TIMOB-19045] Refactor info.js to remove nesting of data

---

cli/lib/info.js

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19045)
5_1_X backport of #500

[TIMOB-19045] Refactor info.js to remove nesting of data (5_1_X)

---

cli/commands/_build/compile.js
cli/commands/_build/config/pfxPassword.js
cli/commands/_build/config/wpProductId.js
cli/commands/_build/config/wpSDK.js
cli/commands/_build/config/wsCert.js
cli/hooks/cert.js
cli/hooks/package.js
cli/hooks/wp-run.js

Behaves a little oddly around prompting for cert still...
https://jira.appcelerator.org/browse/TIMOB-20097
Needs appcelerator/windowslib#28

First working version of Windows 10 mobile emulator

---

Source/TitaniumKit/include/Titanium/UI/Tab.hpp
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/src/UI/Tab.cpp
Source/TitaniumKit/src/UI/TabGroup.cpp
Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/include/TitaniumWindows/UI/TabGroup.hpp
Source/UI/src/Tab.cpp
Source/UI/src/TabGroup.cpp

Fix for [TIMOB-19960](https://jira.appcelerator.org/browse/TIMOB-19960)
- TabGroup.barColor
- TabGroup.tabsBackgroundColor
- TabGroup.tabsBackgroundImage
- TabGroup.tabsBackgroundDisabledColor
- TabGroup.tabsBackgroundDisabledImage
- TabGroup.tabsBackgroundFocusedColor
- TabGroup.tabsBackgroundFocusedImage
- TabGroup.tabsBackgroundSelectedColor
- TabGroup.tabsBackgroundSelectedImage
- TabGroup.activeTabBackgroundColor
- TabGroup.activeTabBackgroundImage
- TabGroup.activeTabBackgroundDisabledColor
- TabGroup.activeTabBackgroundDisabledImage
- TabGroup.activeTabBackgroundFocusedColor
- TabGroup.activeTabBackgroundFocusedImage
- TabGroup.activeTabBackgroundSelectedColor
- TabGroup.activeTabBackgroundSelectedImage
- Tab.backgroundDisabledColor
- Tab.backgroundDisabledImage
- …

Background color/image for Ti.UI.Tab and TabGroup

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.webview.test.html
Examples/NMocha/src/Assets/ti.ui.webview.test.js
Source/UI/src/WebView.cpp
Source/Utility/include/TitaniumWindows/Utility.hpp
Source/Utility/src/Utility.cpp

Fix for [TIMOB-20143](https://jira.appcelerator.org/browse/TIMOB-20143)
Test Case: [ti.ui.webview.test.js](https://github.com/infosia/titanium_mobile_windows/blob/c15555e7a035567c41655d861a638866c68ab88b/Examples/NMocha/src/Assets/ti.ui.webview.test.js)

Fix: Titanium.UI.WebView can't load local html page

---

Source/Ti/src/Platform.cpp

- Fix ```KnownUserProperty``` enum to retrieve username
```XML
..
<windows>
<Capabilities>
<uap:Capability Name="userAccountInformation" />
<windows>
...
```
```Javascript
lbl = Ti.UI.createLabel({text: Ti.Platform.username});
win.add(lbl);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20173)

[TIMOB-20173] Fix Ti.Platform.username on Windows 10

---

Source/UI/include/TitaniumWindows/UI/ScrollableView.hpp
Source/UI/src/ScrollableView.cpp

- Implement missing ```ScrollableView``` events
- ```dragend``` ```dragstart``` ```scroll``` ```scrollend```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19958)

[TIMOB-19958] Implement missing ScrollableView events

---

Source/Map/CMakeLists.txt
Source/Map/include/TitaniumWindows/Map/View.hpp
Source/Map/src/View.cpp
Source/Ti/include/TitaniumWindows/App/Properties.hpp
Source/Ti/src/Properties.cpp
cli/commands/_build/copy.js

- Load windows specific properties into ```_app_prop_.json``` from ```tiapp.xml```
- Obtain and use ```mapservicetoken``` from ```_app_prop_.json```
```XML
...
<windows>
<mapservicetoken>VrSrmXR8B5bgklWrs0CK_w</mapservicetoken>
</windows>
...
```
```Javascript
view = Ti.Map.createView({
mapType: Titanium.Map.NORMAL_TYPE,
region: {latitude:37.390749, longitude:-122.081651}
});
win.add(view);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20162)

[TIMOB-20162] Obtain mapservicetoken from tiapp.xml

---

Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/Label.cpp

Fix for [TIMOB-20195](https://jira.appcelerator.org/browse/TIMOB-20195).
vertical layout +  (textAlign:left, verticalAlign:top)
```javascript
var view = Ti.UI.createView({width:'80%', height:'80%', backgroundColor:'blue', layout:'vertical'});
var lbl = Ti.UI.createLabel({
text: ' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vulputate neque eget placerat commodo. Donec accumsan elit diam, sed convallis nisl feugiat at. Nulla vitae volutpat felis.',
color: 'yellow',
});
view.add(lbl);
win.add(view);
win.open();
```
default: (textAlign:left, verticalAlign:top)
```javascript
var view = Ti.UI.createView({width:'80%', height:'80%', …
```

Fix: Label.textAlign and verticalAlign does not work with Ti.UI.FILL - READY

---

Tools/Scripts/build/test.js
cli/commands/_build/generate.js

https://jira.appcelerator.org/browse/TIMOB-20231

Support differing capabilities per platform/SDK version

---

Source/Network/src/HTTPClient.cpp

Fix for [TIMOB-20239](https://jira.appcelerator.org/browse/TIMOB-20239).
Implement `HTTPClient` username/password.
```javascript
var username = "username";
var password = "pa33w0rd";
var domain = "https://some.where.com/auth/";
function doClick(e) {
var client = Ti.Network.createHTTPClient({
username : username,
password : password,
domain : domain,
onload : function(e) {
alert('success' + this.responseText);
},
onerror : function(e) {
Ti.API.info("Error on Authentication" + e.error);
alert('error in  Authentication');
Titanium.API.info('Status: ' + this.status);
Titanium.API.info('ResponseText: ' + this.responseText);
Titanium.API.info('connectionType: ' + this.connectionType);
},
onreadystatechange : function(e) {
Titanium.API.info('Status: ' + this.status); …
```

Fix: HTTPClient user/password authentication does not work

---

Source/UI/include/TitaniumWindows/UI/AlertDialog.hpp
Source/UI/src/AlertDialog.cpp

- Implemented the ability to hide active alert dialog's
```Javascript
var a = Ti.UI.createAlertDialog({title: 'Alert', message: 'This will hide in 3 seconds'});
a.show();
// hide alert after 3 seconds
a.hide();
}, 3000);
// show alert after another 3 seconds
a.show();
}, 6000);
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19946)

[TIMOB-19946] Implement Ti.UI.AlertDialog.hide() functionality

---

Source/UI/include/TitaniumWindows/UIModule.hpp
apidoc/whitelist.txt

- Amend ```whitelist.txt``` to fix parity report
- Remove ```TITANIUM_MODULE_UNIMPLEMENTED``` definition for ```Titanium.UI.AttributedString```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20350)

[TIMOB-20350] Amend parity report

---

cli/hooks/ws-run.js

Requires appcelerator/windowslib#31 be merged, version bumped and released and then put in appcelerator/titanium_mobile master branch's package.json and merged.
JIRA ticket: https://jira.appcelerator.org/browse/TIMOB-20370
Basically when you launched a desktop app before it'd just launch it and close the CLI process. Now we don't exit and we do some magic voodoo to make the app exempt from the network isolation loopback IP blocking that's done by default for Windows Runtime apps. (See https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx )
So there is still a bit of a difference between phone emulator and desktop apps in that we poll constantly to know when the emulator is killed and then kill the CLI process. We DO NOT do the same thing for desktop apps yet. We likely …

[TIMOB-20370] Windows: Running desktop app doesn't show logs in console

---

Source/UI/src/View.cpp

https://jira.appcelerator.org/browse/TIMOB-20382

Fix TIMOB-20382 - font caching was broken on lookups of cached font

---

Source/TitaniumKit/src/UI/View.cpp

- Implement ```Titanium.UI.View.convertPointToView``` functionality into ```TitaniumKit```
```Javascript
a = Ti.UI.createView({backgroundColor:'red'}),
b = Ti.UI.createView({ top: '100', backgroundColor: 'blue' });
a.add(b);
// the layout MUST be loaded before we can calculate any points
b.addEventListener('postlayout', function () {
Ti.API.info(JSON.stringify(b.convertPointToView({ x: 123, y: 23 }, a), null, ' '));
});
win.add(a);
win.open();
```
```
[INFO] {
"x": 123,
"y": 123
}
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20241)

[TIMOB-20241] Implement Titanium.UI.View.convertPointToView()

---

cli/hooks/package.js
cli/hooks/wp-run.js

Cherry-Pick #531, backport to 5_2_X.
[TIMOB-20172](https://jira.appcelerator.org/browse/TIMOB-20172)

[5_2_X] [TIMOB-20172] Cannot package for the phonestore or winstore

---

apidoc/ti_win_yaml.js
apidoc/whitelist.txt

- Fixed a bug in ```ti_win_yaml.js``` where it would ignored the last entry of the ```whitelist.txt```
- Updated ```whitelist.txt```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20350)

[TIMOB-20350] Fix parity report whitelist

---

Examples/NMocha/src/Assets/ti.locale.test.js
Source/Ti/include/TitaniumWindows/Locale.hpp
Source/Ti/src/Locale.cpp
Source/TitaniumKit/src/Locale.cpp

[TIMOB-20478](https://jira.appcelerator.org/browse/TIMOB-20478)
Implement Ti.Locale properties:
- `Ti.Locale.currentCountry`
- `Ti.Locale.currentLanguage`
- `Ti.Locale.currentLocale`

Implement Ti.Locale properties

---

Source/Media/include/TitaniumWindows/Media/AudioRecorder.hpp
Source/Media/src/Media/AudioRecorder.cpp

- Finished implementing ```Titanium.Media.AudioRecorder```
- Saves audio recordings into _Music Library_
- Requires ```microphone``` ```webcam``` and ```musicLibrary``` capabilities
- Updated [wiki](https://wiki.appcelerator.org/display/guides2/tiapp.xml+and+timodule.xml+Reference#tiapp.xmlandtimodule.xmlReference-AudioRecorder)
```Javascript
var audioRecorder = Titanium.Media.createAudioRecorder(),
win = Titanium.UI.createWindow({ backgroundColor: 'red' }),
record_btn = Titanium.UI.createButton({ title: 'record/stop', top: '33%' }),
pause_btn = Titanium.UI.createButton({ title: 'pause/resume', top: '66%' });
record_btn.addEventListener('click', function () {
audioRecorder.recording ? audioRecorder.stop() : audioRecorder.start();
});
pause_btn.addEventListener('click', function () {
if …
```

[TIMOB-17917] Implement Titanium.Media.AudioRecorder

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.searchbar.test.js
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/TiModule.hpp
Source/TitaniumKit/include/Titanium/UI/Constants.hpp
Source/TitaniumKit/include/Titanium/UI/ListSection.hpp
Source/TitaniumKit/include/Titanium/UI/ListView.hpp
Source/TitaniumKit/include/Titanium/UI/SearchBar.hpp
Source/TitaniumKit/include/Titanium/UI/TableView.hpp
Source/TitaniumKit/include/Titanium/UI/TableViewRow.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/TiModule.cpp
Source/TitaniumKit/src/UI/Constants.cpp
Source/TitaniumKit/src/UI/ListSection.cpp
Source/TitaniumKit/src/UI/ListView.cpp
Source/TitaniumKit/src/UI/SearchBar.cpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/TitaniumKit/src/UI/TableViewRow.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI/SearchBar.hpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/include/TitaniumWindows/UI/TableViewRow.hpp
Source/UI/src/SearchBar.cpp
Source/UI/src/TableView.cpp
Source/UI/src/TableViewRow.cpp

[TIMOB-17972](https://jira.appcelerator.org/browse/TIMOB-17972)
```javascript
layout:'vertical'
});
var searchBar = Ti.UI.createSearchBar({
height: '10%'
});
var sectionFruit = Ti.UI.createTableViewSection({ headerTitle: 'Fruit' });
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Apples' }));
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Bananas' }));
var sectionVeg = Ti.UI.createTableViewSection({ headerTitle: 'Vegetables' });
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Carrots' }));
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Potatoes' }));
data: [sectionFruit, sectionVeg],
search: searchBar,
width: Ti.UI.FILL, height: '80%'
});
win.add(searchBar); …
```

[TIMOB-17972] Implement Ti.UI.SearchBar

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.searchbar.test.js
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/TiModule.hpp
Source/TitaniumKit/include/Titanium/UI/Constants.hpp
Source/TitaniumKit/include/Titanium/UI/ListSection.hpp
Source/TitaniumKit/include/Titanium/UI/ListView.hpp
Source/TitaniumKit/include/Titanium/UI/SearchBar.hpp
Source/TitaniumKit/include/Titanium/UI/TableView.hpp
Source/TitaniumKit/include/Titanium/UI/TableViewRow.hpp
Source/TitaniumKit/include/Titanium/UIModule.hpp
Source/TitaniumKit/src/TiModule.cpp
Source/TitaniumKit/src/UI/Constants.cpp
Source/TitaniumKit/src/UI/ListSection.cpp
Source/TitaniumKit/src/UI/ListView.cpp
Source/TitaniumKit/src/UI/SearchBar.cpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/TitaniumKit/src/UI/TableViewRow.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI/SearchBar.hpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/include/TitaniumWindows/UI/TableViewRow.hpp
Source/UI/src/SearchBar.cpp
Source/UI/src/TableView.cpp
Source/UI/src/TableViewRow.cpp

[5_3_X] [TIMOB-17972] Implement Ti.UI.SearchBar

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Button.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[5_3_X][TIMOB-20386] Fix: View based click event is not responsive #578

---

Examples/NMocha/src/Assets/ti.ui.window.test.js
Source/UI/src/Window.cpp

Fix for [TIMOB-20600](https://jira.appcelerator.org/browse/TIMOB-20600)
```javascript
var win1 = Ti.UI.createWindow({ backgroundColor: 'yellow' }),
win2 = Ti.UI.createWindow({ backgroundColor: 'blue' }),
win3 = Ti.UI.createWindow({ backgroundColor: 'gray' });
win1.addEventListener('open', function (e) {
win2.open();
win3.open();
win2.close();
win3.close();
win1.backgroundColor = 'green';
// and then pushing "back" hardware button should exit the app
}, 1000);
}, 1000);
}, 1000);
});
win1.open();
```

[TIMOB-20600] Fix: Window.close throws "unknown exception"

---

Source/Network/src/HTTPClient.cpp

Attempt to fix wonky HTTPClient

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/589
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20612)

[TIMOB-20612][5_3_X] postlayout events not firing

---

Source/Network/src/HTTPClient.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/591

[5_3_X] Fix HTTPClient configureTimeout()

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Source/TitaniumKit/include/Titanium/UI/ImageView.hpp
Source/TitaniumKit/src/UI/ImageView.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp
Source/Utility/src/Utility.cpp

Fix for [TIMOB-20609](https://jira.appcelerator.org/browse/TIMOB-20609)
- ImageView.image from WIndows-style path such as `C:\Data\Users\DefApps\APPDATA\Local\Packages\etc\etc`
- ~~ImageView.image from `Ti.Blob`~~
- ~~ImageView.image from `Ti.Filesystem.File`~~

[TIMOB-20609] ImageView.image from Windows-style path

---

Examples/NMocha/src/Assets/ti.ui.view.test.js
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-20598](https://jira.appcelerator.org/browse/TIMOB-20598)
```javascript
var box = Ti.UI.createView({
left: 100,
height: '100',
width: '100'
});
var pin1 = Ti.UI.createView({
left: 150,
height: '140',
width: '6'
});
var pin2 = Ti.UI.createView({
left: 200,
height: '140',
width: '6'
});
var pin3 = Ti.UI.createView({
left: 250,
height: '140',
width: '6'
});
win.add(pin1);
win.add(pin2);
win.add(pin3);
win.add(box);
var pos = 100;
box.addEventListener('click', function () {
pos += 50;
var a = Ti.UI.createAnimation({
left: pos,
duration: 2000,
});
box.animate(a);
});
win.open();
```

[TIMOB-20598] views not animating correctly

---

Examples/NMocha/src/Assets/ti.ui.picker.test.js
Source/UI/include/TitaniumWindows/UI/Picker.hpp
Source/UI/include/TitaniumWindows/UI/PickerColumn.hpp
Source/UI/include/TitaniumWindows/UI/PickerRow.hpp
Source/UI/src/Picker.cpp
Source/UI/src/PickerColumn.cpp
Source/UI/src/PickerRow.cpp

Fix for [TIMOB-20599](https://jira.appcelerator.org/browse/TIMOB-20599)
```javascript
function onTest() {
var column = picker.columns[0];
var rows = column.rows;
for (var i = 0; i < rows.length; i++) {
column.removeRow(rows[i]);
};
var data = [];
data[0] = Ti.UI.createPickerRow({ title: '2 Bananas' });
data[1] = Ti.UI.createPickerRow({ title: '2 Strawberries' });
data[2] = Ti.UI.createPickerRow({ title: '2 Mangos' });
data[3] = Ti.UI.createPickerRow({ title: '2 Grapes' });
picker.add(data);
}
var picker = Ti.UI.createPicker({
top: 50
});
var data = [];
data[0] = Ti.UI.createPickerRow({ title: 'Bananas' });
data[1] = Ti.UI.createPickerRow({ title: 'Strawberries' });
data[2] = Ti.UI.createPickerRow({ title: 'Mangos' });
data[3] = …
```

[TIMOB-20599] Picker updating data throws unknown exception

---

Examples/NMocha/src/Assets/ti.ui.view.test.js

Workaround to suppress unit test failure on Windows 10 Store.

Workaround for mocha test failure for Windows 10 Store app

---

Source/UI/src/ListView.cpp
Source/UI/src/TabGroup.cpp
Source/UI/src/TableView.cpp
Source/Utility/src/Utility.cpp

[5_3_X] Use return value from Collection.IndexOf to check if it's found

---

Source/TitaniumKit/include/Titanium/UI/ProgressBar.hpp
Source/TitaniumKit/src/UI/ProgressBar.cpp
Source/UI/include/TitaniumWindows/UI/ProgressBar.hpp
Source/UI/src/ProgressBar.cpp

- Implement ``Titanium.UI.ProgressBar`` properties ``color`` ``tinitColor`` ``trackTintColor``
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'black' }),
pb = Ti.UI.createProgressBar({
value: 50,
message: 'test', color: 'white',
tintColor: 'blue', trackTintColor: 'red'
});
win.add(pb);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20621)

[TIMOB-20621] Implement Ti.UI.ProgressBar color, tintColor, trackTintColor

---

cli/commands/_build/config/wsCert.js

Fix for [TIMOB-23171](https://jira.appcelerator.org/browse/TIMOB-23171)

[TIMOB-23171] Cannot package Alloy app for dist-winstore

---

Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Window.cpp

Implement Ti.UI.Window.orientationModes ([TIMOB-23143](https://jira.appcelerator.org/browse/TIMOB-23143))
```javascript
orientationModes: [Ti.UI.LANDSCAPE_LEFT]
});
var label = Ti.UI.createLabel({text:'Hello, World'});
win.open();
```

[TIMOB-23143] Implement Ti.UI.Window.orientationModes

---

cli/commands/_build/config/deviceID.js
cli/commands/_build/utils.js

Fix `xd` and `de` validation for #620

[TIMOB-20571] Use device or emulator wpsdk when possible

---

cli/commands/_build/config/wpSDK.js

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/623
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23192)

[5_3_X][TIMOB-23192] Filter unsupported Windows SDK 8.0

---

cli/commands/_build/utils.js

Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/622
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20572)

[5_3_X][TIMOB-20572] Only list local devices

---

cli/commands/_build/utils.js

- Filter out any devices that are not connect by USB
```
appc run -p windows -T wp-device
appc run -p windows -T wp-device
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20572)

[TIMOB-20572] Only list local devices

---

Examples/NMocha/src/Assets/ti.app.windows.backgroundservice.test.js
Source/Ti/include/TitaniumWindows/App/BackgroundService.hpp
Source/Ti/include/TitaniumWindows/App/BackgroundServiceTask.hpp
Source/Ti/src/App/BackgroundService.cpp
Source/Ti/src/App/BackgroundServiceTask.cpp
templates/module/default/template/windows/src/{{moduleIdAsIdentifier}}.cpp.ejs

Background service extension by native module: [TIMOB-23205](https://jira.appcelerator.org/browse/TIMOB-23205)
See [Windows Background Service Quick Start](https://wiki.appcelerator.org/display/guides2/Windows+Background+Service+Quick+Start) documentation on how to implement/test background task.

[TIMOB-23205] Background service extension by native module

---

Source/Ti/src/Codec.cpp
Source/TitaniumKit/include/Titanium/Buffer.hpp
Source/TitaniumKit/src/Buffer.cpp

 [5_3_X] [TIMOB-23222] Fix crash at Ti.Codec.decodeNumber

---

Source/TitaniumKit/include/Titanium/API.hpp
Source/TitaniumKit/src/API.cpp

[5_3_X] [TIMOB-23237] Fix Inconsistencies in Ti.API.log

---

templates/module/default/hooks/windows-module.js

[TIMOB-23248](https://jira.appcelerator.org/browse/TIMOB-23248)
Titanium CLI should choose selected Visual Studio for cmake generator.
```bash
> appc new -n TIMOB23246 --id com.appcelerator.TIMOB23246
? What type of project are you creating?
3) Titanium Module (timodule)
Answer: 3
```

[TIMOB-23248] module cmake generator should use selected Visual Studio

---

Examples/NMocha/src/Assets/ti.ui.view.test.js

DO NOT MERGE THIS
[TIMOB-23164](https://jira.appcelerator.org/browse/TIMOB-23164)
Trying to see how mocha tests failed because I can not reproduce this locally.

Enable TIMOB-23164 View animation tests

---

Source/TitaniumKit/include/Titanium/API.hpp
Source/TitaniumKit/src/API.cpp

[TIMOB-23237] Show custom log level in DEBUG

---

Examples/NMocha/src/Assets/ti.ui.view.test.js

They start failing again. disabling.

[5_3_X] Disable TIMOB-23164 View animation tests again

---

templates/module/default/hooks/windows-module.js

Cherry-pick #641 for 5_3_X
```
appc new -p windows -l trace --sdk 5.3.0.v2016xxxxx
cd xxx/windows
ti build -t ws-local -l trace --sdk 5.3.0.v2016xxxx -p windows
```

[5_3_X] [TIMOB-23248] module cmake generator should use selected Visual Studio

---

Examples/NMocha/src/Assets/ti.ui.view.test.js

Disable TIMOB-23164 View animation tests again

---

Source/Ti/src/Locale.cpp

https://jira.appcelerator.org/browse/TIMOB-23301

[5_3_X] [TIMOB-23301] Windows: Bug in Ti.Locale constructor

---

Source/Ti/src/Locale.cpp

https://jira.appcelerator.org/browse/TIMOB-23301

[master] [TIMOB-23301] Windows: Bug in Ti.Locale constructor

---

Source/Media/src/Media.cpp

Fix save location of files, use init settings on MediaCapture so that we don't need wrong/unnecessary capabilities set on apps. i.e. don't require videosLibrary or microphone capability for taking pictures with camera or a screenshot.
Found when looking at #654

Ti.media fixes to avoid use of wrong capabilties

---

Source/TitaniumKit/src/UI/SearchBar.cpp

Use full namespace for name of class
https://jira.appcelerator.org/browse/TIDOC-2513

[TIDOC-2513] Merge Ti.UI.SearchBar with Titanium.UI.SearchBar pages

---

apidoc/Titanium/UI/Tab.yml
apidoc/Titanium/UI/TabGroup.yml

[TIMOB-19960] Update docs for Tab/TabGroup bg color

---

Source/TitaniumKit/src/API.cpp

https://jira.appcelerator.org/browse/TIMOB-23301

[5_3_X] [TIMOB-23301] Windows: Ti.API.log doesn't handle single argument

---

Source/TitaniumKit/src/API.cpp

https://jira.appcelerator.org/browse/TIMOB-23301

[master] [TIMOB-23301] Windows: Ti.API.log doesn't handle single argument

---

Examples/NMocha/src/Assets/ti.locale.test.js
Source/Ti/include/TitaniumWindows/Locale.hpp
Source/Ti/src/Locale.cpp
Source/TitaniumKit/include/Titanium/Locale.hpp
Source/TitaniumKit/src/Locale.cpp

 [TIMOB-23296] Implement Ti.Locale.setLanguage

---

Examples/NMocha/src/Assets/ti.locale.test.js
Source/Ti/include/TitaniumWindows/Locale.hpp
Source/Ti/src/Locale.cpp
Source/TitaniumKit/include/Titanium/Locale.hpp
Source/TitaniumKit/src/Locale.cpp

https://jira.appcelerator.org/browse/TIMOB-23296

[TIMOB-23296] Implement Ti.Locale.setLanguage

---

Source/UI/src/Button.cpp

https://jira.appcelerator.org/browse/TIMOB-23338
Once merged, this needs to be cherry-picked over to master

[5_3_X][TIMOB-23338] Windows: Ti.UI.Button - Color property sets background color instead of text color

---

Source/TitaniumKit/include/Titanium/UI/TextField.hpp
Source/TitaniumKit/src/UI/TextField.cpp
Source/UI/include/TitaniumWindows/UI/TextField.hpp
Source/UI/src/TextField.cpp
Source/UI/src/Windows/ViewHelper.cpp

https://jira.appcelerator.org/browse/TIMOB-23335

[TIMOB-23335] Windows: Support font property on Ti.UI.TextField

---

Examples/NMocha/src/Assets/ti.contacts.test.js
Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/src/Tab.cpp

#667 + Reverting back to default color when color is empty

[TIMOB-23276] Windows: Unable to change color Tab/Window titles

---

Examples/Corporate/src/Assets/alloy/controllers/profile.js
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/Label.cpp

[TIMOB-23372] [TIMOB-23373] Fix resize issue with Label

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[master] [TIMOB-23374] Windows: Label backgroundColor cut through border with radius

---

Source/UI/src/Label.cpp

Workaround to fix layout issue in Corporate app for 5_3_X so we can fix Corporate app layout issue asap.

[5_3_X] Workaround to fix layout issue (TIMOB-23293) on Corporate App

---

Source/UI/include/TitaniumWindows/UI/ScrollableView.hpp
Source/UI/src/ScrollableView.cpp

- Implement ``Titanium.UI.ScrollableView.scrollingEnabled`` property
```Javascript
a = Ti.UI.createView({ backgroundColor: 'red' }),
b = Ti.UI.createView({ backgroundColor: 'green' }),
c = Ti.UI.createView({ backgroundColor: 'blue' }),
sv = Ti.UI.createScrollableView({ views: [a, b, c], showPagingControl: true, scrollingEnabled: true }),
btn = Ti.UI.createButton({ title: 'SCROLL: true', backgroundColor: 'white'});
a.add(btn);
sv.scrollingEnabled = !sv.scrollingEnabled;
btn.title = 'SCROLL: ' + sv.scrollingEnabled;
});
win.add(sv);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23308)

[TIMOB-23308] Implement Ti.UI.ScrollableView.scrollingEnabled property

---

Source/Sensors/src/Geolocation.cpp

- Implement `Ti.Geolocation.locationServicesAuthentication`
- Make sure to request access to location 
- Make sure to catch exception from callback
- Some refactorings around `get_context()`
```javascript
color: "blue",
text: "Get Current Position"
});
label.addEventListener('click', function () {
if (Ti.Geolocation.locationServicesAuthorization == Ti.Geolocation.AUTHORIZATION_DENIED) {
Ti.API.info('Location request has been denied');
return;
} else {
Ti.API.info('Location request has been granted');
}
Ti.Geolocation.getCurrentPosition(function (e) {
Ti.API.info(JSON.stringify(e.coords));
});
});
Ti.Geolocation.addEventListener("location", function (e) { …
```

[5_3_X] Improvement Ti.Geolocation for Windows 10

---

Source/Sensors/src/Geolocation.cpp

Improvement Ti.Geolocation for Windows 10

---

Source/Network/src/HTTPClient.cpp

[TIMOB-23400] Fix: Analytics sends wrong UTF8 characters

---

Source/Ti/src/Platform.cpp

https://jira.appcelerator.org/browse/TIMOB-23393
Ti.Platform.ostype no longer just returns the same value as Ti.Platform.architecture. They both use GetNativeSystemInfo under the hood. ostype should be either "32bit", "64bit" or "unknown". architecture should be one of: x86, x64, ia64, ARM, or unknown.

[TIMOB-23393] Analytics: Windows JSON payload lists ostype as arm

---

Source/Ti/src/Platform.cpp

- Remain in parity with iOS and return the device name for ``Titanium.Platform.username``
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20173)

[TIMOB-20173] Improve Ti.Platform.username

---

Source/TitaniumKit/src/analytics.js

https://jira.appcelerator.org/browse/TIMOB-23402

[TIMOB-23402] Analytics: Add data element to JSON payload for windows phone parity

---

Examples/NMocha/src/Assets/ti.blob.test.js
Source/Titanium/src/Blob.cpp

- Add validation to ``transformImage`` to determine if the ``Blob`` is a valid image
- Add test cases
```Javascript
var textBlob = Ti.Filesystem.getFile('app.js').read();
textBlob.imageAsResized(25, 25);
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23425)

[TIMOB-23425] Validate Ti.Blob.image* methods

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-23461] Fix: Ti.UI.View ignores click event

---

Source/UI/src/Window.cpp

move Window log to internal

---

Source/TitaniumKit/include/Titanium/UI/Animation.hpp
Source/TitaniumKit/src/UI/Animation.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

This is an attempt to fix the remaining issue on #731

[TIMOB-23209] Improve handling of view animations on multiple presses

---

Examples/NMocha/src/Assets/ti.locale.test.js
Examples/NMocha/src/Assets/ti.ui.alertdialog.test.js
Examples/NMocha/src/Assets/ti.ui.button.test.js
Examples/NMocha/src/Assets/ti.ui.label.test.js
Examples/NMocha/src/Assets/ti.ui.optiondialog.test.js
Examples/NMocha/src/Assets/ti.ui.tab.test.js
Examples/NMocha/src/Assets/ti.ui.window.test.js
Source/Ti/include/TitaniumWindows/Locale.hpp
Source/Ti/src/Locale.cpp
Source/TitaniumKit/include/Titanium/Locale.hpp
Source/TitaniumKit/src/Locale.cpp
Source/TitaniumKit/src/UI/AlertDialog.cpp
Source/TitaniumKit/src/UI/Button.cpp
Source/TitaniumKit/src/UI/Label.cpp
Source/TitaniumKit/src/UI/OptionDialog.cpp
Source/TitaniumKit/src/UI/Tab.cpp
Source/TitaniumKit/src/UI/Window.cpp

[TIMOB-23498](https://jira.appcelerator.org/browse/TIMOB-23498)
```javascript
button = Ti.UI.createButton({ title: 'BUTTON TITLE', backgroundColor: 'blue' });
button.titleid = "should_not_be_found";
Ti.API.info(button.title); // should print "BUTTON TITLE"
});
win.open();
```

[TIMOB-23498] titleId/title should retain existing value if no key found

---

templates/module/default/hooks/windows-module.js

- Add validation of required SDK to all module projects
```
ti create -p windows -t module -n TIMOB23246 --id win.module --force
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23246)

[TIMOB-23246] Validate SDKs before generating module projects

---

templates/module/default/hooks/windows-module.js

[5_4_X] [TIMOB-23246] Validate SDKs before generating module projects

---

cli/commands/_buildModule.js

[TIMOB-23557](https://jira.appcelerator.org/browse/TIMOB-23557)

[TIMOB-23557] Configure target sdk from timodule.xml

---

Examples/NMocha/src/Assets/ti.geolocation.test.js

Add timeout for `Ti.Geolocation.forward/reverseGeocoder` unit test

Add timeout for Ti.Geolocation test

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Source/TitaniumKit/src/UI/ImageView.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp

[TIMOB-23560] Fix: Setting images on ImageView will crash the app

---

Source/TitaniumKit/src/Module.cpp

[5_4_X] [TIMOB-23615] removeEventListener() should update event_listener_map__

---

cli/commands/_build/copy.js
cli/commands/_build/generate.js

- Generate ``Package.appxmanifest`` ``Capabilities`` and ``DeviceCapabilities`` from API usage
- Only generate capabilities when none are specified in ``tiapp.xml``
|               API               |
|:-------------------------------:|
| Titanium.Contacts.* |
| Titanium.Filesystem.externalStorageDirectory |
| Titanium.Geolocation.* |
| Titanium.Media.openPhotoGallery |
| Titanium.Media.startVideoCapture |
| Titanium.Media.takeScreenshotToFile |
| Titanium.Media.showCamera |
| Titanium.Media.AudioRecorder.* |
| Titanium.Network.* |
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'black' }),
lbl = Ti.UI.createLabel({ top: '5%', left: 5, color: 'white' }),
btn_a = Ti.UI.createButton({ top: '25%',color: 'white', title: 'showCamera()' }),
btn_b = Ti.UI.createButton({ top: '35%', …
```

[TIMOB-23156] Generate capabilities from API usage

---

Source/Global/src/GlobalObject.cpp
Source/Ti/src/Codec.cpp
Source/Ti/src/Contacts.cpp
Source/Ti/src/Platform.cpp
Source/Titanium/src/Blob.cpp
Source/Titanium/src/File.cpp
Source/UI/src/AlertDialog.cpp
Source/UI/src/Clipboard.cpp
Source/UI/src/ImageView.cpp
Source/UI/src/OptionDialog.cpp
Source/UI/src/WebView.cpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp
Source/Utility/include/TitaniumWindows/WindowsTiImpl.hpp
Source/Utility/src/Utility.cpp

[TIMOB-23439](https://jira.appcelerator.org/browse/TIMOB-23439)
Improve exception handling in async function
* Use `concurrency::task::get()` whenever possible so we can catch the exception
* Make sure we prefer to catch `Platform::Exception^` over `Platform::COMException^`

[TIMOB-23439] Improve exception handling in async function

---

Examples/NMocha/src/Assets/ti.ui.view.test.js

- Use ``parent`` view to correctly determine the final animation positions for ``view``
- Add a timeout
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23164)

[TIMOB-23164] Fix Windows 10 Store animate left and top test cases

---

Examples/NMocha/src/Assets/ti.ui.button.test.js
Source/Network/src/HTTPClient.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/UI/TableViewSection.hpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/TitaniumKit/src/UI/TableViewSection.cpp
Source/UI/src/ListView.cpp
Source/UI/src/ProgressBar.cpp
Source/UI/src/Window.cpp

The [single context mode](https://github.com/appcelerator/HAL/pull/63) and [retain count management](https://github.com/appcelerator/HAL/pull/64) I introduced in the latest HAL provides huge performance improvement in TitaniumKit. I  have observed it cuts down over ~~50%~~ 70% of time.
On Lumia 630 (Windows Phone 8.1) using Ti SDK 6.0.0.v20160714010528
- Ti SDK 6.0.0.v20160714010528 ... 5.5 sec
- Ti SDK 6.0.0.v20160714010528 with this update ... ~~2.7 sec~~ -> 1.7 sec
```javascript
var data = [];
var start = +new Date();
for (var i = 0; i < 100; i++) {
var task = {
Id: i,
Title: 'Row ' + i,
Data: 'Data ' + i
};
var tvr = Ti.UI.createTableViewRow({
height: 70,
taskId: task.Id
});
tvr.add(Ti.UI.createLabel({
text: task.Title, …
```

TitaniumKit performance optimization

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp
Source/Utility/include/TitaniumWindows/Utility.hpp
Source/Utility/src/Utility.cpp

[TIMOB-23546](https://jira.appcelerator.org/browse/TIMOB-23546)
How to test:
- Open camera, then tap the screen to see if focus is changed
```javascript
imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '70%' });
var overlay = Ti.UI.createView({
height: '20%', width: Ti.UI.FILL,
bottom: 0
}),
hideButton = Ti.UI.createButton({ title: 'HIDE PREVIEW', backgroundColor: 'red' });
});
hideButton.addEventListener('click', function () { …
```

[TIMOB-23546] Tap-to-focus for Camera

---

Source/UI/include/TitaniumWindows/UI/Button.hpp
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/include/TitaniumWindows/UI/ScrollableView.hpp
Source/UI/include/TitaniumWindows/UI/SearchBar.hpp
Source/UI/include/TitaniumWindows/UI/Slider.hpp
Source/UI/include/TitaniumWindows/UI/Switch.hpp
Source/UI/include/TitaniumWindows/UI/TextArea.hpp
Source/UI/include/TitaniumWindows/UI/TextField.hpp
Source/UI/include/TitaniumWindows/UI/WebView.hpp
Source/UI/src/Button.cpp
Source/UI/src/ScrollView.cpp
Source/UI/src/ScrollableView.cpp
Source/UI/src/SearchBar.cpp
Source/UI/src/Slider.cpp
Source/UI/src/Switch.cpp
Source/UI/src/TextArea.cpp
Source/UI/src/TextField.cpp

- Fix ``borderRadius`` property for
- ``Titanium.UI.Button``
- ``Titanium.UI.ScrollView``
- ``Titanium.UI.WebView``
- ``Titanium.UI.TextField``
- ``Titanium.UI.ScrollableView``
- ``Titanium.UI.Switch``
- ``Titanium.UI.TextArea``
- ``Titanium.UI.SearchBar``
- ``Titanium.UI.Slider``
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'purple' }),
scrollView = Ti.UI.createScrollView({
borderWidth: 5,
borderColor: 'yellow',
borderRadius: 5
}),
button = Ti.UI.createButton({
title: 'BUTTON',
borderWidth: 5,
borderColor: 'yellow',
borderRadius: 5
}),
webView = Ti.UI.createWebView({
url: 'http://www.appcelerator.com/',
borderWidth: 5,
borderColor: 'yellow',
borderRadius: 5
}),
textField = Ti.UI.createTextField({ …
```

[TIMOB-23657] borderRadius does not work for some components

---

Examples/NMocha/src/Assets/ti.ui.view.test.js

- Fix `ti.ui.view.test.js` `border` test case

Fix Windows 10 Jenkins builds

---

Source/UI/src/ListView.cpp
Source/UI/src/TableView.cpp

[TIMOB-23693](https://jira.appcelerator.org/browse/TIMOB-23693)
[TIMOB-23694](https://jira.appcelerator.org/browse/TIMOB-23694)
TableView
```javascript
var header = Ti.UI.createView({ backgroundColor: "blue"});
var lbl = Ti.UI.createLabel({ text: "Valid" });
header.add(lbl);
var footer = Ti.UI.createView({ backgroundColor: "blue" });
var lbl2 = Ti.UI.createLabel({ text: "Invalid" });
footer.add(lbl2);
var section = Ti.UI.createTableViewSection({ id: "Valid", headerView: header, footerView: footer });
section.add(Ti.UI.createTableViewRow({ title: 'Carrots' }));
section.add(Ti.UI.createTableViewRow({ title: 'Potatoes' }));
var tblView = Ti.UI.createTableView({
data: [section]
});
win.add(tblView);
win.open();
```
ListView …

Fix: Wrong header/footer height for TableView/ListView

---

Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp

Cherry-pick #801 for 5_4_X
[TIMOB-23717](https://jira.appcelerator.org/browse/TIMOB-23717)

[5_4_X] [TIMOB-23717] Fx Ti.UI.ImageView.toImage() 

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp

[TIMOB-23716](https://jira.appcelerator.org/browse/TIMOB-23716)
```javascript
imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '70%' });
var overlay = Ti.UI.createView({
height: '20%', width: Ti.UI.FILL,
bottom: 0
}),
hideButton = Ti.UI.createButton({ title: 'HIDE PREVIEW', backgroundColor: 'red' });
});
hideButton.addEventListener('click', function () {
Ti.Media.hideCamera();
});
overlay.add(takeButton);
overlay.add(hideButton); …
```

Fix orientation for front camera

---

Source/UI/src/ListView.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/808
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23734)

[5_4_X][TIMOB-23734] Fix ListSection events index when without a header

---

Source/UI/src/ListView.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/808
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23734)

[6_0_X][TIMOB-23734] Fix ListSection events index when without a header

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Examples/NMocha/src/Assets/utilities/utilities.js

We've been seeing some tests fails on Windows 10 desktop.

Attempt to fix unit tests

---

Examples/NMocha/src/Assets/ti.ui.listview.test.js
Source/TitaniumKit/src/UI/ListSection.cpp
Source/UI/src/ListView.cpp

[TIMOB-23734] Fix ListView fireListSectionEvent()

---

Examples/NMocha/src/Assets/app.js

Skip UI tests temporary on Windows 8.1 desktop

---

Source/Network/src/HTTPClient.cpp
Source/TitaniumKit/include/Titanium/Network/HTTPClient.hpp
Source/TitaniumKit/src/Network/HTTPClient.cpp

This reverts commit c98f5f08612485b24732d6f784d7e91937f5aa60.

Revert "[TIMOB-23752] Async HTTPClient crashes on Desktop (#826)"

---

Examples/NMocha/src/Assets/app.js

Investigate failing mocha tests on Jenkins
[TIMOB-23776](https://jira.appcelerator.org/browse/TIMOB-23776)
Skip UI tests on Windows 10 desktop to make nightly build pass.

TIMOB-23776 Skip tests on Windows Desktop due to intermittent freeze

---

cli/commands/_build/generate.js

- Include `proximity` capability in capability auto-generation
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' });
Ti.App.addEventListener('proximity', function (e) {
win.setBackgroundColor(e.state ? 'green' : 'red');
});
Ti.App.setProximityDetection(true);
// Ti.App.proximityDetection = true;
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23832)

[TIMOB-23832] Auto-generate proximity capability

---

Source/Media/src/Media.cpp
Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp
Source/TitaniumKit/src/API.cpp
Source/TitaniumKit/src/App/Properties.cpp
Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/Blob.cpp
Source/TitaniumKit/src/Buffer.cpp
Source/TitaniumKit/src/GeolocationModule.cpp
Source/TitaniumKit/src/GlobalObject.cpp
Source/TitaniumKit/src/Media/VideoPlayer.cpp
Source/TitaniumKit/src/MediaModule.cpp
Source/TitaniumKit/src/Module.cpp
Source/TitaniumKit/src/NetworkModule.cpp
Source/TitaniumKit/src/Stream.cpp
Source/TitaniumKit/src/UI/2DMatrix.cpp
Source/TitaniumKit/src/UI/3DMatrix.cpp
Source/TitaniumKit/src/UI/Clipboard.cpp
Source/TitaniumKit/src/UI/Picker.cpp
Source/TitaniumKit/src/UI/ScrollView.cpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/WebView.cpp

[TIMOB-23621](https://jira.appcelerator.org/browse/TIMOB-23621)
```javascript
Ti.UI.createTableViewRow({ title: 'Bananas' });
var table = Ti.UI.createTableView({});
table.insertRowAfter(Ti.UI.createTableViewRow({ title: 'notEnoughArgs' }));
win.open();
```
*Expected*
- Error message: `insertRowAfter: Invalid number of arguments. Expected 2 but got 1` is shown in the error message window
- Following messages are shown in the console
```
[ERROR] ----- Titanium Javascript Runtime Error -----
[ERROR] In app.js: 4,21
[ERROR] Message: Uncaught Error: insertRowAfter: Invalid number of arguments. Expected 2 but got 1
```

[TIMOB-23621] Improve arguments error for function call

---

cli/commands/_build/generate.js

- Always include auto-generated capabilities, even if capabilities are already defined in `tiapp.xml`
```Javascript
Ti.App.setProximityDetection(true);
```
```XML
<windows>
<manifest>
<Capabilities>
<Capability Name="internetClient" />
<Capability Name="picturesLibrary" />
</manifest>
</windows>
```
```
appc run -p windows -S 10.0 --build-only
```
```XML
<Capabilities>
<Capability Name="internetClient" />
<uap:Capability Name="picturesLibrary" />
<DeviceCapability Name="proximity" />
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23833)

[TIMOB-23833] Always auto-generate capabilities

---

cli/commands/_build/generate.js

- Fix auto-capability generation for Windows 8.1 store
- Add `videosLibrary` capability for `Titanium.Media.takePicture()`
- TIMOB-23156 was already fixed in `master`
[TIMOB-23156](https://jira.appcelerator.org/browse/TIMOB-23156)
[TIMOB-23869](https://jira.appcelerator.org/browse/TIMOB-23869)

[TIMOB-23156] Fix auto-capability generation

---

Examples/NMocha/src/Assets/app.js

Workaround to make nightly build pass

---

cli/commands/_build/utils.js
cli/lib/info.js

[TIMOB-23371] Only report a device when one has been detected

---

Examples/NMocha/src/Assets/ti.require.test.js
Examples/NMocha/src/Assets/with_index_js/sub1.js
Source/TitaniumKit/src/GlobalObject.cpp

[TIMOB-23875] __filename should not be messed with nested require

---

cli/commands/_build/generate.js

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/866
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23869)

[6_0_X][TIMOB-23869] Fix Ti.Media.takePicture() capabilities

---

cli/commands/_build/generate.js

- Add `picturesLibrary` to `Titanium.Media.takePicture()` auto-capability generation
```Javascript
imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '70%' });
var overlay = Ti.UI.createView({
height: '20%', width: Ti.UI.FILL,
bottom: 0
}),
hideButton = Ti.UI.createButton({ title: 'HIDE PREVIEW', backgroundColor: 'red' });
});
hideButton.addEventListener('click', function () {
Ti.Media.hideCamera();
});
overlay.add(takeButton); …
```

[TIMOB-23869] Fix Ti.Media.takePicture() capabilities

---

templates/module/default/template/windows/timodule.xml

[TIMOB-23877](https://jira.appcelerator.org/browse/TIMOB-23877)
Steps to test
```
> appc new -n test --id com.example.test
> cd test/windows
```
Expected
You should see `windows` element in `timodule.xml`

[TIMOB-23877] Add Windows element to timodule.xml template

---

Source/TitaniumKit/src/analytics.js

[TIMOB-23965](https://jira.appcelerator.org/browse/TIMOB-23965)
Cherry-pick #872 for 6_0_X

[TIMOB-23965] Add eventName after feature event validation

---

Source/TitaniumKit/src/analytics.js

[TIMOB-23952](https://jira.appcelerator.org/browse/TIMOB-23952)
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'purple' }),
btn_b = Ti.UI.createButton({ title: 'Feature Event: invalid object', top: 50 });
btn_b.addEventListener('click', function () {
var data = undefined;
Ti.Analytics.featureEvent('invalid', data);
});
win.add(btn_b);
win.open();
```

[TIMOB-23952] Analytics should not send invalid object

---

Examples/NMocha/src/Assets/ti.app.test.js
Source/Ti/include/TitaniumWindows/AppModule.hpp
Source/Ti/src/AppModule.cpp

[TIMOB-23977](https://jira.appcelerator.org/browse/TIMOB-23977)
Create unique identifier for the current continuous run of the application.
```javascript
Ti.API.info(Ti.App.getSessionId())
```

[TIMOB-23977] Implement Ti.App.getSessionId

---

Source/Sensors/src/Geolocation.cpp

[TIMOB-23655](https://jira.appcelerator.org/browse/TIMOB-23655) for `6_0_X`
- Fix crash at `Ti.Geolocation.requestLocationPermissions()`
```Javascript
btn_a = Ti.UI.createButton({top: '33%', title:'hasLocationPermissions()'}),
btn_b = Ti.UI.createButton({top: '66%', title:'requestLocationPermissions()'});
btn_a.addEventListener('click', function () {
alert('hasLocationPermissions() : ' + Ti.Geolocation.hasLocationPermissions(null));
});
btn_b.addEventListener('click', function () {
Ti.Geolocation.requestLocationPermissions(null, function (res) {
alert(JSON.stringify(res, null, ' '));
});
});
win.add(btn_a);
win.add(btn_b);
win.open();
```

[6_0_X] [TIMOB-23655] Fix crash at Ti.Geolocation.requestLocationPermissions

---

Source/Sensors/src/Geolocation.cpp

[TIMOB-23655] Fix crash at Ti.Geolocation.requestLocationPermissions

---

Examples/NMocha/src/Assets/ti.ui.listview.test.js
Examples/NMocha/src/Assets/ti.ui.searchbar.test.js
Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/TitaniumKit/include/Titanium/UI/TableViewSection.hpp
Source/TitaniumKit/src/UI/ListView.cpp
Source/UI/src/ListView.cpp

[TIMOB-24019] ListView should keep "original" data even when filtered

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

[TIMOB-23930] Setting FILL for ScrollView should show all content

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js

We've been seeing intermittent unstable status on 'layoutWithSIZE_and_fixed' test. Trying to fix it.

[6_0_X] Attempt to stabilize 'layoutWithSIZE_and_fixed' test

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js

Attempt to stabilize 'layoutWithSIZE_and_fixed' test

---

Examples/NMocha/src/Assets/ti.geolocation.test.js
Examples/NMocha/src/Assets/ti.ui.view.test.js

Skip geolocation tests because it may be blocking other tests

Skip geolocation tests

---

cli/lib/stub.js

[TIMOB-24147](https://jira.appcelerator.org/browse/TIMOB-24147)
- Fix: `null` is returned when you get `EasClientDeviceInformation` constructor
```javascript
var EasClientDeviceInformation = require('Windows.Security.ExchangeActiveSyncProvisioning.EasClientDeviceInformation'),
deviceInfo = new EasClientDeviceInformation();
alert('SystemFirmwareVersion: ' + JSON.stringify(deviceInfo.SystemFirmwareVersion));
```
`TypeHelper` should have been built for `Debug` as well as `Release`.

[TIMOB-24147] Fix: Unable to "new" EasClientDeviceInformation 

---

Source/TitaniumKit/src/UI/TableView.cpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

[TIMOB-24104](https://jira.appcelerator.org/browse/TIMOB-24104)
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green'});
// data: [{title: 'test'}]
});
// appending row data to tableView
for (var i = 1; i <= 3; i++) {
var stringTitle = 'row data ' + i;
var rowData = Ti.UI.createTableViewRow({
title: stringTitle
});
tableView.appendRow(rowData);
}
// appending an array of rows to table view
var arrayRows = [{
title: 'array row 1'
}, {
title: 'array row 2'
}, {
title: 'array row 3'
}];
tableView.appendRow(arrayRows );
win.add(tableView);
win.open();
```

[TIMOB-24104] appendrow does not work on a TableView with no data

---

Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

[TIMOB-24116](https://jira.appcelerator.org/browse/TIMOB-24116)
```javascript
var data = [{ title: 'Alan' }, { title: 'Alice' }, { title: 'Alexander' }, { title: 'Amos' }, { title: 'Alonzo' }, { title: 'Brad' }, { title: 'Brent' }, { title: 'Billy' }, { title: 'Brenda' }, { title: 'Potsie' }];
var header = Ti.UI.createView({
height: 100
});
var tableview = Titanium.UI.createTableView({
data: data,
headerTitle: 'This is a test-test',
//headerView: header,
});
_window.add(tableview);
````

[TIMOB-24116] TableView.header cannot be set after setting data

---

.gitmodules

Cherry-pick 7c776d34689ed60eaa65c8ecc9b210fa1a982386 for 6_0_X

Make submodule name match path for Source/HAL

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.test.js
Examples/NMocha/src/Assets/ti.ui.button.test.js
Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Examples/NMocha/src/Assets/ti.ui.label.test.js

Attempt to make the build pass

---

cli/commands/_build/generate.js

[TIMOB-24063](https://jira.appcelerator.org/browse/TIMOB-24063)
If a Windows Platform module requires specific capabilities to function then a module developer should be able to use the timodule.xml file (in a similar way to Android modules and permissions) to specify capabilities that are required. Then at build time these should be included with any capabilities a users app may need.
1.  Create new module
2. Update `timodule.xml`, add required `Capabilities` for the module.
3. Install the module, and build your app that uses the module
4. See if your app has required capabilities (You can find your app's generated manifests in `﻿C:\Users\USERNAME\.titanium\vsbuild\YOUR_APP_NAME\Package.xxx.appxmanifest.in`)
timodule.xml
```xml
<ti:module …
```

[TIMOB-24063] Add ability to set manifest in timodule.xml

---

Source/TitaniumKit/src/GlobalObject.cpp

- [TIMOB-23994](https://jira.appcelerator.org/browse/TIMOB-23994)
- [TIMOB-23995](https://jira.appcelerator.org/browse/TIMOB-23995) 
`__filename` & `__dirname` should be defined in `app.js`.
```js
Ti.API.info(__dirname);
Ti.API.info(__filename);
```

[TIMOB-23994] [TIMOB-23995] __filename & __dirname in app.js

---

Source/Network/src/HTTPClient.cpp

[TIMOB-24268] Fix crash/freeze in HttpClient

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Examples/NMocha/src/Assets/ti.network.socket.tcp.test.js
Source/Network/src/HTTPClient.cpp

#917 + Re-enable httpclient test

Re-enable httpclient test

---

Examples/NMocha/src/Assets/app.js

Skip network test on Windows 10

---

Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/UI/src/TableView.cpp

[TIMOB-24135](https://jira.appcelerator.org/browse/TIMOB-24135)
```js
var _window = Ti.UI.createWindow({backgroundColor:'green'});
var data = [{
title: 'First Row',
hasDetail: true
}, {
title: 'Second Row',
hasDetail: true
}, {
title: 'Third Row',
hasDetail: true
}, {
title: 'Forth Row',
hasDetail: true
}, {
title: 'Fifth Row',
hasDetail: true
}];
var search = Ti.UI.createSearchBar({
top: 0,
returnKeyType: Ti.UI.RETURNKEY_DONE,
});
top: 50,
data: data,
search: search
});
tableView.addEventListener('click', function (e) {
alert('Click Event. index: ' + e.index + ', Title: ' + e.row.title);
});
_window.add(tableView);
_window.add(search);
```
Steps to test
- Add the above code to an existing app.js and build for …

[TIMOB-24135] TableView events does not handle filtered data

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/UI/src/TableView.cpp

Cherry-pick for 6_0_X
- #925
- #927

[6_0_X] [TIMOB-24135]  [TIMOB-24318] Backport for 6.0.2

---

Source/UI/include/TitaniumWindows/UI/ListView.hpp
Source/UI/src/ListView.cpp

[TIMOB-24245](https://jira.appcelerator.org/browse/TIMOB-24245)
```js
var listView = Ti.UI.createListView();
for (var i = 0; i < 10; i++) {
var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits ' + sections.length });
{ properties: { title: 'Apple' } },
{ properties: { title: 'Banana' } },
];
var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables ' + sections.length });
var vegDataSet = [
{ properties: { title: 'Carrots'} },
{ properties: { title: 'Potatoes' } },
];
vegSection.setItems(vegDataSet);
sections.push(vegSection);
}
win.addEventListener('open', function() { …
```

[TIMOB-24245] Implement ListView.scrollToItem

---

cli/commands/_build/utils.js
cli/lib/info.js

[TIMOB-24183](https://jira.appcelerator.org/browse/TIMOB-24183)
Cherry-pick #915 for 6_0_X
Revert "[TIMOB-23371] Only report a device when one has been detected"
This reverts commit a35c83c4d0ecd1d14edc9fe21d048d3fe01967ed.

[6_0_X] [TIMOB-24183] Revert TIMOB-23371

---

Source/UI/include/TitaniumWindows/UI/TableViewRow.hpp
Source/UI/src/TableViewRow.cpp

[TIMOB-24130](https://jira.appcelerator.org/browse/TIMOB-24130)
```js
var row1 = Ti.UI.createTableViewRow({
title: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
});
var row2 = Ti.UI.createTableViewRow({
});
var label2 = Ti.UI.createLabel({
top: 0,
text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
});
row2.add(label2);
data: [row1, row2]
});
_window.add(table);
```

[TIMOB-24130] Layout issue in Label in TableView with long text

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.blob.test.js
Examples/NMocha/src/Assets/ti.network.test.js
Examples/NMocha/src/Assets/utilities/assertions.js
Examples/NMocha/src/Assets/utilities/utilities.js
Jenkinsfile

Trying to get back to stable, closer to our common mocha suite.

More work on builds/tests

---

Source/TitaniumKit/include/Titanium/UI/Label.hpp
Source/TitaniumKit/src/UI/Label.cpp
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/Label.cpp
Source/UI/src/Window.cpp

- [TIMOB-23388](https://jira.appcelerator.org/browse/TIMOB-23388) autoLink URL for Ti.UI.Label
- [TIMOB-24386](https://jira.appcelerator.org/browse/TIMOB-24386) Resize Label when root Window is resized
Test code: Following label should display hyperlink for each `http://` `tel:` `mailto:` schemes. Also, this label should be resized when you resize root Window (Windows Store app only).
```js
var win = Ti.UI.createWindow({ backgroundColor: 'green'});
var label1 = Ti.UI.createLabel({
text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. http://www.appcelerator.com/ Ut enim ad tel:0123456789 minim veniam, quis nostrud mailto:foo@example.com exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', …
```

[TIMOB-23388] [TIMOB-24386] autoLink URL for Ti.UI.Label

---

Source/Ti/src/Platform.cpp

[TIMOB-23319](https://jira.appcelerator.org/browse/TIMOB-23319)
We are now able to open local PDF file by saving it in application data directory and then open with `Ti.Platform.openURL('ms-appdata:///local/goalsetting.pdf')`. We are also able to open public pdf files directly via web (http) like `Ti.Platform.openURL('http://bdrconsultants.com/goalsetting.pdf');`.
```js
/*
win.addEventListener('click', function () {
Ti.Platform.openURL('http://bdrconsultants.com/goalsetting.pdf');
});
*/
win.addEventListener('click', function () {
var xhr = Ti.Network.createHTTPClient();
xhr.setTimeout(6e4);
xhr.onload = function (e) {
var to = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'goalsetting.pdf'); …
```

[TIMOB-23319] Ability to open local pdf file

---

Source/TitaniumKit/include/Titanium/UI/TableViewRow.hpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/TitaniumKit/src/UI/TableViewRow.cpp

[TIMOB-23331](https://jira.appcelerator.org/browse/TIMOB-23331)
Implement `filterAnchored`, `filterCaseInsensitive` and `filterAttribute` properties.
Test code:
- Typing `A` with `filterCaseInsensitive: true` & `filterAnchored:false` should list all items
- Typing `A` with `filterCaseInsensitive: false` & `filterAnchored:false` should show only ` Apple`
- Typing `A` with `filterAnchored:true` should show only `Apple`
- Typing `Za` with `filterAttribute`, `filterCaseInsensitive: true` & `filterAnchored:false`  should show `Apple` and `Carrots`
- Typing `Za` with `filterAttribute`, `filterCaseInsensitive: true` & `filterAnchored:true` should show only `Carrots`
```js
var searchBar = Ti.UI.createSearchBar();
var tableView = …
```

[TIMOB-23331] Implement TableView filter properties

---

Source/Network/src/Network.cpp

[TIMOB-24561] Ti.Network change event crashes the app

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

Cherry-pick #972 for 6_1_X
You don't have to review this, this can be merged once #972 passed.

[6_1_X] [TIMOB-24583] Native view should use absolute position in Ti View (#972)

---

cli/commands/_build/copy.js

Cherry-pick #974 for 6_1_X 
You don't have to review this, this can be merged once #974 passed.

[6_1_X] [TIMOB-24595] Hyperloop addEventListener fails

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[6_1_X][TIMOB-24603] removeAllChildren() does not work

---

Source/Network/src/HTTPClient.cpp

[6_1_X] [TIMOB-24615] HTTPClient.responseText is not cleared

---

Source/TitaniumKit/include/Titanium/MediaModule.hpp
Source/TitaniumKit/src/MediaModule.cpp
apidoc/Titanium/Media.yml

Cherry-pick #965 for 6_1_X 
You don't have to review this, this can be merged once #965 passed.

[6_1_X] [TIMOB-20544] Align permission methods Ti.Media.AudioRecorder

---

templates/build/Native/src/RequireHook.cpp.ejs
templates/build/TitaniumWindows_Hyperloop/src/TypeHelper.cs.ejs

[TIMOB-24651](https://jira.appcelerator.org/browse/TIMOB-24651)
```js
var List = require('System.Collections.Generic.List<System.Int32>');
```
Expected: This should not cause compile error.

[TIMOB-24651] Hyperloop: unable to compile generic collections

---

templates/build/Native/src/RequireHook.cpp.ejs
templates/build/TitaniumWindows_Hyperloop/src/TypeHelper.cs.ejs

[6_1_X] [TIMOB-24651] Hyperloop: unable to compile generic collections

---

cli/hooks/wp-run.js

Cherry-pick #989 for 6_1_X.
I would like to push this to 6.1.x because it's critical.

[6_1_X] [TIMOB-24656] Skip installing dependencies on deployment

---

cli/commands/_build/copy.js
cli/commands/_build/encrypt.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-24618
Taking over #991 , making Hyperloop event work.
**Test if Hyperloop event works**
```js
﻿var win = Ti.UI.createWindow({ backgroundColor: 'green' }),
Button = require('Windows.UI.Xaml.Controls.Button'),
button = new Button();
button.Content = "PUSH";
button.addEventListener('Tapped', function (e) {
alert('pushed');
});
win.open();
```
**Test if Hyperloop + ES6 works**
```js
Button = require('Windows.UI.Xaml.Controls.Button'),
button = new Button();
button.Content = "PUSH";
button.addEventListener('Tapped', e => {
alert('pushed');
});
win.open();
```
Expected: "pushed" dialog should be shown when you push "PUSH"

[TIMOB-24618] Windows: Replace uglify usage in build process

---

cli/commands/_build/copy.js
cli/commands/_build/encrypt.js

[6_1_X] [TIMOB-24618] Windows: Replace uglify usage in build process

---

Source/UI/src/TableView.cpp

JIRA: https://jira.appcelerator.org/browse/TIMOB-24719
````
var searchBar = Ti.UI.createSearchBar();
var data = [];
for (var i = 0; i < 25; i++) {
data.push({ title: `Row ${i}` });
}
search: searchBar,
data: data
});
_window.add(tableView);
````

[TIMOB-24719] Fix TableView with searchbar not scrolling

---

Source/UI/include/TitaniumWindows/UI/WebView.hpp
Source/UI/src/WebView.cpp

[TIMOB-24533](https://jira.appcelerator.org/browse/TIMOB-24533)
Implement `WebView.html` getter property. 
```js
webview = Ti.UI.createWebView(),
textarea = Ti.UI.createTextArea({
height: Ti.UI.FILL
});
webview.setUrl("http://www.appcelerator.com/");
});
webview.addEventListener('load', function (e) {
var html = webview.getHtml();
textarea.value = html;
}, 3000);
});
win.add(webview);
win.add(textarea);
win.open();
```

[TIMOB-24533] Implement WebView.html getter

---

Source/UI/src/TableView.cpp

JIRA: https://jira.appcelerator.org/browse/TIMOB-24719
````
var searchBar = Ti.UI.createSearchBar();
var data = [];
for (var i = 0; i < 25; i++) {
data.push({ title: `Row ${i}` });
}
search: searchBar,
data: data
});
_window.add(tableView);
````

[6_1_X][TIMOB-24719] Fix TableView with searchbar not scrolling

---

Source/UI/src/ListView.cpp

[TIMOB-24714](https://jira.appcelerator.org/browse/TIMOB-24714)
`ListView` doesn't scroll when use with SearchBar.
```js
var _ = require('underscore');
backgroundColor: 'white'
});
var searchBar = Ti.UI.createSearchBar({
});
var usersListView = Ti.UI.createListView({
height: Ti.UI.FILL,
backgroundColor: 'purple',
searchView: searchBar
});
var userSection = Ti.UI.createListSection();
sections.push(userSection);
usersListView.sections = sections;
var wrapper = Ti.UI.createView({
top: 0,
left: 0,
height: Ti.UI.FILL,
});
wrapper.add(usersListView);
win.add(wrapper);
var url = 'https://randomuser.me/api/?results=150&nat=us';
var client = Ti.Network.createHTTPClient({
// function called …
```

[TIMOB-24714] ListView's scroll breaks if search bar added

---

cli/commands/_build/config/wpSDK.js

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1006
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24751)

[6_1_X][TIMOB-24751] Fix wpSDK config when selecting sdkTargets

---

README.md

Noticed the build badge was broken, figured might as well fix it

Update build badge in readme

---

templates/module/default/template/windows/manifest.ejs

[6_1_X] [TIMOB-24853] Update module apiversion

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24867](https://jira.appcelerator.org/browse/TIMOB-24867)
```js
borderRadius: 50,
borderColor: 'red',
borderWidth: 3,
width: '30%',
height: '30%'
});
win.add(view);
win.open();
```
**Expected**

[TIMOB-24867] borderRadius for View not working

---

Source/TitaniumKit/include/Titanium/UI/OpenWindowParams.hpp
Source/UI/src/Window.cpp

[TIMOB-24873](https://jira.appcelerator.org/browse/TIMOB-24873)
Implement `Window.open({ fullscreen:true });`
```js
var window = Ti.UI.createWindow({ backgroundColor: 'gray' }),
btn = Ti.UI.createButton({ title: 'CLOSE THIS WINDOW', bottom: 0, left: 0, width: '50%' });
window.close();
});
window.add(btn);
window.open({ fullscreen:true });
```

[TIMOB-24873] Ti.UI.Window.open({fullscreen: true})  doesn't work

---

Source/TitaniumKit/src/UI/listview.js

- Implement support for `template.events`
```JS
var win = Ti.UI.createWindow({ backgroundColor: 'white' }),
list = Ti.UI.createListView({
templates: {
template: {
events: {
click: onClick
},
{
type: 'Ti.UI.Label',
bindId: 'title',
properties: {
left: '5dp',
right: '5dp'
}
}
]
}
},
defaultItemTemplate: 'template'
}),
section = Ti.UI.createListSection(),
items = [];
function onClick(e) {
alert(JSON.stringify(e, null, 2));
}
items.push({
title: { text: 'TEXT' }
});
section.setItems(items);
list.setSections([section]);
win.add(list);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24919)

[TIMOB-24919] Support ListView template.events

---

templates/module/default/template/windows/plugins/hooks/windows.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-24915
When run through titanium CLI this hook would be unable to resolve async and wrench and silently fail, to fix this
- Use the async that's internal to node-appc
- Replace usage of wrench with the same rmdir function in [alloy deep-clean hook](https://github.com/appcelerator/alloy/blob/master/hooks/deepclean.js#L45-L65)
@infosia  out of interest what was the reason for splitting this out into a hook? Could we not do this during the normal module build process?
Verification
1. Grab https://github.com/appcelerator-archive/ti.paint
2. Build the module using `ti build -p windows --build-only --run-cmake` (not `appc ti build`)
- Should build successfully rerunning CMake
3. Build the module using `ti build -p windows --build-only --run-cmake` …

[TIMOB-24915] Fix issue where ti cli could not use run cmake hook

---

Examples/NMocha/src/Assets/ti.blob.test.js
Source/UI/src/Label.cpp
Source/UI/src/TableView.cpp

Cherry-pick #1014 and #1019 for 6.1.2
- [TIMOB-24814](https://jira.appcelerator.org/browse/TIMOB-24814)
- [TIMOB-24819](https://jira.appcelerator.org/browse/TIMOB-24819)
- [TIMOB-24840](https://jira.appcelerator.org/browse/TIMOB-24840)

[6_1_X] backports for 6.1.2

---

Examples/NMocha/src/Assets/ti.ui.label.test.js
Examples/NMocha/src/Assets/ti.ui.textfield.test.js
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Label.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

* [TIMOB-24883](https://jira.appcelerator.org/browse/TIMOB-24883) Incorrect child view size when parent view has border
* [TIMOB-24848](https://jira.appcelerator.org/browse/TIMOB-24848) ListView template with left and right defined causes crash
* [TIMOB-24831](https://jira.appcelerator.org/browse/TIMOB-24831) Layout does not seem to consider left and right properties
* [TIMOB-24828](https://jira.appcelerator.org/browse/TIMOB-24828) Unexpected layout for second UI element in a View
**TIMOB-24883**
```js
view0 = Ti.UI.createView({
top: 20,
bottom: 20,
left: 20,
right: 20,
borderColor: 'blue',
borderWidth: 1,
backgroundColor: 'white'
}),
top: 10,
bottom: 10,
left: 10,
right: 10,
borderColor: 'green',
borderWidth: 10,
backgroundColor: …
```

Fix View layout issues

---

Examples/NMocha/src/Assets/ti.ui.webview.test.js

Increase webview test timeout

---

Examples/NMocha/src/Assets/ti.ui.webview.test.js

[6_2_X] Increase webview test timeout

---

Source/UI/include/TitaniumWindows/UI/SearchBar.hpp
Source/UI/src/SearchBar.cpp

[6_1_X][TIMOB-24966] Implement SearchBar.showCancel

---

cli/commands/_build/config.js
cli/commands/_build/generate.js
package.json

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1028
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24908)

[6_2_X][TIMOB-24908] Add Windows 10 SDK version limits for compatibility

---

templates/build/CMakeLists.txt.ejs

[6_2_X][TIMOB-24957] Unable to place XAML resource in project (#1041)

---

Source/UI/src/SearchBar.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

backports for 6_2_X
- [TIMOB-25044](https://jira.appcelerator.org/browse/TIMOB-25044)
- [TIMOB-25023](https://jira.appcelerator.org/browse/TIMOB-25023)
- [TIMOB-24977](https://jira.appcelerator.org/browse/TIMOB-24977)

[6_2_X][TIMOB-25044][TIMOB-25023][TIMOB-24977]

---

Source/UI/include/TitaniumWindows/UI/Picker.hpp
Source/UI/src/Picker.cpp

[6_2_X][TIMOB_25033] Backport

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Examples/NMocha/src/Assets/ti.ui.scrollview.test.js
Source/TitaniumKit/include/Titanium/UI/Point.hpp
Source/TitaniumKit/src/UI/MatrixCreationDict.cpp
Source/TitaniumKit/src/UI/Point.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/UI/src/ScrollView.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[6_2_X] [TIMOB-24825] Ti.UI.View.center is incorrectly calculated

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js

Skip timob 23225 6 2 x

---

Source/UI/include/TitaniumWindows/UI/SearchBar.hpp
Source/UI/src/SearchBar.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

cherry-pick #1053 and #1059 for 6_2_X

[6_2_X]  #1053 and #1059

---

Source/UI/src/SearchBar.cpp

[TIMOB-24972](https://jira.appcelerator.org/browse/TIMOB-24972)
Implement SearchBar.change event.
```js
var window = Ti.UI.createWindow({ backgroundColor: 'gray' });
var search = Titanium.UI.createSearchBar({
width: 350,
height: 143,
top: 0
});
search.addEventListener('change', function (_evt) {
console.log('change event fired! ' + _evt.value);
});
window.add(search);
window.open();
```
Expected: `change` event should be fired on user input

[TIMOB-24972] Implement SearchBar.change event

---

Examples/NMocha/src/Assets/ti.app.properties.test.js
Source/Ti/include/TitaniumWindows/App/Properties.hpp
Source/Ti/src/App/Properties.cpp
Source/TitaniumKit/include/Titanium/App/Properties.hpp
Source/TitaniumKit/src/App/Properties.cpp
Source/UI/src/SearchBar.cpp
Tools/Scripts/build/build.js
cli/commands/_build/compile.js
cli/commands/_build/config.js
cli/commands/_build/initialize.js
cli/commands/_buildModule.js
cli/lib/stub.js
templates/module/default/hooks/windows-module.js
templates/module/default/template/windows/plugins/hooks/windows.js

Cherry-pick #959, #1061 and #1067 for 6_2_X

[6_2_X] #959 #1061 and #1067

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp
Source/TitaniumKit/include/Titanium/Media/CameraOptionsType.hpp
Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/src/Media/CameraOptionsType.cpp
Source/TitaniumKit/src/UI/Window.cpp
Source/UI/src/TableView.cpp
Source/UI/src/Window.cpp

backport #1036 #1060 #1065 into 6_2_X

[6_2_X] #1036 #1060 #1065 

---

Tools/Scripts/build/test.js
cli/commands/_buildModule.js
package.json

Backport #1073 and #1077 for 6_2_X

[6_2_X][TIMOB-25031][TIMOB-25166] backports

---

apidoc/WindowsOnly/Titanium.UI.Windows.ListViewScrollPosition.yml

apidoc for `Titanium.UI.Windows.ListViewScrollPosition` ([TIMOB-24802](https://jira.appcelerator.org/browse/TIMOB-24802))

[6_2_X][TIMOB-24802]apidoc for Titanium.UI.Windows.ListViewScrollPosition

---

apidoc/WindowsOnly/Titanium.UI.Windows.ListViewScrollPosition.yml

apidoc for `Titanium.UI.Windows.ListViewScrollPosition` ([TIMOB-24802](https://jira.appcelerator.org/browse/TIMOB-24802))

[TIMOB-24802] apidoc for Titanium.UI.Windows.ListViewScrollPosition

---

Source/TitaniumKit/src/Module.cpp
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

Cherry-pick #1083 for 6_2_X
* [[TIMOB-25178](https://jira.appcelerator.org/browse/TIMOB-25178)]
* [[TIMOB-25174](https://jira.appcelerator.org/browse/TIMOB-25174)]

[6_2_X][TIMOB-25178] [TIMOB-25174] ScrollView and Picker layout issues

---

Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Label.cpp

[TIMOB-24814](https://jira.appcelerator.org/browse/TIMOB-24814)
```js
view0 = Ti.UI.createView({
top: 0,
left: 0,
height: Ti.UI.FILL,
width: '50%',
}),
view1 = Ti.UI.createView({
top: 0,
right: 0,
height: 300,
width: 300,
}),
label0 = Ti.UI.createLabel({
width: Ti.UI.SIZE,
color: "#000",
font: {
fontSize: 12
},
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint …
```

[6_2_X][TIMOB-24814] Label regression

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js

Move to using postlayout and the pattern from titanium-mobile-mocha-suite for the 3 failing tests, keep the others as is due to fragility and time

Fix layout tests

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js

Tweak layout test cases for 6_2_X

Tweak layout test cases

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Revert "[TIMOB-24867] borderRadius for View not working"
- Clean up test cases
Cherry-pick #1100 through #1106 for master

Revert "[TIMOB-24867] borderRadius for View not working"

---

Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Label.cpp

[TIMOB-24814] Label regression

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1101
- ~~Re-introduce https://github.com/appcelerator/titanium_mobile_windows/pull/1018~~
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25261) and [TIMOB-24867](https://jira.appcelerator.org/browse/TIMOB-24867)

[6_2_X][TIMOB-24867] Fix panel component events when wrapped by border

---

Jenkinsfile

Reverts appcelerator/titanium_mobile_windows#1113

Revert "Skip tests to get build"

---

cli/commands/_build/generate.js
templates/build/CMakeLists.txt.ejs

[TIMOB-25064](https://jira.appcelerator.org/browse/TIMOB-25064)
Ability to use 3rd party .NET managed DLL with Hyperloop.
**Steps to Test**
1. Create .NET managed DLL 
Create _Universal Windows Class Library_ with Visual C#. It should output only `.dll` other than `.winmd`. You can skip this step by using prebuilt [ManagedClassLibrary1.dll](https://jira.appcelerator.org/secure/attachment/63087/ManagedClassLibrary1.dll).
```cs
using System;
namespace ManagedClassLibrary1
{
public class Test
{
public Test()
{
}
public string Hello()
{
return "Hello, World!";
}
}
}
```
2. Copy your `ManagedClassLibrary1.dll` file into `lib/windows/win10/x86/` under  your Titanium app project folder.
**app.js**
```js
Test = …
```

[TIMOB-25064] Ability to use 3rd party .NET managed DLL with Hyperloop

---

cli/commands/_build/generate.js
templates/build/CMakeLists.txt.ejs

[6_3_X][TIMOB-25064] Ability to use managed DLL with Hyperloop

---

Source/TitaniumKit/include/Titanium/UI/PickerColumn.hpp
Source/TitaniumKit/src/UI/Picker.cpp
Source/TitaniumKit/src/UI/PickerColumn.cpp
Source/UI/include/TitaniumWindows/UI/PickerColumn.hpp
Source/UI/src/PickerColumn.cpp

- [TIMOB-25245](https://jira.appcelerator.org/browse/TIMOB-25245)
- [TIMOB-25246](https://jira.appcelerator.org/browse/TIMOB-25246)
```js
var names = ['Joanie', 'Mickey', 'Jean-Pierre', 'Gustav', 'Raul', 'Mimi', 'Emily', 'Sandra', 'Carrie', 'Chachi'];
var verbs = ['loves', 'likes', 'visits', 'loathes', 'waves to', 'babysits', 'accompanies', 'teaches', 'announces', 'supports', 'knows', 'high-fives'];
var column1 = Ti.UI.createPickerColumn();
for (var i = 0; i < names.length; i++) {
column1.addRow(Ti.UI.createPickerRow({ title: names[i] }));
}
var column2 = Ti.UI.createPickerColumn();
for (i = 0; i < verbs.length; i++) {
column2.addRow(Ti.UI.createPickerRow({ title: verbs[i] }));
}
var column3 = Ti.UI.createPickerColumn();
for (i = (names.length - 1) ; i …
```

[TIMOB-25245] picker.reloadColumn removes all other columns

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[6_3_X][TIMOB-25325] Click event of Button does not provide coordinates

---

Source/Media/src/Media.cpp

[TIMOB-25282](https://jira.appcelerator.org/browse/TIMOB-25282)
`Ti.Media.saveToPhotoGallery()` throws exception.
```js
var file = Ti.Filesystem.getFile('Logo.png')
Ti.Media.saveToPhotoGallery(file, {
success: function (e) {
alert('image done');
},
alert(JSON.stringify(e))
}
});
});
win.open();
```

[TIMOB-25282] saveToPhotoGallery throws exception

---

cli/commands/_build/validate.js

[TIMOB-25357] Add deprecation warning when building using 8.1

---

Jenkinsfile

I think this possibly might fix the error seen in https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile_windows/detail/PR-1120/8/pipeline/
@sgtcoolguy Could this fix that?

Unstash sources in test step

---

Source/UI/src/ListView.cpp

[6_3_X][TIMOB-25175] Unexpected scrollbar appears on ListView

---

Source/UI/src/ListView.cpp
Source/UI/src/TableView.cpp

- [TIMOB-25298](https://jira.appcelerator.org/browse/TIMOB-25298)
- [TIMOB-25273](https://jira.appcelerator.org/browse/TIMOB-25273)
Expected: Unnecessary margin on both side (right & left) should not be appeared for `ListView` and `TableView`.
```js
var data = [];
for (var i = 0; i < 10; i++) {
data.push(Titanium.UI.createTableViewRow({
height: 50,
backgroundColor: i % 2 == 0 ? 'blue' : 'red',
id: i
}));
}
var table = Titanium.UI.createTableView({
data: data,
});
_window.add(table);
```
```js
﻿var win = Ti.UI.createWindow({ backgroundColor: 'green' });
var myTemplate = {
{
type: 'Ti.UI.View',
bindId: 'itemContainer',
properties: {
height: 50,
width: …
```

[TIMOB-25298][TIMOB-25273] Remove margin from ListView/TableView

---

Source/UI/src/ListView.cpp
Source/UI/src/TableView.cpp

[6_3_X][TIMOB-25298][TIMOB-25273] Remove unexpected margin from ListView/TableView

---

Source/UI/src/Label.cpp

[6_3_X][TIMOB-25385] TableViewRow with Label breaks layout

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[6_3_X][TIMOB-25325] Wrong Y-coordinate for click event

---

Source/TitaniumKit/include/Titanium/UI/ScrollView.hpp
Source/TitaniumKit/src/UI/ScrollView.cpp
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

[TIMOB-24964](https://jira.appcelerator.org/browse/TIMOB-24964)
- Implement `ScrollView.scrollToTop`
```js
var win = Ti.UI.createWindow({ backgroundColor: '#fff' });
var view1 = Ti.UI.createView({ width: 20, height: 20, backgroundColor: "#f00", top: 0 });
var view2 = Ti.UI.createView({ width: 20, height: 20, backgroundColor: "#f0f", top: 2000 });
var scrollView = Ti.UI.createScrollView({ height: Ti.UI.FILL, width: Ti.UI.FILL });
var btn1 = Ti.UI.createButton({ title: "scrollUp", top: 10, left: 0 });
var btn2 = Ti.UI.createButton({ title: "scrollDown", bottom: 10, left: 0 });
btn1.addEventListener("click", function (e) { scrollView.scrollToTop() });
btn2.addEventListener("click", function (e) { scrollView.scrollToBottom() });
win.add(btn1);
win.add(btn2); …
```

[TIMOB-24964] Implement ScrollView.scrollToTop

---

Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/src/UI/View.cpp

[TIMOB-25027](https://jira.appcelerator.org/browse/TIMOB-25027)
- Remove `Ti.UI.View.enabled` property
```js
var win = Ti.UI.createWindow({ backgroundColor: '#fff' });
var view = Ti.UI.createButton({
title: 'PUSH THIS?',
enabled: false // this should take no effect
});
alert('It accepts touch event!');
});
win.add(view);
win.open();
```
Expected: button should still accept touch event.

[TIMOB-25027] Remove Ti.UI.View.enabled

---

Source/TitaniumKit/include/Titanium/UI/TextField.hpp
Source/TitaniumKit/src/UI/TextField.cpp
Source/UI/include/TitaniumWindows/UI/TextField.hpp
Source/UI/src/TextField.cpp

[TIMOB-25233](https://jira.appcelerator.org/browse/TIMOB-25233)
```js
var textfield0 = Titanium.UI.createTextField({
top: 100,
value: 'textfield0'
});
_window.addEventListener('open', function () {
textfield0.setSelection(1, 4);
});
_window.add(textfield0);
```
Expected: texts between 1 to 3 character (`'ext'`) is selected.

[TIMOB-25233] Implement TextField.setSelection

---

Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

[TIMOB-24832](https://jira.appcelerator.org/browse/TIMOB-24832)
```js
var header = Ti.UI.createView({
height: 50,
});
var footer = Ti.UI.createView({
height: 50,
backgroundColor: 'gray'
});
var t = Ti.UI.createTableView({
footerView: footer,
});
t.setData([{ title: 'Row 1' }]);
t.headerView = header;
_window.add(t);
```
```js
var header = Ti.UI.createView({
height: 50,
});
var footer = Ti.UI.createView({
height: 50,
backgroundColor: 'gray'
});
var t = Ti.UI.createTableView({
headerView: header,
});
t.setData([{ title: 'Row 1' }]);
t.footerView = footer;
_window.add(t); …
```

[TIMOB-24832] Unable to set TableView.header/footerView after setData

---

cli/commands/_buildModule.js

https://jira.appcelerator.org/browse/TIMOB-25561

[TIMOB-25561] Error if apiversion is incorrect

---

Source/TitaniumKit/src/Application.cpp

[TIMOB-25598](https://jira.appcelerator.org/browse/TIMOB-25598)
When JavaScript has runtime exception, the error messages are shown in Window (aka red screen of death), but there's no detailed information shown in console, like `[ERROR] In undefined: undefined, undefined`,
```js
label = Ti.UI.createLabel({
text: 'Hello, World'
});
var getData = function (_callback) {
_callback({
first: {
name: 'test',
city: 'PA',
distance: 2
}
});
};
var testObject = {
first: {
name: 'test',
city: 'PA',
distance: 2
}
};
function doClick(e) {
getData(function (_data) {
label.text = _data.secondObject.distance;
});
}
label.addEventListener('click', doClick);
win.open();
```
Expected: Following error message should be shown in console when clicking on the …

[TIMOB-25598] No detail info in console on exception

---

Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

[TIMOB-25595](https://jira.appcelerator.org/browse/TIMOB-25595)
```js
var data = [];
var titles = ['Apples', 'Bananas', 'Carrots', 'Potatoes'];
for (var i = 0; i < titles.length; i++) {
var row = Ti.UI.createTableViewRow({ id: titles[i], height: 45});
var view = Ti.UI.createView({backgroundColor: 'red', height: Ti.UI.FILL, width: Ti.UI.FILL});
view.add(Ti.UI.createLabel({ text: titles[i], color: 'black', width: "100%", backgroundColor: 'pink' }));
row.add(view);
data.push(row);
}
var searchbar = Titanium.UI.createSearchBar();
search: searchbar,
filterAttribute: 'id',
filterCaseInsensitive: true,
data: data
});
table.addEventListener('click', function (e) {
alert(JSON.stringify(e.rowData.id));
}); …
```

[TIMOB-25595] Selecting search result shows empty row

---

Source/Network/src/HTTPClient.cpp
tests/Resources/ti.network.httpclient.test.js

[TIMOB-25760](https://jira.appcelerator.org/browse/TIMOB-25760)
```js
var _tmpURL = "https://goo.gl/TckK14"
var _tmpClient = Ti.Network.createHTTPClient({
onload: function (e) {
serverAddressRedirected = _tmpClient.location;
//this should return redirected url
alert("Location:" + serverAddressRedirected);
},
onerror: function (e) {
alert("Error:" + e.error);
},
timeout: 30000
});
_tmpClient.open("GET", _tmpURL);
_tmpClient.send();
```

[TIMOB-25760] Handle HttpClient redirect to get correct location

---

Source/TitaniumKit/include/Titanium/UI/Label.hpp
Source/TitaniumKit/src/UI/Label.cpp
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/Label.cpp

[7_1_X][TIMOB-25648] Implement Ti.UI.Label.minimumFontSize

---

Source/Network/src/Socket/TCP.cpp

[7_1_X][TIMOB-25696] Runtime error in TCP callback causes crash

---

Tools/Scripts/build/test.js
cli/commands/_build/copy.js
cli/commands/_build/generate.js
cli/commands/_build/run.js
cli/commands/_build/write.js
cli/hooks/package.js
cli/hooks/wp-run.js
cli/hooks/ws-run.js

[7_1_X][TIMOB-25743] Auto-increment build number

---

cli/commands/_build/validate.js

7_1_X backport for #1202, see steps there

[7_1_X][TIMOB-24610] Make transpiling off by default

---

Source/LayoutEngine/src/Node.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[7_1_X][TIMOB-25814] UI is not resized properly on incorrect operations

---

Source/TitaniumKit/src/UI/Window.cpp
cli/commands/_build/run.js
templates/build/CMakeLists.txt.ejs

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1210
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25876)

[7_1_X][TIMOB-25876] Support @ character in asset paths

---

Tools/Scripts/build/build.js
Tools/Scripts/generate_project.js
cli/commands/_build/copy.js
cli/commands/_build/run.js
cli/commands/_buildModule.js
templates/build/CMakeLists.txt.ejs
templates/build/cmake/FindHAL.cmake
templates/module/default/hooks/windows-module.js
templates/module/default/template/windows/manifest.ejs

[7_1_X][TIMOB-25895] Rename HAL to AXWAYHAL 

---

Jenkinsfile

Update npm to 5.7.1

---

Tools/Scripts/generate_project.js

Internal tool update for Visual Studio 2017.

Add VS 2017 support in generate_project.js

---

Tools/Scripts/build/build.js
Tools/Scripts/build/package-lock.json
Tools/Scripts/build/package.json

`msbuild` command detection was not working with Visual Studio 2017.
```
node build.js -s 10.0 -m 15.0 -o WindowsStore-x86 -o WindowsStore-ARM
```

VS2017 support for build.js

---

Tools/Scripts/setup.js

[7_2_X] Fix path error in setup.js

---

cli/commands/_build/copy.js

Attempt to fix packaging error on Jenkins.

fix packaging error for scaling assets

---

cli/commands/_build/copy.js

Remove default splash image when scaled asset found.

Attempt to fix build issue on Jenkins.

---

Source/TitaniumKit/include/Titanium/Analytics.hpp
Source/TitaniumKit/src/Analytics.cpp
Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/analytics.js
apidoc/Titanium/Analytics.yml

[7_2_X][TIMOB-26005] Support opt-out of Analytics at runtime

---

cli/commands/_build/analytics.js
cli/commands/_buildModule.js

[TIMOB-26084] Removed project directory from analytics events. Updated copyright years.
https://jira.appcelerator.org/browse/TIMOB-26084

[TIMOB-26084] Removed project directory from analytics events.

---

templates/module/default/template/windows/manifest.ejs

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26106

[7_3_X]TIMOB-26106 Update module apiversion

---

templates/module/default/template/windows/manifest.ejs

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26106

[TIMOB-26106] Update module apiversion

---

Source/TitaniumKit/src/TiModule.cpp
tests/Resources/ti.builtin.addontest.js

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-13379
Implement console.time/timeEnd according to https://console.spec.whatwg.org/#time, with the optional log on `console.time('duplicate label')` implemented, and a slight deviation to log a warning when calling `console.timeEnd('does not exist')`.
```js
console.time('set label'); // Set custom labels
console.time('set label'); // Should log "Label set label already exists" at a warn lebel
setTimeout(() => {
console.timeEnd('set label'); // Should log "set label: 100ms" (not exactly 100ms)
}, 100);
console.time(); // Defaults to "default" if no value passed in
setTimeout(() => {
console.timeEnd(); // Should log "set label: 5000ms" (not exactly 5000ms)
}, 5000);
console.timeEnd('No exist') // Should log "Label No exist does not exist" …
```

[TIMOB-13379] Implement console.time/timeEnd

---

Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp
Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/GeolocationModule.cpp
Source/TitaniumKit/src/Module.cpp
Source/Utility/include/TitaniumWindows/WindowsTiImpl.hpp
tests/Resources/error.test.js

[7_3_X][TIMOB-26048] Refactor RSOD UI 

---

cli/commands/_build/copy.js

- Required for https://github.com/appcelerator/node-titanium-sdk/pull/32
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26117)

[TIMOB-26117] Include resources path

---

Source/TitaniumKit/include/Titanium/UI/2DMatrix.hpp
Source/TitaniumKit/src/UI/2DMatrix.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp
tests/Resources/ti.ui.view.test.js

- [TIMOB-26045](https://jira.appcelerator.org/browse/TIMOB-26045)
```js
});
width: 100,
height: 200
}), matrix = Ti.UI.create2DMatrix({
rotate: 90
}), animation = Ti.UI.createAnimation({
transform: matrix,
duration: 3000
});
win.addEventListener('click', function () {
view.animate(animation);
});
win.add(view);
win.open();
```
Expected: Clicking Window does rotate the view 90 degrees. It should not scale the view.
- [TIMOB-26085](https://jira.appcelerator.org/browse/TIMOB-26085)
```js
});
width: 100,
height: 200,
id: 'view'
}), matrix = Ti.UI.create2DMatrix({
scale: 0.5 …
```

[TIMOB-26045][TIMOB-26085][TIMOB-26086][TIMOB-25542] Fix: 2DMatrix rotation/scale and event source

---

Source/TitaniumKit/include/Titanium/UI/2DMatrix.hpp
Source/TitaniumKit/src/UI/2DMatrix.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp
tests/Resources/ti.ui.view.test.js

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1249
[TIMOB-26045](https://jira.appcelerator.org/browse/TIMOB-26045)
[TIMOB-26085](https://jira.appcelerator.org/browse/TIMOB-26085)
[TIMOB-26086](https://jira.appcelerator.org/browse/TIMOB-26086)
[TIMOB-25542](https://jira.appcelerator.org/browse/TIMOB-25542)

[7_3_X][TIMOB-26045][TIMOB-26085][TIMOB-26086][TIMOB-25542] Fix: 2DMatrix rotation/scale and event source

---

Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/ScrollView.cpp

[7_3_X][TIMOB-26152] ScrollView doesn't return correct event source

---

Source/TitaniumKit/src/UI/listview.js

Cherry-pick #1265 for 7_3_X. 
I would like to push this into `7_3_X` if time permits because it's related to customer ticket.

[TIMOB-26175] Label.text is ignored in ListView template

---

package.json

Pushing again, as I unintentionally closed #1269

[7_3_X][TIMOB-26139] Fix build issue on phone device

---

Source/UI/src/Window.cpp

[TIMOB-26457](https://jira.appcelerator.org/browse/TIMOB-26457)
`Window.exitOnClose` should work on last Window.
Relates to #1285
```js
var win = Ti.UI.createWindow({ exitOnClose: false, backgroundColor: 'yellow' });
win.close();
});
win.open();
```
```js
var newWin;
var win = Ti.UI.createWindow({ exitOnClose: false, backgroundColor: 'yellow' });
win.close();
newWin = Ti.UI.createWindow({ backgroundColor: 'green' });
newWin.open();
});
win.open();
```

[TIMOB-26457] Window.exitOnClose parity

---

Examples/kitchensink-v2/CMakeLists.txt
Source/UI/src/ScrollView.cpp

[7_5_X][TIMOB-26510] Workaround "layout cycle" issue 

---

cli/commands/_build/copy.js
cli/commands/_build/generate.js

[TIMOB-26531] Build fails when module resources has sub folders

---

Source/UI/src/WebView.cpp

[TIMOB-26540] Fix crash when using html property

---

cli/commands/_build/copy.js

Fixes https://jira.appcelerator.org/browse/TIMOB-26564. 
This code is required for hyperloop 2.x which is not supported by SDK 8
This should fix the current build issues on Jenkins fyi @ssjsamir

fix(build): Remove babel requires and unneeded babel traversal step

---

Source/TitaniumKit/src/analytics.js

- Refactor `analytics.js` to implement V4 analytics sepcification
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26357)

[TIMOB-26357] Implement V4 analytics specification

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Update static variable in constructor is theoretically wrong

---

Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp

Remove unnecessary increments

---

cli/commands/_build/copy.js
cli/commands/_build/validate.js

**JIR**: https://jira.appcelerator.org/browse/TIMOB-26146
appcelerator/titanium_mobile#10566

feat: enable transpile by default, opt-out option now

---

Source/TitaniumKit/src/analytics.js

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1347
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26748)

fix(8_0_X): always send full analytics payload

---

cli/hooks/wp-run.js

[8_0_X][TIMOB-26766] Timeout when installing to wp-device

---

cli/commands/_build/checks.js

[TIMOB-26776]  App launch failed with "cyclic redundancy check"

---

apidoc/Titanium/UI/Matrix2D.yml
apidoc/Titanium/UI/NavigationWindow.yml

[TIDOC-3288][TIDOC-3287] Update Ti.UI.NavigationWindow and Matrix2D

---

apidoc/Titanium/UI/Matrix2D.yml
apidoc/Titanium/UI/NavigationWindow.yml

- [TIDOC-3287](https://jira.appcelerator.org/browse/TIDOC-3287)
- [TIDOC-3288](https://jira.appcelerator.org/browse/TIDOC-3288)
Update `Ti.UI.NavigationWindow` and `Matrix2D` documents to indicate Windows support

[8_0_X][TIDOC-3288][TIDOC-3287] Update Ti.UI.NavigationWindow and Matrix2D

---

cli/commands/_build/copy.js

https://github.com/appcelerator/titanium_mobile/commit/9588041218021a94cc0eaa9e222ec762229140e1#diff-c5b02bc76af40eccf082f63f6da1ec91

fix(windows): handle when ti.internal folder does not already exist

---

tests/Resources/app.js

Experimental.
Attempt to workaround crash on Jenkins tests by trying to load less files for platforms.

fix(windows): require less files for platforms

---

Source/TitaniumKit/include/Titanium/UI/WebView.hpp
Source/TitaniumKit/src/UI/WebView.cpp
Source/UI/include/TitaniumWindows/UI/WebView.hpp
Source/UI/src/WebView.cpp
tests/Resources/ti.ui.webview.test.js

[TIMOB-19965](https://jira.appcelerator.org/browse/TIMOB-19965)
```js
});
var blob = Ti.Filesystem.getFile('app.js').read();
var webview = Ti.UI.createWebView({
data: blob,
height: Ti.UI.FILL,
});
webview.addEventListener('load', function () {
Ti.API.info(typeof webview.data);
});
win.add(webview);
win.open();
```
Expected: This should show `app.js` content (with new line ignored) and should print `[INFO] object` in console.

 [TIMOB-19965] Implement WebView.data 

---

tests/Resources/ti.ui.textfield.test.js

fix: textfield.width test failure

---

.eslintrc
Tools/Scripts/build/build.js
Tools/Scripts/build/setupSDK.js
Tools/Scripts/convert_project_to_example.js
Tools/Scripts/generate_cpp_headerfile.js
Tools/Scripts/generate_project.js
Tools/Scripts/module_generator/generate.js
Tools/Scripts/setup.js
apidoc/ti_win_yaml.js
cli/commands/_build/checks.js
cli/commands/_build/copy.js
cli/commands/_build/encrypt.js
cli/commands/_build/generate.js
cli/commands/_build/run.js
cli/commands/_build/write.js
cli/commands/_buildModule.js
cli/hooks/cert.js
cli/hooks/clean.js
cli/hooks/package.js
package-lock.json
package.json
templates/module/default/hooks/windows-module.js

Relates to appcelerator/titanium_mobile#10908

refactor: move from wrench to fs-extra, klaw-sync

---

cli/commands/_buildModule.js

https://jira.appcelerator.org/browse/TIMOB-27257
Fixes TIMOB-27257

fix(build/module): correct variable declaration

---

Jenkinsfile

Relates to: https://github.com/appcelerator/titanium_mobile/pull/11336

ci(jenkins): use node 10.17.0 to build/test

---

Jenkinsfile
apidoc/WindowsOnly/Ti.App.Windows.BackgroundService.yml
apidoc/WindowsOnly/Ti.App.Windows.BackgroundServiceTask.yml
apidoc/WindowsOnly/Titanium.App.Windows.yml
apidoc/WindowsOnly/Titanium.Network.Socket.UDP.yml
apidoc/WindowsOnly/Titanium.UI.Windows.AppBarButton.yml
apidoc/WindowsOnly/Titanium.UI.Windows.AppBarSeparator.yml
apidoc/WindowsOnly/Titanium.UI.Windows.AppBarToggleButton.yml
apidoc/WindowsOnly/Titanium.UI.Windows.CommandBar.yml
apidoc/WindowsOnly/Titanium.UI.Windows.ListViewScrollPosition.yml
apidoc/WindowsOnly/Titanium.UI.Windows.Style.yml
apidoc/WindowsOnly/Titanium.UI.Windows.SystemIcon.yml
apidoc/WindowsOnly/Titanium.UI.Windows.yml

**JIRA:**
https://jira.appcelerator.org/browse/TIDOC-3392

docs: mark windows apis as removed

---

apidoc/Titanium/JSON.yml

To be in sync with https://github.com/appcelerator/titanium_mobile/pull/11479

docs(apidoc): delete JSON.yml
