appcelerator/titanium_mobile_windows

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/ImageView.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-18684](https://jira.appcelerator.org/browse/TIMOB-18684)
To test this, make sure following code shows 75x75 image at (top=0,left=0), and also `NG` and `Corporate` app works as expected.
```javascript
var window = Ti.UI.createWindow({ backgroundColor: 'blue' });
var view = Ti.UI.createImageView({
image: 'http://api.randomuser.me/portraits/women/0.jpg',
width: 75,
top: 0,
left: 0
});
window.add(view);
window.open();
```

[TIMOB-18684] View width/height is ignored when use with Ti.UI.SIZE

---

Source/API/src/API.cpp

Fix for [TIMOB-18322](https://jira.appcelerator.org/browse/TIMOB-18322).
To test this, copy & paste following code, make sure you saved your `app.js` as UTF-8 file, then you'll see these messages in VS output log. Note that you may need to wait for few seconds to see output in VS console because log functions are using async.
```
Ti.API.info('[TEST] TEST');
Ti.API.info('[TEST] 表示テスト');
```

Support UTF-8 logging

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/LayoutEngine/src/Composite.cpp
Source/UI/src/ImageView.cpp
Source/UI/src/ScrollView.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Related to #206.
- Fix crash at sizeFillConflict unit test on Release build [TIMOB-18790](https://jira.appcelerator.org/browse/TIMOB-18790)
- Add unit test for [TIMOB-18684](https://jira.appcelerator.org/browse/TIMOB-18684). Related to #204.
- Implement `load` event for `Ti.UI.ImageView` which is fired when image is loaded.
- Fix ScrollView layout issue [TIMOB-18819](https://jira.appcelerator.org/browse/TIMOB-18819)
- Implement "postlayout" UI event [TIMOB-18785](https://jira.appcelerator.org/browse/TIMOB-18785)

Fix crash at sizeFillConflict unit test on Release build

---

Source/API/src/API.cpp
Source/Accelerometer/src/Accelerometer.cpp
Source/LayoutEngine/src/Horizontal.cpp
Source/LayoutEngine/src/ParseProperty.cpp
Source/LayoutEngine/src/Vertical.cpp
Source/Titanium/src/File.cpp
Source/Titanium/src/File.hpp
Source/TitaniumKit/examples/NativeFileExample.cpp
Source/TitaniumKit/examples/NativeFileExample.hpp
Source/TitaniumKit/include/Titanium/Blob.hpp
Source/TitaniumKit/include/Titanium/Filesystem/File.hpp
Source/TitaniumKit/src/Blob.cpp
Source/TitaniumKit/src/Filesystem/File.cpp
Source/TitaniumKit/src/Network/HTTPClient.cpp
Source/UI/src/ImageView.cpp
Source/UI/src/Label.cpp

Related to #212, and reflect cpplint result for better code.
- Update to latest HAL
- Make sure variables are properly initialized
- Use `std::int64_t` instead of `long long`
- Remove duplicate `include`

Make sure variables are properly initialized

---

Examples/NMocha/src/Assets/ti.database.test.js
Source/TitaniumKit/include/Titanium/Database/DB.hpp
Source/TitaniumKit/include/Titanium/Database/ResultSet.hpp
Source/TitaniumKit/src/Database/DB.cpp
Source/TitaniumKit/src/Database/ResultSet.cpp
Source/TitaniumKit/src/DatabaseModule.cpp

- [TIMOB-18562](https://jira.appcelerator.org/browse/TIMOB-18562) Database module doesn't properly clean up ResultSets
- [TIMOB-18696](https://jira.appcelerator.org/browse/TIMOB-18696) Ti.Database.ResultSet interface should not use HAL types
- [TIMOB-18695](https://jira.appcelerator.org/browse/TIMOB-18695) Ti.Database.DB interface should not use HAL types 
For "removing HAL types", I noticed that you don't have to make methods `virtual` and just use HAL types as it is because Database module is cross-platform and thus nobody extends it. Because original purpose of "removing HAL types" is meant to separate TitaniumKit from platform-specific modules, I think this fix fits the requirement.

Fix: Database module doesn't properly clean up ResultSets

---

Source/TitaniumKit/include/Titanium/Database/DB.hpp
Source/TitaniumKit/include/Titanium/Database/ResultSet.hpp
Source/TitaniumKit/include/Titanium/UI/TextArea.hpp
Source/TitaniumKit/src/Database/DB.cpp
Source/TitaniumKit/src/Database/ResultSet.cpp
Source/TitaniumKit/src/UI/TextArea.cpp

Related to #220 
Database should receive callback from ResultSet when it's closed and then DB should release shared pointer to the ResultSet. Pretty similar logic that how Ti.Current (iOS) does.

DB should release ResultSet when it's closed

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Examples/NMocha/src/Assets/ti.ui.window.test.js
Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/src/Module.cpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/AlertDialog.cpp
Source/UI/src/View.cpp
Source/UI/src/WebView.cpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Part of [TIMOB-18734](https://jira.appcelerator.org/browse/TIMOB-18734)
- Implement Window navigation
- Implement Window blur event
- Some tweaks around window events
To test this, use following code and see if window navigation stack works as expected. Note that application should exit when `win1` is closed.
```javascript
title: 'Window 1',
backgroundColor: 'Blue'
});
var win2 = Titanium.UI.createWindow({
title: 'Window 2',
backgroundColor: 'Yellow'
});
var win3 = Titanium.UI.createWindow({
title: 'Window 3',
backgroundColor: 'Green'
});
win1.addEventListener('focus', function () {
Ti.API.info('win1 focus');
});
win1.addEventListener('blur', function () {
Ti.API.info('win1 blur');
});
var button1 = Ti.UI.createButton({
top:  20,
left: 10,
title: …
```

Implement Window navigation

---

Tools/Scripts/module_generator/generate.js
Tools/Scripts/module_generator/module_template/TitaniumKit/include/Titanium/Module.hpp
Tools/Scripts/module_generator/module_template/TitaniumKit/src/Module.cpp

- At the TitaniumKit level, add stubs for every method and property. We should only filter down to cross -Android and -iOS for our Windows impl as a first pass at which ones to implement. But TK should always have the full set of Titanium APIs.
- Update the templates to use our new macros

Module generator updates

---

Examples/Corporate/src/Assets/alloy/controllers/profile.js
Source/TitaniumKit/include/Titanium/Module.hpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Window.cpp
Source/UI/src/Windows/SystemIcon.cpp

Fix for [TIMOB-18734](https://jira.appcelerator.org/browse/TIMOB-18734)
- Add `windows:back` event which handles hardware back button
- Navigate back to directory window on back button event (Corporate app)
To check how this works on Corporate app, navigate to profile view and then press hardware back button and see if it navigates back to directory view.

[TIMOB-18734] Fix: No way to navigate back to directory view

---

Tools/Scripts/setup.js

It was originally because JavaScriptCore returns wrong value for `new Date()` so we just need to upgrade the library.

[TIMOB-18855] Fix: new Date() returns wrong value

---

Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Window.cpp

Fix for [TIMOB-18856](https://jira.appcelerator.org/browse/TIMOB-18856).
To test this, use following code and see if hardware back button closes current Window.
```javascript
title: 'Window 1',
backgroundColor: 'Blue'
});
var win2 = Titanium.UI.createWindow({
title: 'Window 2',
backgroundColor: 'Yellow'
});
var win3 = Titanium.UI.createWindow({
title: 'Window 3',
backgroundColor: 'Green'
});
/*
win1.addEventListener('windows:back', function () {
win1.close();
});
win2.addEventListener('windows:back', function () {
win2.close();
});
win3.addEventListener('windows:back', function () {
win3.close();
});
*/
win1.addEventListener('focus', function () {
Ti.API.info('win1 focus');
});
win1.addEventListener('blur', function () {
Ti.API.info('win1 blur');
}); …
```

[TIMOB-18856] Hardware back button should close Ti.Window

---

Source/TitaniumKit/src/UI/Animation.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Implement [TIMOB-18753 Windows: Support curve/easing functions on Animations](https://jira.appcelerator.org/browse/TIMOB-18753)
- Implement [TIMOB-18752 Windows: Support animations of height, width and
zIndex properties](https://jira.appcelerator.org/browse/TIMOB-18752)
This doesn't try to handle left/right/center because it'd involve dealing
with precedence and differing ways to calculate height/width.
ZIndex animations don't use curves or transition over time. They simply go
from one value at the beginning to suddenly changing to the new value at
the end.
Curves use Windows CubicEase. There's no equivalent to iOS's curve
functions. We also should consider exposing a new "default" curve option
because of undocumented use in iOS (it uses a different easing function
than the other …

Animation improvements

---

Source/Network/include/TitaniumWindows/Network/HTTPClient.hpp
Source/Network/src/HTTPClient.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/examples/NativeBlobExample.cpp
Source/TitaniumKit/examples/NativeBlobExample.hpp
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/Network/Constants.hpp
Source/TitaniumKit/include/Titanium/Network/Cookie.hpp
Source/TitaniumKit/include/Titanium/Network/HTTPClient.hpp
Source/TitaniumKit/include/Titanium/Network/PushNotificationConfig.hpp
Source/TitaniumKit/include/Titanium/Network/Socket.hpp
Source/TitaniumKit/include/Titanium/Network/Socket/AcceptDict.hpp
Source/TitaniumKit/include/Titanium/Network/Socket/TCP.hpp
Source/TitaniumKit/include/Titanium/Network/Socket/UDP.hpp
Source/TitaniumKit/include/Titanium/NetworkModule.hpp
Source/TitaniumKit/include/Titanium/detail/TiBase.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/Network/Constants.cpp
Source/TitaniumKit/src/Network/Cookie.cpp
Source/TitaniumKit/src/Network/HTTPClient.cpp
Source/TitaniumKit/src/Network/PushNotificationConfig.cpp
Source/TitaniumKit/src/Network/Socket.cpp
Source/TitaniumKit/src/Network/Socket/AcceptDict.cpp
Source/TitaniumKit/src/Network/Socket/TCP.cpp
Source/TitaniumKit/src/Network/Socket/UDP.cpp
Source/TitaniumKit/src/NetworkModule.cpp
Source/TitaniumKit/src/UI/ScrollableView.cpp
Source/TitaniumKit/test/NetworkTests.cpp
Source/TitaniumKit/xcode/TitaniumKit.xcodeproj/project.pbxproj

[TIMOB-18759](https://jira.appcelerator.org/browse/TIMOB-18759) Windows: Stub out all properties/methods of Titanium.Network in TitaniumKit
- Ti.Network
- Ti.Network.HTTPClient
- Ti.Network.Cookie
- [AcceptDict](http://docs.appcelerator.com/titanium/3.0/#!/api/AcceptDict)
- [PushNotificationConfig](http://docs.appcelerator.com/titanium/3.0/#!/api/PushNotificationConfig)
- Ti.Network.Socket
- Ti.Network.Socket.TCP
- Ti.Network.Socket.UDP
- Ti.Network related constants
- Ti.Network related enums
- Unit tests (TitaniumKit)

Stub out all properties/methods of Titanium.Network in TitaniumKit

---

cli/commands/_build.js
cli/lib/stub.js

- parse JS files with UglifyJS, look for require calls with a single
string argument. If string begins with "Windows." treat as native type,
and add it to list of wrappers to generate.
This is an extremely naive check. Basically, if users want to use native APIs, they need to use static strings in typical require calls. Dynamically building the string won't be picked up. I think if they want to do that we should have some overriding option for them to declare they want _all_ APIs generated, or some way to generate a whitelist of types they need. Assuming we should generate everything when we run into dynamic requires would be horrendous for build time/app size.

TIMOB-18882 Crawl user's app for native requires

---

Tools/Scripts/build/build.js
Tools/Scripts/build/package.json
Tools/Scripts/build/test.js
cli/commands/_buildModule.js
templates/build/cmake/FindJavaScriptCore.cmake
templates/module/default/hooks/windows-module.js
templates/module/default/template/windows/CMakeLists.txt.ejs
templates/module/default/template/windows/build_and_test.sh.ejs
templates/module/default/template/windows/cmake/{{ModuleName}}_Config.cmake
templates/module/default/template/windows/include/{{ModuleName}}.hpp.ejs
templates/module/default/template/windows/manifest.ejs
templates/module/default/template/windows/src/{{ModuleName}}.cpp.ejs
templates/module/default/template/windows/test/CMakeLists.txt.ejs
templates/module/default/template/windows/timodule.xml

- Created project structure for native modules
- Created templates for module project generation
- Implemented a CLI hook to generate the Visual Studio projects using CMake
- Updated build script to copy over necessary header files (HAL and TitaniumKit) into the SDK ```windows/lib/*/include``` directory for successful module compilation
- Added ```WindowsStore``` ```ARM``` to build script
[TIMOB-18978](https://jira.appcelerator.org/browse/TIMOB-18978) - https://github.com/appcelerator/titanium_mobile/pull/6892
- I have updated the ```build.js``` script to use ```fs-extra``` as I was having problems with ```wrench```
- @infosia Do you still need ```classname``` or can you use ```moduleid```?
**EPIC** [TIMOB-17911](https://jira.appcelerator.org/browse/TIMOB-18937)
- …

[TIMOB-18937][TIMOB-18938][TIMOB-18939][TIMOB-18942] Add module support to the CLI - READY

---

apidoc/ti_win_yaml.js

- Ignore methods beginning with _ (e.g: ```_loadAppInfo```)
- Fix whitespace bug

YAML generator: Fix whitespace bug, ignore underscore methods

---

templates/build/cmake/internal_utils.cmake

- Remove ```GTest``` package requirement
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18987)

[TIMOB-18987] App build fails if GTEST is not present on system

---

cli/commands/_build.js

- Force delete any existing folder before copying
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18981)

[TIMOB-18981] Resources are not copied from temp folder to build folder

---

cli/commands/_build.js
cli/hooks/wp-run.js

Fix for [TIMOB-18989](https://jira.appcelerator.org/browse/TIMOB-18989).
Steps To Reproduce
1. Create a project using ti create with a space in the name (i.e. "space app")
2. Build the project for Windows using `ti build p windows -T wp-device`

[TIMOB-18989] Unable to build a project if the project name contains a space

---

Source/UI/src/AlertDialog.cpp

Fix for [TIMOB-18980](https://jira.appcelerator.org/browse/TIMOB-18980).
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });
var button = Titanium.UI.createButton({
top: 60,
title: 'Hello',
width: '180',
height: '80'
});
button.addEventListener('click', function () {
var dialog = Ti.UI.createAlertDialog({
title: 'Push OK',
buttonNames: ['OK']
});
dialog.addEventListener('click', function (e) {
alert('HELLO!');
});
dialog.show();
});
win.open();
```

[TIMOB-18980] Fix:  Closing an alert crashes the app

---

cli/commands/_build.js

Fix for [TIMOB-18974](https://jira.appcelerator.org/browse/TIMOB-18974).
Steps To Reproduce
1. Create a new application using ti create
2. Run the application using ti build -p windows -T wp-device --build-only

[TIMOB-18974] Fix: Building a project with the --build-only flag errors out

---

cli/commands/_build.js
cli/lib/stub.js
cli/lib/templates/Proxy.cpp
cli/lib/templates/Proxy.hpp
cli/lib/templates/add_event_handler.cpp
cli/lib/templates/function.cpp
cli/lib/templates/js_to_native.cpp
cli/lib/templates/js_to_native_class.cpp
cli/lib/templates/js_to_native_enum.cpp
cli/lib/templates/js_to_native_primitive.cpp
cli/lib/templates/js_to_native_struct.cpp
cli/lib/templates/native_class_to_js.cpp
cli/lib/templates/native_primitive_to_js.cpp
cli/lib/templates/native_struct_to_js.cpp
cli/lib/templates/remove_event_handler.cpp

https://jira.appcelerator.org/browse/TIMOB-18883
Adding event handlers on native types is done more like Titanium event handling, not hyperloop.
```javascript
var Window = require('Windows.UI.Xaml.Window'),
TextBlock = require('Windows.UI.Xaml.Controls.TextBlock'),
window = Window.Current,
text = new TextBlock();
text.Text = "Click me, please!";
text.TextAlignment = Windows.UI.Xaml.TextAlignment.Center;
text.VerticalAlignment = Windows.UI.Xaml.VerticalAlignment.Center;
text.HorizontalAlignment = Windows.UI.Xaml.HorizontalAlignment.Center;
text.FontSize = 60;
text.addEventListener('Tapped', function() {
alert('You touched it!');
});
window.Content = text;
window.Activate();
```

[TIMOB-18883] Windows: Allow registering event handlers with callback functions

---

cli/commands/_build.js
cli/lib/stub.js

If you `--log-level info` you'll get a nice short console; debug will
give you a little more progress, and trace will give you the full amount
we had before. Reduces it to just a couple screens of data when run at
info level.
https://jira.appcelerator.org/browse/TIMOB-18973

[TIMOB-18973] Reduce Clutter of Logs

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Use actual PPI instead of ```1```
- This allows ```cm, in and dp``` to be calculated correctly
```Javascript
var win = Titanium.UI.createWindow({
});
var view = Titanium.UI.createView({
width: '1in',
height: '10dp'
});
win.add(view);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18999)

[TIMOB-18999] Use actual PPI when populating layout properties

---

Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/UI/src/TableView.cpp

Fix for [TIMOB-19013](https://jira.appcelerator.org/browse/TIMOB-19013).
Example: TableView constructed from array of JS object
```javascript
var tableData = [{ title: 'Apples' }, { title: 'Bananas' }, { title: 'Carrots' }, { title: 'Potatoes' }];
data: tableData
});
table.addEventListener('click', function (e) {
alert(e.rowData);
});
win.open();
```
Example: TableView constructed from array of TableViewSection
```javascript
var sectionFruit = Ti.UI.createTableViewSection({ headerTitle: 'Fruit' });
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Apples' }));
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Bananas' }));
var sectionVeg = Ti.UI.createTableViewSection({ …
```

Fix: crash when triggering eventListener on a table view

---

Source/Titanium/src/TitaniumWindows.cpp

We never set up our Windows implementation to "override" the TitaniumKit Geolocation module.

Fix TIMOB-19022 Windows: Geolocation never returning data for getCurrentPosition

---

Source/Network/include/TitaniumWindows/Network/HTTPClient.hpp
Source/Network/src/HTTPClient.cpp

The initial error was because we didn't "skip" setting up a timeout timer when timeout was 0 (or less). Since timeout defaults to 0, we always cancelled the request immediately.
I also took the time to clean up the code so we didn't have three separate "send" implementations. Now they all just gather up the content object they need to send and call the shared send implementation.

Fix TIMOB-19023 Windows: HTTPClient GET is failing

---

Tools/Scripts/build/test.js
cli/commands/_build.js
templates/build/Package.phone.appxmanifest.in.ejs
templates/build/Package.store.appxmanifest.in.ejs

[TIMOB-18995](https://jira.appcelerator.org/browse/TIMOB-18995)
Provide ability to set capabilities on appx.manifest in tiapp.xml. Not only `Capabilities` but also `Properties`, `﻿Prerequisites` and `Resources` are supported.
```xml
<windows>
<manifest>
<Capabilities>
<Capability Name="internetClient" />
</manifest>
</windows>
```
By providing `target` attribute, you can setup platform-specific properties. Entries with no target means common properties across `phone` and `store`.
Updated: See example at https://github.com/appcelerator/titanium_mobile_windows/pull/278#issuecomment-111519660
In this case this ends up with `location` and `internetClient` capabilities set for `phone` app.
```xml
<Capabilities>
<Capability Name="location" />
<Capability Name="internetClient" /> …
```

Provide ability to set capabilities on appx.manifest in tiapp.xml

---

Source/Sensors/include/TitaniumWindows/Geolocation.hpp
Source/Sensors/src/Geolocation.cpp

Quick fix for [TIMOB-19028](https://jira.appcelerator.org/browse/TIMOB-19028). Developer should take care of the timing when first use of Geolocation, which should be done on UI thread according to the [guideline](https://msdn.microsoft.com/en-us/library/windows/apps/hh465148.aspx).
```javascript
Ti.Geolocation.addEventListener('location', ...); // should be done on the UI thread!
```

Fix: Geolocation module should instantiate Geolocator on-demand

---

Source/TitaniumKit/include/Titanium/ErrorResponse.hpp
Source/TitaniumKit/include/Titanium/Map/CameraAnimationParams.hpp
Source/TitaniumKit/include/Titanium/Map/MapLocationTypev2.hpp
Source/TitaniumKit/include/Titanium/Map/MapRegionTypev2.hpp
Source/TitaniumKit/include/Titanium/Media/CameraMediaItemType.hpp
Source/TitaniumKit/include/Titanium/Media/CameraOptionsType.hpp
Source/TitaniumKit/include/Titanium/Media/MediaQueryInfoType.hpp
Source/TitaniumKit/include/Titanium/Media/MediaQueryType.hpp
Source/TitaniumKit/include/Titanium/Media/MusicLibraryOptionsType.hpp
Source/TitaniumKit/include/Titanium/Media/MusicLibraryResponseType.hpp
Source/TitaniumKit/include/Titanium/Media/PhotoGalleryOptionsType.hpp
Source/TitaniumKit/include/Titanium/Media/PreviewImageOptions.hpp
Source/TitaniumKit/include/Titanium/Media/RouteDescription.hpp
Source/TitaniumKit/include/Titanium/Network/PushNotificationConfig.hpp
Source/TitaniumKit/include/Titanium/Network/Socket/AcceptDict.hpp
Source/TitaniumKit/include/Titanium/UI/Dimension.hpp
Source/TitaniumKit/include/Titanium/UI/Font.hpp
Source/TitaniumKit/include/Titanium/UI/Gradient.hpp
Source/TitaniumKit/include/Titanium/UI/ListViewMarkerProps.hpp
Source/TitaniumKit/include/Titanium/UI/MatrixCreationDict.hpp
Source/TitaniumKit/include/Titanium/UI/Point.hpp
Source/TitaniumKit/include/Titanium/UI/ShadowDict.hpp
Source/TitaniumKit/include/Titanium/UI/TitleAttributesParams.hpp

Followup for [TIMOB-18992](https://jira.appcelerator.org/browse/TIMOB-18992)
Export utility functions for Titanium abstract types such as `Titanium::UI::js_to_Point`.

Export functions for Titanium abstract types

---

Tools/Scripts/build/build.js
templates/build/cmake/FindLayoutEngine.cmake

Followup for [TIMOB-18992](https://jira.appcelerator.org/browse/TIMOB-18992).
Package all headers including `TitaniumWindows` for Titanium SDK build, because it may be used by module developers. For example `ti.map` may need access to constants in `TitaniumWindows::UI` as well as `Titanium::UI::View`.

Package all headers including TitaniumWindows

---

Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/GlobalObject.cpp
Source/TitaniumKit/src/Module.cpp

Fix for [TIMOB-19034](https://jira.appcelerator.org/browse/TIMOB-19034).
```javascript
win.add(Ti.UI.createLabel({ text: 'Please Wait...' }));
win.open();
setTimeout(function() {
throw new Error('oh no!');
}, 2000);
```
And
```javascript
title: 'PUSH'
});
throw new Error('oh no!');
});
win.open();
```

Fix: Building to Emulator Should Allow Error Dialogs

---

Source/Ti/src/Platform.cpp

Get processor count, add FIXME about architecture, report availableMemory on Phone
I was playing around seeing if it's feasible to implement a node-compatible native "os" module and needed some values we report from Ti.Platform. We seem to be lacking some of them, so I tried to fix a couple.

Ti.Platform tweaks

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Source/Network/src/HTTPClient.cpp
Source/TitaniumKit/src/Network/HTTPClient.cpp

We used to set HTTP request headers for GET only, then when I refactored for the fix recently even that got removed. This is an attempt to bring it back for all request methods.

Fix to actually set request headers before making the request.

---

Source/Ti/src/API.cpp

- Prevent ```Ti.API.info()``` from causing a buffer overflow by splitting up the output
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19043)

[TIMOB-19043] Prevent Ti.API.info() buffer overflow

---

Source/TitaniumKit/src/UI/Slider.cpp
Source/UI/include/TitaniumWindows/UI/Slider.hpp
Source/UI/src/Slider.cpp

The problem is that we need to override the getter for value in the Windows subclass to always return the value from the widget itself, rather than just parrot back the internal value field (which is only changed by the property setter, not from actually manipulating the widget).
https://jira.appcelerator.org/browse/TIMOB-19044

Fix TIMOB-19044 Windows: Accessing a sliders value always returns 0

---

Tools/Scripts/build/build.js

Add build step to replace hard-coded placeholder values in TiModule for git hash and build date

TIMOB-19031 Windows: Update Ti.version and Ti.buildDate properties on CI build

---

Source/TitaniumKit/src/Module.cpp

These logs should be debug logs and not error logs.
```
TitaniumKit 000000120 Mon Jun 22 16:03:50 2015 ERROR: Module::eventListenerIndex: index = 0 for event 'click'.
```

Error log should be debug log

---

Source/Ti/src/TiModule.cpp
Tools/Scripts/build/build.js

Build for the various targets and architectures in parallel, and then copy over the various files in parallel. Builds take about 30 minutes for me using this, and they _appear_ to work as normal. (I say _appear_
because I'm just poking around with an app to test.)

Parallelize Builds

---

Tools/Scripts/build/test.js
cli/commands/_build/generate.js
cli/commands/_build/validate.js
cli/hooks/ws-package.js

We attempt to use the value if it's there in tiapp, otherwise we generate one with"CN=" + tiapp.publisher (and log a warning). If there's no publisher (display name) then we show an error message about needing the value and exit with error code 1.
https://jira.appcelerator.org/browse/TIMOB-19009
https://jira.appcelerator.org/browse/TIMOB-19025

ti.windows.publishername tweaks

---

Source/TitaniumKit/include/Titanium/detail/TiUtil.hpp

Currently all PR is failing because Travis build is failing at `TitaniumKit`.

Fix compile error in TitaniumKit on Travis

---

Source/UI/src/AlertDialog.cpp

Fix for [TIMOB-19065](https://jira.appcelerator.org/browse/TIMOB-19065)
Following code should show Application Error dialog on debug mode with appropriate error message. Originally I thought we could check number of buttons available and assert when it's too much, but it turns out  there's no documentation on limitation of the number [according to Microsoft](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.popups.messagedialog.commands). So we just can check if it throws exception and re-throw it with error message.
```javascript
var button = Ti.UI.createButton({ title: 'PUSH' });
button.addEventListener('click', function () {
Ti.UI.createAlertDialog({
title: 'Title',
message: 'Message',
buttonNames: ['A', 'B', 'C']
}).show();
}); …
```

Fix: AlertDialog.show() fails with "unknown error" message

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

- Throw runtime error when attempting to add a single instance of a child element to multiple views.
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19038)

[TIMOB-19038] Throw descriptive runtime error when adding a child to multiple parent views

---

cli/commands/_buildModule.js
templates/module/default/hooks/windows-module.js
templates/module/default/template/windows/CMakeLists.txt.ejs

:star:  There's a fix in the CMakeLists.txt template that had a bad reference to HAL that would cause warnings during the build process.
But for the main ticket:
- Before we run cmake, we check to see if running it inside the temp dir would result in a shorter path than running in current location. If so we run in temp dir. Later when we do the build, we check the configured build directory and if it's in temp, we ensure we copy over the stuff we need there if it'snot there still.

Fix TIMOB-19052 Windows: ti create for modules with long paths fails with cryptic errors

---

Source/UI/src/Label.cpp

Revert #317, because it introduces another layout issue. For example it breaks layout of the default app template, the "I am Window 1" label should have been aligned in center of the view but it's not.
Also, I am not sure if [TIMOB-19048](https://jira.appcelerator.org/browse/TIMOB-19048) is valid, because :
- According to [Transitioning to the New UI Layout System](http://docs.appcelerator.com/platform/latest/#!/guide/Transitioning_to_the_New_UI_Layout_System), default layout of `Ti.UI.Label` should be `Ti.UI.SIZE` for both `width` and `height`.
- API document for [Ti.UI.Label](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.Label) doesn't specify how it should resize itself when text is longer than UI width. (For example, should it change its height when width is too …

Revert #317

---

templates/module/default/template/windows/CMakeLists.txt.ejs

Fix for [TIMOB-19108](https://jira.appcelerator.org/browse/TIMOB-19108).

Fix: Creating windows module errors out due to missing boost libraries

---

cli/commands/_build/encrypt.js
cli/commands/_build/validate.js

- Retry using 64-bit ```titanium_prep``` if 32-bit failed with ```JAVA_HOME``` error, caused by it being set to a 64-bit JRE
- Fix logger in ```validate.js```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19107)

[TIMOB-19107] Fix 64-bit Java support

---

Examples/NMocha/src/Assets/ti.platform.test.js
Source/Ti/src/Platform.cpp
Source/TitaniumKit/src/analytics.js

https://jira.appcelerator.org/browse/TIMOB-19127
This adds more testing of the createUUID value in our unit tests to validate that the UUID is 36 characters long, doesn't start with open brace or end with close brace and tests against a regexp for format.
I also remove the hacks around the issue in analytics.

TIMOB-19127 Windows: Ti.Platform.createUUID() should not have curly brackets

---

Source/UI/src/OptionDialog.cpp

https://jira.appcelerator.org/browse/TIMOB-19123
Same issue we ran into with AlertDialog and fixed in this commit: https://github.com/appcelerator/titanium_mobile_windows/commit/a5b5306870fb622a49f9f7a2526b43ff47dece7d

Fix TIMOB-19123 Ti.UI.OptionDialog crashes with unknown exception

---

Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

https://jira.appcelerator.org/browse/TIMOB-19130
```javascript
top: 100,
width: 100,
height: 100,
});
win.add(view);
var btn = Ti.UI.createButton({
top: 300,
title: 'Click'
});
btn.addEventListener('click', function (e) {
win.remove(view);
});
win.add(btn);
win.open();
```

Fix TIMOB-19130 Ti.UI.Window.remove() generates runtime error, view is not removed

---

cli/commands/_build/validate.js

https://jira.appcelerator.org/browse/TIMOB-19104
A good example is to set your tiapp publisher value to "Appcelerator, Inc." (like some of our samples do) and make sure the build doesn't break.

TIMOB-19104 Windows: If generating ti.windows.publishername from tiapp publisher value, escape invalid characters

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

- Fix ```left, right``` and ```top, bottom``` scaling for sized components such as ```TextField```
```Javascript
});
var viewA = Ti.UI.createTextField({
hintText: 'SOME TEXT',
top: '5dp',
left: '10dp',
// removing this line should allow the TextField to scale according to its contents
// retaining this line should scale the TextField to the same size as the red view below
right: '10dp',
height: '40dp'
});
var viewB = Ti.UI.createView({
top: '60dp',
left: '10dp',
right: '10dp',
height: '40dp'
});
win.add(viewA);
win.add(viewB);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19119)

[TIMOB-19119] Fix LayoutEngine 'left, right' and 'top, bottom' scaling

---

Tools/Scripts/generate_cpp_headerfile.js

Very simple tool to convert JS files into C++ header files all at once. It is useful when you debug `*.js` files in TitaniumKit, to avoid running `cmake` every time you update the JS file.
How to Use:
```bash
$ # update JS file, for example Source/TitaniumKit/src/analytics.js
$ vi Source/TitaniumKit/src/analytics.js
$ node Tools/Scripts/generate_cpp_headerfile.js
$ # Source/TitaniumKit/include/Titanium/analytics_js.hpp is updated!
```

Simple tool to convert JS files into C++ header files all at once

---

Source/UI/src/Button.cpp
Source/UI/src/TextField.cpp

- Reset component ```MinWidth``` for ```Button``` and ```TextField```
```Javascript
});
var viewA = Ti.UI.createTextField({
top: '5dp',
width: '20dp',
height: '20dp'
});
var viewB = Ti.UI.createView({
backgroundColor: 'white',
top: '35dp',
width: '20dp',
height: '20dp'
});
var viewC = Ti.UI.createButton({
top: '55dp',
width: '20dp',
height: '20dp'
});
win.add(viewA);
win.add(viewB);
win.add(viewC);
win.open();
```
I don't think this https://github.com/appcelerator/titanium_mobile_windows/blob/master/Source/UI/src/TextField.cpp#L40 has any effect any more
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19143)

[TIMOB-19143] Fix width sizing for Button and TextField

---

Source/Global/include/TitaniumWindows/GlobalObject.hpp
Source/Global/src/GlobalObject.cpp
Source/Titanium/src/TitaniumWindows.cpp

- Allows unencrypted file types to load by checking if an ```.iv``` is present
- ```seed__``` is now a ```::Platform::String^``` to prevent unnecessary string conversions
- Changed variable names to match our naming convention
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19152)

[TIMOB-19152] Allow encrypted file types to load if they are not encrypted

---

cli/commands/_build/generate.js
cli/hooks/wp-run.js
templates/build/Package.phone.appxmanifest.in.ejs
templates/build/Package.store.appxmanifest.in.ejs

This attempts to enforce a 4 part version string and passes that version into the app manifest. CMake also can take up to 4 version segments, so using same version variable for both looks OK.
https://jira.appcelerator.org/browse/TIMOB-19175

Fix TIMOB-19175 Windows: Tiapp version isn't populated into app's manifest file

---

cli/commands/_build/copy.js

Changed the copy order. First we copy over the template files, then copy the app files over top. That way app's branding/assets "win".
https://jira.appcelerator.org/browse/TIMOB-19112

Fix TIMOB-19112 Windows: Splash Screen not showing

---

Source/Ti/include/TitaniumWindows/TiModule.hpp
Source/Ti/src/TiModule.cpp
Source/TitaniumKit/include/Titanium/App.hpp
Source/TitaniumKit/src/App.cpp

This is a very ugly hack. Basically we throw the sdk version from the CLI build into the _app_info_.json file along with some of the other tiapp values. Then When we load those up in the Ti.App module, we load the sdkVersion value too. And when the user asks for Ti.version, we basically just secretly do Ti.App._sdkVersion to grab that value.
https://jira.appcelerator.org/browse/TIMOB-19144

Fix TIMOB-19144 Windows: Ti.version is blank

---

Source/UI/src/Windows/AppBarToggleButton.cpp

https://jira.appcelerator.org/browse/TIMOB-19114
```javascript
backgroundColor: 'black'
});
var likeButton = Ti.UI.Windows.createAppBarToggleButton({
icon: Ti.UI.Windows.SystemIcon.LIKEDISLIKE
});
likeButton.addEventListener('click', function (e) {
console.log(JSON.stringify(e, null, 2));
});
win.add(Ti.UI.Windows.createCommandBar({
items: [likeButton]
}));
win.open();
```

Fix TIMOB-19114 Ti.UI.Windows.AppBarToggleButton:click does not include checked like documented

---

Source/Network/src/HTTPClient.cpp
Source/Ti/src/Platform.cpp
Source/TitaniumKit/src/ApplicationBuilder.cpp

- Use JS to build the default userAgent string when we do our other global setup
- Set the User-Agent header on HTTPClient.open(), handle the header specially (like we do for Content-Type)
- Set the X-Titanium-Id header when we prepare a request with the Ti.App.guid.
- Implement Ti.Platform.version. We had hard-coded "0.0" for os version, but I found a hacky way around it using PnP device sniffing. We basically take the first "Microsoft" provider listing and use it's version. Typically that is right and is something along the lines of "6.3.9651.0" (for windows phone), which in Windows version world means Windows 8.1. Desktop should return "6.3.9600" or equivalent.
https://jira.appcelerator.org/browse/TIMOB-19129

Fix TIMOB-19129 Windows: HTTPClient does not send User-Agent

---

Tools/Scripts/build/build.js

This way we can just build the architectures that we care about when
testing. The others can be skipped easily from the command line.
node build.js --only WindowsPhone-x86

Support `build.js --only WindowsPhone-x86`

---

templates/module/default/template/windows/CMakeLists.txt.ejs

- Remove unnecessary ```JavascriptCore``` dependency from module generation
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19180)

[TIMOB-19180] Remove JavascriptCore dependancy from modules

---

Source/TitaniumKit/src/UI/Switch.cpp
Source/UI/src/Switch.cpp

Fix for [TIMOB-19132](https://jira.appcelerator.org/browse/TIMOB-19132)
```javascript
win.add(Ti.UI.createSwitch({
top: 20,
left: 20
}));
win.open();
```

[TIMOB-19132] Ti.UI.Switch cannot be positioned (absolute)

---

cli/commands/_build/validate.js
cli/hooks/ws-package.js

Took the regex from Microsoft's specifications for publisher names.
Also, move the trimming so that it will apply to all passed in publisher
names.
It should be tested to work with various deploy types, using a publisher name that contains character's Microsoft doesn't like, such as commas and spaces.
```bash
ti build -p windows -G 00000000-0000-1000-8000-000000000000 -C 8-1-1
ti build -p windows -G 00000000-0000-1000-8000-000000000000 --target dist-winstore
```
https://jira.appcelerator.org/browse/TIMOB-19104

[TIMOB-19104] Remove Invalid Chars from Publisher Name

---

Source/UI/include/TitaniumWindows/UI/AlertDialog.hpp
Source/UI/src/AlertDialog.cpp

- Queue alert dialogs so only one is displayed at a time
```Javascript
var n = 0;
function createAlert() {
var alertDialog = Ti.UI.createAlertDialog({
message: 'alert #' + n++,
buttonNames: ['create two alerts', 'close']
});
alertDialog.addEventListener('click', function (e) {
if (e.index === 0) {
createAlert();
createAlert();
}
});
alertDialog.show();
}
createAlert();
```
```Javascript
alert('alert #1');
alert('alert #2');
alert('alert #3');
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19137)

[TIMOB-19137] Queue alert dialogs - READY

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.view.test.js
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

We had overridden hide() and show() for Windows, but really could have kept them as set_visible(true/false) calls up in TitaniumKit. We never overrode set/get_visible though, so assigning to the visible property wasn't honored.
Fixed that and added a unit test for it.

Fix so visible property changes are actually done

---

Source/Sensors/src/Geolocation.cpp

- Removed ```altitudeAccuracy``` from ```getCurrentPosition()``` as it caused a memory access error
- Fixed returned JSON object from ```reverseGeocoder()```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19217)

[TIMOB-19217] Fix reverseGeocoder() and getCurrentPosition() callback payloads

---

Tools/Scripts/setup.js

- Update ```JavaScriptCore``` URL to newer build containing fix for ```TIMOB-18770```
- ~~Set correct permissions for [JavaScriptCore-Windows-1433795599.zip](http://timobile.appcelerator.com.s3.amazonaws.com/jscore/JavaScriptCore-Windows-1433795599.zip) on the Amazon-S3 server~~ ✓
```Javascript
// this should display a white window with no exceptions
var φ = 'hello world';
Ti.UI.createWindow({
backgroundColor: "white"
}).open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18770)

[TIMOB-18770] Update JavaScriptCore URL

---

Source/UI/include/TitaniumWindows/UI/AlertDialog.hpp
Source/UI/src/AlertDialog.cpp

Fix for [TIMOB-19219](https://jira.appcelerator.org/browse/TIMOB-19219)
Test case 1:
1. Show dialog once by clicking "Push" button
2. Close the dialog
3. Show dialog once again by clicking " "Push" button
4. AlertDialog should be shown again
```javascript
var btn = Ti.UI.createButton({title:'Push'});
btn.addEventListener('click', function (e) {
var dialog = Ti.UI.createAlertDialog({
message: 'Okay',
title: 'Alert Dialog Test'
});
dialog.show();
});
win.add(btn);
win.open();
```
Test case 2: This should not cause runtime exception ([TIMOB-19137](https://jira.appcelerator.org/browse/TIMOB-19137))
```javascript
var n = 0;
function createAlert() {
var alertDialog = Ti.UI.createAlertDialog({
message: 'alert #' + n++,
buttonNames: ['create two alerts', 'close'] …
```

Fix: AlertDialog is not shown more than twice

---

Source/Global/src/GlobalObject.cpp
Source/TitaniumKit/src/Database/DB.cpp

Fix for [TIMOB-19216](https://jira.appcelerator.org/browse/TIMOB-19216)
`std::unordered_map::emplace` should not be used to replace elements because it works only when key is unique. Also added assertion to make sure if it's unique when you use `emplace`.

FIx; Wrong use of std::unordered_map::emplace

---

Examples/RSSReader/src/Assets/alloy/controllers/master.js
Source/UI/src/ListView.cpp

Part of [TIMOB-19056](https://jira.appcelerator.org/browse/TIMOB-19056)
- Add support for `itemId` and `bindId` properties for `itemclick` event on ListView.
- Implement "Refresh" button for RSS reader
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });
var listView = Ti.UI.createListView();
var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits' });
{ properties: { title: 'Apple', itemId:'apple' } },
{ properties: { title: 'Banana', itemId:'banana' } },
];
var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables' });
var vegDataSet = [
{ properties: { title: 'Carrots', itemId:'carrots' } },
{ properties: { title: 'Potatoes', itemId:'potatos' …
```

Add "itemId" and "bindId" for ListView itemclick event

---

Source/TitaniumKit/src/GlobalObject.cpp

Fix for [TIMOB-19212](https://jira.appcelerator.org/browse/TIMOB-19212).
- Fix: setTimeout delay param should be optional
- Fix wrong line break and remove obsolete comments
```javascript
Ti.API.info('yay!');
});
```

Fix: setTimeout delay param should be optional

---

Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp

Follow up from discussion at #379.
Stop throwing JS error at assertion but just log onto console. The error message contains file name and line number integrated to help debug.
```
TitaniumKit 000000072 Fri Jul 17 16:04:20 2015 WARN: C:\titanium_mobile_windows\Source\TitaniumKit\src\GlobalObject.cpp:532: Expected Number.
```

Stop throwing JS error at assertion but just log onto console

---

Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/Label.cpp

Fix for [TIMOB-19048](https://jira.appcelerator.org/browse/TIMOB-19048).
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'white' });
var lbl = Ti.UI.createLabel({
text: '*** Resources Dir: Test presence of file that exists => blahTest presence of file that does not exist => bleh*** appData Dir:Test presence of file that exists => meh Test presence of file that does not exist => merh',
color: 'black'
});
win.add(lbl);
win.open();
```

Fix: Word wrap on labels does not work if width and height are not set

---

Source/UI/include/TitaniumWindows/UI/AlertDialog.hpp
Source/UI/src/AlertDialog.cpp

Fix for [TIMOB-19225](https://jira.appcelerator.org/browse/TIMOB-19225)
Following code should print "Callback from Push 1" when you dismiss alert dialog from Push1 button, and should print "Callback from Push 2" when you dismiss alert dialog from Push2 button.
```javascript
var win = Ti.UI.createWindow({layout:'vertical'});
var btn1 = Ti.UI.createButton({ title: 'Push 1' });
btn1.addEventListener('click', function (e) {
var dialog = Ti.UI.createAlertDialog({
message: 'Okay 1',
title: 'Alert Dialog Test 1'
});
dialog.addEventListener('click', function (e) {
Ti.API.info('Callback from Push 1');
});
dialog.show();
});
win.add(btn1);
var btn2 = Ti.UI.createButton({ title: 'Push 2' });
btn2.addEventListener('click', function (e) {
var dialog = Ti.UI.createAlertDialog({
message: 'Okay 2', …
```

Fix: wrong callback for AlertDialog

---

Source/LayoutEngine/src/ParseProperty.cpp

- Fixed ```dp``` calculation
- ```1dp is equal to 1 physical pixel on a 160 DPI screen```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19224)

[TIMOB-19224] Fix 'dp' calculation

---

Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/include/TitaniumWindows/UI/TabGroup.hpp
Source/UI/src/Tab.cpp
Source/UI/src/TabGroup.cpp

Implement TabGroup for Windows Store app. [TIMOB-19187](https://jira.appcelerator.org/browse/TIMOB-19187).
TabGroup for Windows Store now uses [ListView](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.listview.aspx) for the navigation because there's no [Pivot](https://msdn.microsoft.com/en-us/library/windows/apps/ff941097%28v=vs.105%29.aspx) for Windows Store app.  [Hub](https://msdn.microsoft.com/en-us/library/windows/apps/dn958438.aspx) is not suitable because it is meant to provide previews/summaries. On the coming Windows 10 we might want to use [SplitView](http://igrali.com/2015/04/12/getting-started-with-splitview-control-in-universal-apps/) instead because it is conceptually well suitable for TabGroup.

Implement TabGroup for Windows Store app

---

Source/TitaniumKit/examples/CMakeLists.txt
Source/TitaniumKit/examples/NativeHTTPClientExample.cpp
Source/TitaniumKit/examples/NativeHTTPClientExample.hpp
Source/TitaniumKit/src/Network/HTTPClient.cpp
Source/TitaniumKit/test/DatabaseTests.cpp
Source/TitaniumKit/test/FilesystemTests.cpp
Source/TitaniumKit/test/MediaTests.cpp
Source/TitaniumKit/test/ModuleTests.cpp
Source/TitaniumKit/test/NativeAccelerometerTests.cpp
Source/TitaniumKit/test/NativeBlobTests.cpp
Source/TitaniumKit/test/NativeButtonTests.cpp
Source/TitaniumKit/test/NativeFileTests.cpp
Source/TitaniumKit/test/NativeGestureTests.cpp
Source/TitaniumKit/test/NativePlatformTests.cpp
Source/TitaniumKit/test/NativeTiTests.cpp
Source/TitaniumKit/test/NativeWebViewTests.cpp
Source/TitaniumKit/test/NativeWindowTests.cpp
Source/TitaniumKit/test/NetworkTests.cpp
Source/TitaniumKit/test/TiAppTests.cpp
Source/TitaniumKit/test/UITests.cpp

Fix for [TIMOB-19181](https://jira.appcelerator.org/browse/TIMOB-19181) and [TIMOB-19183](https://jira.appcelerator.org/browse/TIMOB-19183).
- Fix: JSON.stringify fails for Ti.Network.HTTPClient
- Add unit test for JSON.stringify
```javascript
Ti.API.info(JSON.stringify(Ti.Network.createHTTPClient(), null, 2));
win.open();
```

Fix: HTTPClient.responseXML throws exception

---

Examples/Geocoder/src/Assets/ui/ApplicationWindow.js

- Revert Windows specific scaling for ```Geocoder``` example since TIMOB-19224 fixed this issue
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19055)

[TIMOB-19055] Revert Geocoder Windows specific sizes due to TIMOB-19224

---

cli/commands/_build/compile.js

- Fix ```error``` output being displayed as a ```warning```
[TIMOB-19148](https://jira.appcelerator.org/browse/TIMOB-19148)

[TIMOB-19148] Fix MSBuild error output

---

cli/hooks/wp-run.js

I would like to revert #390, I had experienced following error during `ti build` for development deployment. I shouldn't have merged it.
```
[ERROR] Failed to start emulator "8-1-1"
[ERROR] Connection failed because of invalid command-line arguments.
```

Revert "Fix TIMOB-19153.." #390

---

cli/hooks/wp-run.js

https://jira.appcelerator.org/browse/TIMOB-19153
I think the error Kota ran into before was related to issues seen on the build machine - where suddenly shorthand options are not working for titanium CLI (i.e. -C and -T versus --device-id and --target), see https://jira.appcelerator.org/browse/TIMOB-19281
Reverts appcelerator/titanium_mobile_windows#393

Re-introduce Fix for TIMOB-19153

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/ApplicationBuilder.hpp
Source/TitaniumKit/include/Titanium/UI/Clipboard.hpp
Source/TitaniumKit/src/ApplicationBuilder.cpp
Source/TitaniumKit/src/UI/Clipboard.cpp
Source/UI/CMakeLists.txt
Source/UI/include/TitaniumWindows/UI.hpp
Source/UI/include/TitaniumWindows/UI/Clipboard.hpp
Source/UI/src/Clipboard.cpp

- Implement ```Titanium.UI.Clipboard```
- ```getData()``` and ```setData()``` are implemented similar to our Android implementation
- This is for ```WindowsStore``` applications __ONLY__.
```Javascript
Ti.UI.Clipboard.clearText();
Ti.UI.Clipboard.setText('Hello World!');
if (Ti.UI.Clipboard.hasText()) {
Ti.API.info('getText() : ' + Ti.UI.Clipboard.getText());
}
var obj = { test: 'Hello World!' };
Ti.UI.Clipboard.setData('text', obj);
if (Ti.UI.Clipboard.hasData('text')) {
Ti.API.info('getData() : ' + JSON.stringify(Ti.UI.Clipboard.getData('text')));
}
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18757)

[TIMOB-18757] Implement Titanium.UI.Clipboard

---

Source/UI/include/TitaniumWindows/UI/TabGroup.hpp
Source/UI/src/TabGroup.cpp

Fix for [TIMOB-19251](https://jira.appcelerator.org/browse/TIMOB-19251)
```javascript
var win1 = Ti.UI.createWindow({
title: 'Blue'
});
win1.add(Ti.UI.createLabel({ text: 'I am a blue window.' }));
var win2 = Ti.UI.createWindow({
title: 'Red'
});
win2.add(Ti.UI.createLabel({ text: 'I am a red window.' }));
var tab1 = Ti.UI.createTab({
window: win1,
title: 'Blue'
}),
tab2 = Ti.UI.createTab({
window: win2,
title: 'Red'
}),
tabGroup = Ti.UI.createTabGroup({
tabs: [tab1, tab2]
});
//tabGroup.addTab(tab1);
//tabGroup.addTab(tab2);
//tabGroup.tabs = [tab1, tab2];
//tabGroup.setTabs([tab1, tab2]);
tabGroup.open();
```

Fix: Tabs added using the TabGroup property are not rendered

---

Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/src/GlobalObject.cpp

Fix for [TIMOB-19305](https://jira.appcelerator.org/browse/TIMOB-19305) and [TIMOB-19084](https://jira.appcelerator.org/browse/TIMOB-19084).
When requiring files, only `app.js` should be treated special. It should expose every variables to child.
`app.js`
```javascript
var Alloy = { Globals:{} };
Alloy.Globals.winTop = 6;
var m = require('testmodule')
m.test();
```
`testmodule.js`
```javascript
exports.test = function() {
Ti.API.info("Test Module");
Ti.API.info("Module Wintop " + Alloy.Globals.winTop);
};
```

Fix: Alloy.Globals not accessible from a commonjs module

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Source/TitaniumKit/src/Network/HTTPClient.cpp

Fix for [TIMOB-19347](https://jira.appcelerator.org/browse/TIMOB-19347)
```javascript
win.open();
var xhr = Ti.Network.createHTTPClient();
xhr.setTimeout(3e4);
xhr.onload = function (e) {
Ti.API.info('onload: ' + xhr.responseText);
win.backgroundColor = 'green';
};
xhr.onerror = function (e) {
Ti.API.error('onerror: '+e.error);
};
xhr.open("POST", "http://www.ambientreality.com/ingot/post_test.php");
xhr.send({
message: "check me out",
numericid: 1001 
});
```

Fix: HTTPClient.send fails when data has non-string/Blob values

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-19294](https://jira.appcelerator.org/browse/TIMOB-19294).
```javascript
var win = Ti.UI.createWindow({layout: 'vertical'});
var tf1 = Ti.UI.createTextField({
left: 10,
right: 10,
hintText: 'blah blah blah'
});
win.add(tf1);
var tf2 = Ti.UI.createTextField({
width: 100,
hintText: 'yada yada yada'
});
win.add(tf2);
win.open();
```

Fix: Setting both left and right properties causes wrong layout

---

Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Implement zIndex on View subclasses: [[TIMOB-19349](https://jira.appcelerator.org/browse/TIMOB-19349)]
```javascript
var win = Ti.UI.createWindow({backgroundColor:'black'});
top: 0, left: 0,
zIndex: 1
});
top: 30, left: 30,
zIndex: 2
});
top: 60, left: 60,
zIndex: 3
});
win.add(view3);
var commandBar = Ti.UI.createView({
width: Ti.UI.FILL, height: '10%',
bottom: 0, left: 0,
layout:'horizontal'
});
var view1Top = Ti.UI.createButton({ title: '3,2,1',   width: '30%'});
var view2Top = …
```

Implement zIndex on View subclasses

---

Source/LayoutEngine/include/LayoutEngine/LayoutEngine.hpp
Source/LayoutEngine/src/ParseProperty.cpp
Source/LayoutEngine/test/PropertyParserTest.cpp
Source/TitaniumKit/include/Titanium/App.hpp
Source/TitaniumKit/src/App.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

https://jira.appcelerator.org/browse/TIMOB-19350
Fixed a typo in method name in LayoutEngine. Added comments and fixed calculations for certain units.
Added a Titanium::AppModule::defaultUnit() method that pulls the units from Ti.App.Properties.getString("ti.ui.defaultunit"). If the property is empty, is "system" or is not a recognized unit, we default to "px".
We pass in the default unit to the LayoutEngine along with the ppi/dpi whenever we set a layout property.
Technically this is a potentially useless perf hit since we only really need the default units if there's no valid units specified for the value.

Fix TIMOB-19350 tiapp property ti.ui.defaultunit ignored

---

Source/TitaniumKit/src/Network/HTTPClient.cpp

Fix for [TIMOB-19416](https://jira.appcelerator.org/browse/TIMOB-19416). Setting null to `securityManager` should not cause runtime error.
```javascript
Ti.Network.createHTTPClient({
securityManager: null
});
win.open();
```

Fix: runtime error when securityManager is null

---

Tools/Scripts/setup.js

JavaScriptCore_HOME should have set to $HOME/JavaScriptCore

Fix JavaScriptCore_HOME for Windows Setup

---

README.md

No need to specify `--wp-publisher-guid` for now.

Update README for CLI options

---

Source/TitaniumKit/include/Titanium/UI/ProgressBar.hpp
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/src/UI/ProgressBar.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/UI/include/TitaniumWindows/UI/View.hpp
Source/UI/src/View.cpp

https://jira.appcelerator.org/browse/TIMOB-19394
Not sure if we want to merge this immediately. Need more direction on whether we truly want to expand the API for other platforms like this and update our docs; or keep as-is and drop support in iOS; or further expand API to also support a single or array of objects holding a "view" and "position" key like iOS supports (but is not mentioned in the ticket or docs).

TIMOB-19394 Ti.UI.View.add should support array of views

---

cli/lib/TODO.md
cli/lib/stub.js
templates/build/Native/src/WindowsNativeModuleLoader.cpp.ejs

https://jira.appcelerator.org/browse/TIMOB-19414
Basically we whittle down the set of headers to include in Plaftorm.Object.cpp and WindowsNativeModuleLoader based on the knowledge that we have about the inheritance tree and that a given type will include it's parent header in it's own.
The effects don't seem to be all to great. In a first-time build from scratch I saw a reduction in the compile/link time from about 5:35 to 5:29. We could do the same thing in the individual proxy/wrapper cpp files too, but generally speaking the list of includes there is much smaller, and it's slightly more work to filter there right now. Given the small reduction in time for the two files with the largest set of includes, it probably isn't worth it right now.

Improve compile time of WindowsNativeModuleLoader for Native API access

---

Source/UI/src/View.cpp

Fix for [TIMOB-19502](https://jira.appcelerator.org/browse/TIMOB-19502) originated from [TIMOB-19401](https://jira.appcelerator.org/browse/TIMOB-19401)
- Fix: touchstart and touchend not fired
- Fix: longpress fired twice

Fix: wrong behavior for touch events

---

Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/UI/include/TitaniumWindows/UI/View.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/View.cpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Refactoring #419, which basically overrides `View.add` and `Window.add` only. This PR moves these native hook logic onto `WindowsViewLayoutDelegate` so that every View subclass supports mixing Windows UI components. Moving to layout delegate is also good for avoiding duplicate code across View subclasses.
- Refactor & Allow mixing Windows UI component for View subclass
- Move View::registerNativeUIWrapHook to layout delegate
```javascript
var win,
TextBlock = require('Windows.UI.Xaml.Controls.TextBlock'),
text = new TextBlock();
text.Text = "Hello, world!";
text.FontSize = 60;
win = Ti.UI.createWindow({});
win.add(text);
win.open();
```
```javascript
var Window = require('Windows.UI.Xaml.Window'),
Canvas = require('Windows.UI.Xaml.Controls.Canvas'),
window = Window.Current,
canvas = new …
```

Refactor & Allow mixing Windows UI component for View subclass

---

Source/TitaniumKit/src/analytics.js

- Fix invalid ```_t.receivedResponse``` statement causing an error when an application is being debugged whilst the device is offline.
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19572)

[TIMOB-19572] Fix invalid receivedResponse in analytics.js

---

cli/lib/stub.js
cli/lib/templates/js_to_native.cpp
cli/lib/templates/js_to_native_primitive.cpp
cli/lib/templates/native_primitive_to_js.cpp
cli/lib/templates/native_to_js.cpp

Handle all primitives found in metabase wherever we need to filter them out/convert them.
https://jira.appcelerator.org/browse/TIMOB-19517
Basically we need to avoid including primitives in the dependency tree for generating wrappers, and we  need to make sure we can convert primitives back and forth from JS.

Fix TIMOB-19517 Windows: Native stub generation fails on 'float32' when requiring StackPanel

---

cli/commands/_build/copy.js

- Generate missing icons ```Square44x44Logo.png``` ```Square71x71Logo.png``` and ```Square150x150Logo.png```
NOTE : ```Package.appxmanifest``` needs to be updated to make use of the missing icons.
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19487)

[TIMOB-19487] Generate missing app icons based on DefaultIcon.png

---

cli/commands/_build/copy.js

[TIMOB-19644](https://jira.appcelerator.org/browse/TIMOB-19644) Related: [TIMOB-19643](https://jira.appcelerator.org/browse/TIMOB-19643)
When there's no DefaultIcon.png, CLI shows critical error on build but it does not stop build process.

[TIMOB-19644] Fix: CLI build error is ignored

---

Tools/Scripts/generate_project.js
cli/commands/_build/config.js
cli/commands/_build/config/_index.js
cli/commands/_build/config/vstarget.js
cli/commands/_build/config/wpSDK.js
cli/commands/_build/initialize.js
cli/commands/_build/logInfo.js
cli/commands/_build/run.js

[TIMOB-19576](https://jira.appcelerator.org/browse/TIMOB-19576)
- Add `--vs-target` option to specify Visual Studio version
- 12.0  ... Visual Studio 2013
- 14.0 ... Visual Studio 2015
- Add Windows 10 sdk support  (`--wp-sdk 10`)
```
ti build --platform windows --vs-target 12.0 --target wp-emulator --device-id 8-1-1 --win-publisher-id 13AXB724-65X2-4X30-8994-C79399EDXX00 --wp-sdk 8.1
```
Note that although CLI accepts targeting to Windows 10 (`--wp-sdk 10`), it's failing for now because cmake doesn't support that yet. It's implemented for future release.

Add VS 2015 and Windows 10 SDK option for CLI

---

cli/commands/_build/copy.js

- Skip the generation of existing icons
- Place a required icon into ```<project>/app/assets/windows/```, for example ```Square150x150Logo.png```
- This icon should not be overwritten by the ```DefaultIcon.png``` after the project has been generated using ```appc run```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19650)

[TIMOB-19650] Skip generation of existing icons

---

cli/commands/_build/config/winPublisherId.js

- Set a default value for the ```Windows Publisher ID``` prompt
- Do not set a default prompt value if ```--deploy-type``` is ```production```
```
appc run -p windows
```
```
appc run -p windows --deploy-type production
What is your Windows Publisher ID?:
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18531)

[TIMOB-18531] Set default value for Windows Publisher ID prompt

---

cli/commands/_build/config/wpSDK.js
cli/commands/_build/generate.js
templates/build/CMakeLists.txt.ejs
templates/build/Package.store.appxmanifest.in.ejs

Fix for [TIMOB-19689](https://jira.appcelerator.org/browse/TIMOB-19689).
- Ignore scaled image assets with `scale-xx` when building for Store
- Remove invalid capability entry
Make sure to update [windowslib](https://github.com/appcelerator/windowslib/pull/24) too.

Fix: building Windows 10 Store app

---

cli/commands/_build/encrypt.js

- Validate ```this.jdkInfo``` exists to prevent hanging during encryption
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19745)

[TIMOB-19745] Validate jdkInfo during encryption

---

cli/commands/_build/compile.js
cli/commands/_buildModule.js

Fix for [TIMOB-19646](https://jira.appcelerator.org/browse/TIMOB-19646).
`MSBuild` process remains after `ti build`. For some reason `/m` (`/maxcpucount[:number]`) option didn't work well, it lefts zombie process even after build is finished.

Fix: MSBuild process remains after "ti build"

---

Source/TitaniumKit/include/sqlite3.h
Source/TitaniumKit/src/Database/ResultSet.cpp

- Update ```fieldName()``` to always return ```std::string```, setting ```std::string``` to ```nullptr``` is not supported
- Removed C-style cast from ```sqlite3_column_count```
- Update SQLite to version ```3.9.1```
```Javascript
var booksDB = Ti.Database.open('booksDB');
booksDB.execute('CREATE TABLE IF NOT EXISTS books(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, author TEXT)');
booksDB.execute('REPLACE INTO books (title,author) VALUES (?,?)', ['Great Expectations', 'Charles Dickens']);
var result = booksDB.execute('SELECT * FROM books');
Ti.API.info('fieldCount: ' + result.fieldCount);
Ti.API.info('=== RESULT ===');
for (var i = 0, j = result.fieldCount; i < j; i++) {
Ti.API.info(result.fieldName(i));
}
Ti.API.info('==============');
result.close();
booksDB.close();
```
``` …
```

[TIMOB-19820] Fix Ti.Database.ResultSet.fieldName()

---

cli/commands/_build/copy.js

Fix for [TIMOB-19698](https://jira.appcelerator.org/browse/TIMOB-19698)

Fix :CLI doesn't exit on parse error

---

cli/commands/_build/config/deviceID.js
cli/commands/_build/utils.js

Fix for [TIMOB-19811](https://jira.appcelerator.org/browse/TIMOB-19811).
Emulators that are not supported should not be shown as an option to build to.
```
﻿﻿PS > ti build --platform windows --vs-target 12.0 --target wp-emulator --win-publisher-id 00AFB000-00F0-0F00-0000-C00000EDBD00 --wp-sdk 8.1
Titanium Command-Line Interface, CLI version 5.0.1, Titanium SDK version 5.2.0.v20151102141226
Copyright (c) 2012-2015, Appcelerator, Inc.  All Rights Reserved.
Please report bugs to http://jira.appcelerator.org/
Which emulator do you want to install your app on?
1)  Emulator 8.1 WVGA 4 inch 512MB  (udid: 8-1-6)
2)  Emulator 8.1 WVGA 4 inch        (udid: 8-1-7)
3)  Emulator 8.1 WXGA 4.5 inch      (udid: 8-1-8)
4)  Emulator 8.1 720P 4.7 inch      (udid: 8-1-9)
5)  Emulator 8.1 1080P 5.5 inch …
```

Fix: Windows 10 mobile emulator should not show up in selection

---

cli/commands/_build/copy.js

Fix for [TIMOB-19487](https://jira.appcelerator.org/browse/TIMOB-19487)
- Fix: Generate app icons for Windows Store
- Fix: Use app icon when it is under project directory

Fix: Generate app icons for Windows Store

---

cli/lib/info.js

- Create ```cli/lib/info.js``` for ```titanium``` to use
- This enables ```appc ti info -t windows``` and ```appc ti info -t windows -o json```
- This requires [titanium_mobile/pull/7409](https://github.com/appcelerator/titanium_mobile/pull/7409)
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19045)

[TIMOB-19085] Move CLI info detection and rendering into windows folder

---

cli/commands/_build/generate.js

Fix for [TIMOB-19138](https://jira.appcelerator.org/browse/TIMOB-19138)
Set `DefaultLanguage` to `en` to suppress compiler warning.
Note: Would be nice to have platform-specific default language property, something like `ti.windows.defaultLanguage` FYI: [TIMOB-16356](https://jira.appcelerator.org/browse/TIMOB-16356)

Fix: DefaultLanguage property should be set (to "en") in manifest

---

Examples/NMocha/src/Assets/ti.ui.textfield.test.js
Source/UI/include/TitaniumWindows/UI/TextField.hpp
Source/UI/src/TextField.cpp

Fix for [TIMOB-19894](https://jira.appcelerator.org/browse/TIMOB-19894).
Test Case: Following script should show password-masked TextField.
```javascript
});
var field = Ti.UI.createTextField({ width:200, passwordMask:true, value:'pa33w0rd'});
win.add(field);
win.open();
```

Fix: TextField.passwordMask doesn't work

---

Source/UI/src/Window.cpp

- ```5_1_X``` cherry-pick of [#473](https://github.com/appcelerator/titanium_mobile_windows/pull/473)

[5_1_X][TIMOB-19394] Allow array input for Ti.UI.Window.add()

---

Examples/NMocha/src/Assets/ti.app.properties.test.js
Source/Ti/include/TitaniumWindows/App/Properties.hpp
Source/Ti/src/Properties.cpp
Source/TitaniumKit/src/App/Properties.cpp

- Implement the ```change``` event to be fired when properties are set
```Javascript
Ti.App.Properties.addEventListener('change', function (properties) {
Ti.API.info(JSON.stringify(properties));
});
Ti.App.Properties.setBool('BOOL', true);
Ti.App.Properties.setDouble('DOUBLE', 1.23);
Ti.App.Properties.setInt('INT', 1);
Ti.App.Properties.setString('STRING', 'test');
Ti.App.Properties.setList('LIST', [1, 2, 3]);
Ti.App.Properties.setObject('OBJECT', {test: 'test'});
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19925)

[TIMOB-19925] Implement Ti.App.Properties 'change' event

---

Source/TitaniumKit/include/Titanium/UI/TextArea.hpp
Source/TitaniumKit/src/UI/TextArea.cpp
Source/UI/include/TitaniumWindows/UI/Button.hpp
Source/UI/include/TitaniumWindows/UI/TextArea.hpp
Source/UI/include/TitaniumWindows/UI/TextField.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Button.cpp
Source/UI/src/TextArea.cpp
Source/UI/src/TextField.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp
apidoc/whitelist.txt

Fix for [TIMOB-19953](https://jira.appcelerator.org/browse/TIMOB-19953), [TIMOB-19955](https://jira.appcelerator.org/browse/TIMOB-19955), [TIMOB-19963](https://jira.appcelerator.org/browse/TIMOB-19963) and [TIMOB-20078](https://jira.appcelerator.org/browse/TIMOB-20078)
Some events are not available depending on Windows xaml components. For instance, `touchstart/end` event doesn't work for Button and TextField/Area. Note that `pinch`, `swipe` and `twofingertap` are not implemented yet, because Xaml `GestureRecognizer` doesn't work for most of components unfortunately. In that sense we might want to invent our own gesture recognizer to introduce `swipe/pinch` and touch events with multiple fingers.
| event        | supported  |
| ------------- |:-------------:|
| blur      | :x: |
| click …

Implement missing events for Label, Button, TextField and TextArea

---

Source/Media/src/Media/AudioPlayer.cpp

Fix compiler warning on Windows 10.
Although it's not quite clear which values are deprecated, VS 2015 compiler produces warning on use of `AudioCategory::BackgroundCapableMedia`. 
The document from MS says:
[MediaElement class](https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.mediaelement.aspx)
> To let audio continue to play when your app is in the background, set the AudioCategory property to BackgroundCapableMedia. This also requires declaring the "Audio" background task capability in the app manifest. **These values are deprecated in Windows 10**.
But what does "*Those values*" exactly mean?
In their API document, MS says it's *supported* in Windows 10. See [AudioCategory enumeration](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.media.a …

Disable AudioCategory on Windows 10

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.ui.button.test.js
Source/TitaniumKit/include/Titanium/UI/Button.hpp
Source/TitaniumKit/src/UI/Button.cpp
Source/UI/include/TitaniumWindows/UI/Button.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Button.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-19952](https://jira.appcelerator.org/browse/TIMOB-19952)
`Ti.UI.Button.image` should have accepted string as well as `Blob`.
```javascript
var window = Ti.UI.createWindow({
});
width: '100%',
height: 150
});
var button = Ti.UI.createButton({ title: 'Bar bar bar' });
//button.image = "http://www.appcelerator.com/wp-content/themes/appc-rwd/assets/media/images/logo.png";
button.image = Ti.Filesystem.getFile('Logo.png').read();
view.add(button);
window.add(view);
window.open();
```

Implement Button.image property

---

Examples/NMocha/src/Assets/ti.blob.test.js
Source/Titanium/include/TitaniumWindows/Blob.hpp
Source/Titanium/src/Blob.cpp

- Implemented ```Titanium.Blob.width``` and ```Titanium.Blob.height``` functionality
- Updated NMocha ```ti.blob.test.js``` to test ```width``` and ```height``` of ```Logo.png```
```Javascript
var blob = Ti.Filesystem.getFile('Logo.png').read();
Ti.API.info('Blob->width: ' + blob.width);
Ti.API.info('Blob->height: ' + blob.height);
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19927)

[TIMOB-19927] Implement Titanium.Blob width and height

---

Source/UI/src/TextField.cpp

- Cherry-pick of [7cbf311](https://github.com/appcelerator/titanium_mobile_windows/commit/7cbf31170706675d43a9d33cc0fd3feb086605ae)

[5_1_X] Fix MSBuild warnings

---

Source/Media/CMakeLists.txt
Source/Media/include/TitaniumWindows/Media/AudioBackground.hpp
Source/Media/include/TitaniumWindows/Media/AudioPlayer.hpp
Source/Media/src/Media/AudioBackground.cpp
Source/Media/src/Media/AudioPlayer.cpp
cli/commands/_build/generate.js
templates/build/Package.phone.appxmanifest.in.ejs
templates/build/Package.store.appxmanifest.in.ejs
templates/build/Package.win10.appxmanifest.in.ejs

- Implemented ```Titanium.Media.AudioPlayer.allowBackground``` functionality
- Added ```AudioBackground``` background task to ```TitaniumWindows_Media```
- Fixed ```CurrentStateChanged``` switch statement
- Added ```Extentions``` support into ```tiapp.xml``` to enable the audio background task
- Both Windows Phone and Windows Store apps require an ```Audio``` _BackgroundTask_ extension in the ```Package.appxmanifest```
- Background audio plays from a separate media player [BackgroundMediaPlayer](https://msdn.microsoft.com/en-us/library/windows/apps/windows.media.playback.backgroundmediaplayer.current.aspx) which means we need to switch between media players when setting the ```allowBackground``` property
```XML
<windows>
<manifest>
<Extentions>
<Extension …
```

[TIMOB-20035] Implement Ti.Media.AudioPlayer.allowBackground

---

Source/TitaniumKit/src/UI/ImageView.cpp
Source/UI/src/ImageView.cpp
apidoc/whitelist.txt

Fix for [TIMOB-19937](https://jira.appcelerator.org/browse/TIMOB-19937)
- Implement `start`, `pause` and `stop` event for ImageView
```javascript
var win = Ti.UI.createWindow({background:'black'});
var animationFrames = [
'http://api.randomuser.me/portraits/women/0.jpg',
'http://api.randomuser.me/portraits/women/1.jpg',
'http://api.randomuser.me/portraits/women/2.jpg',
'http://api.randomuser.me/portraits/women/3.jpg'
];
var view = Ti.UI.createImageView({
images: animationFrames,
duration: 2000,
repeatCount: 2
});
view.addEventListener('start', function (e) {
Ti.API.info('start animation');
});
view.addEventListener('stop', function (e) {
Ti.API.info('stop animation');
});
win.add(view);
var button = Ti.UI.createButton({ title: 'start/stop', top: 0, left: 0 }); …
```

Implement ImageView animation events

---

Examples/NMocha/src/Assets/ti.buffer.test.js
Examples/NMocha/src/Assets/ti.codec.test.js
Examples/NMocha/src/Assets/ti.contacts.test.js
Examples/NMocha/src/Assets/ti.ui.button.test.js
Source/Ti/src/Contacts/Group.cpp
Tools/Scripts/build/package.json
Tools/Scripts/build/test.js
Tools/Scripts/win10.bat
Tools/Scripts/win81.bat
cli/commands/_build/config/target.js
cli/commands/_build/config/wpSDK.js
cli/commands/_build/config/wsCert.js
cli/hooks/cert.js

CMake includes a default temporary PFX file to use. Ultimately both CMake and VS do this for the user transparently - when deploying to emulator or device, if the app requires a cert, it uses a temporary PFX with no password.
This PR is to do the same. If we're on 10.0 and not doing dist-winstore or dist-phonestore, we use the temp key from cmake transparently. If we're on 8.1 and not doing dist-winstore, we do the same.
This also improves our code so that if you specify a PFX file that doesn't need a password, we shouldn't require you to pass you in.
So in summary:
- On Windows 8.1 it needs PFX for store apps, but not for phone apps. We should just magically use a temp key on ws-local, but require a user PFX on dist-winstore.
- On Windows 10.0 it requires a PFX for both store and phone …

TIMOB-20145 Use default temporary pfx from make when no pfx found in project and deploying to emulator or device

---

Source/TitaniumKit/include/Titanium/UI/ImageView.hpp
Source/TitaniumKit/src/UI/ImageView.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/include/TitaniumWindows/UI/View.hpp
Source/UI/src/ImageView.cpp
Source/UI/src/View.cpp
Source/Utility/src/Utility.cpp

Fix for [TIMOB-19954](https://jira.appcelerator.org/browse/TIMOB-19954)
- Implement `ImageView.defaultImage`, which enables to place placeholder image while waiting `image` loaded. especially useful when you need to grab `image` from network. 
- Implement `ImageView.toBlob` (but it does not work)
- Implement `View.toImage` (but it does not work)
Currently `toBlob` and `toImage` is always returning empty data. The problem is that they are using `Windows::UI::Xaml::Media::Imaging::RenderTargetBitmap::RenderAsync` to capture images from the component, but it always return `nullptr` when you call  `GetPixelsAsync`. I'm not sure if this API is actually implemented or working.
```javascript
var win = Ti.UI.createWindow({background:'black'});
var view = Ti.UI.createImageView({
defaultImage: …
```

Implement ImageView properties

---

Examples/Corporate/CMakeLists.txt
Examples/Corporate/src/Package.win10.appxmanifest.in
Examples/Geocoder/CMakeLists.txt
Examples/Geocoder/src/Package.win10.appxmanifest.in
Examples/Movies/CMakeLists.txt
Examples/Movies/src/Package.win10.appxmanifest.in
Examples/NG/CMakeLists.txt
Examples/NMocha/CMakeLists.txt
Examples/NMocha/src/Package.win10.appxmanifest.in
Examples/RSSReader/CMakeLists.txt
Examples/RSSReader/src/Package.win10.appxmanifest.in
Examples/ToDoList/CMakeLists.txt
Examples/ToDoList/src/Package.win10.appxmanifest.in
Tools/Scripts/generate_project.js

The node script didn't need updating for Windows 10, but I did want to clean it up a bit. It now uses the right settings by default if you pass along the -s 10.0 option to target Windows 10 (you don't necessarily have to also set the msbuild version, platform, etc).
The examples needed their CMakeLists.txt update to handle Windows 10, and a Win 10 appxmanifest template needed to be added to each.
https://jira.appcelerator.org/browse/TIMOB-20158

TIMOB-20158 Windows: Update generate_project.js script to handle Windows 10 appxmanifest

---

Source/UI/src/Window.cpp

Fix for [TIMOB-20166](https://jira.appcelerator.org/browse/TIMOB-20166)
```javascript
fullscreen: true,
});
var label = Ti.UI.createLabel({text:'Click here to exit fullscreen'});
// exit fullscreen when label is clicked
label.addEventListener('click', function () {
win.fullscreen = false;
});
win.open();
```

Fix: Window.fullscreen doesn't work on Windows 10

---

Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Window.cpp

Fix for [TIMOB-20187](https://jira.appcelerator.org/browse/TIMOB-20187)
*This works only on Windows 10 Store App*.
```javascript
var win = Ti.UI.createWindow({width:600, height:800, backgroundColor:'green'}),
lbl = Ti.UI.createLabel({ text: 'Hello, World' });
win.add(lbl);
win.open();
```

Fix: Window width & height for Store App doesn't work

---

Source/UI/src/Window.cpp

Follow-up on #519 
Fix crash with invalid width/height on Windows 10.
```javascript
var win = Ti.UI.createWindow({ width: '', height: '', backgroundColor: 'green' }),
lbl = Ti.UI.createLabel({ text: 'Hello, World' });
win.add(lbl);
win.open();
```

Fix crash with invalid width/height on Windows 10

---

Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/include/TitaniumWindows/UI/TabGroup.hpp
Source/UI/src/Tab.cpp
Source/UI/src/TabGroup.cpp

[TIMOB-20164](https://jira.appcelerator.org/browse/TIMOB-20164)
*Note: This needs #522 to be merged otherwise you'll see crash.*
Use `Windows::UI::Xaml::Controls::Pivot` for `Ti.UI.Tab/TabGroup` on Windows 10.
Note that the default color scheme is different between Windows 10 and Windows 10 Mobile.
```javascript
// create tab group
var tabGroup = Titanium.UI.createTabGroup();
//
// create base UI tab and root window
//
title: 'Tab 1',
});
var tab1 = Titanium.UI.createTab({
icon: 'KS_nav_views.png',
title: 'Tab 1',
window: win1
});
var label1 = Titanium.UI.createLabel({
color: '#999',
text: 'I am Window 1',
font: { fontSize: 20, fontFamily: 'Helvetica Neue' },
textAlign: 'center',
width: 'auto'
});
win1.add(label1);
//
// create …
```

Use Pivot for UI.TabGroup on Windows 10

---

templates/build/include/OutputDebugStringBuf.hpp
templates/build/src/main.cpp

Disable debug log on Release build which causes certification error described in [TIMOB-20192](https://jira.appcelerator.org/browse/TIMOB-20192).

Fix: Disable OutputDebugString on Release build

---

Examples/NG/src/OutputDebugStringBuf.hpp
Examples/NG/src/main.cpp
Examples/NMocha/src/OutputDebugStringBuf.hpp
Examples/NMocha/src/main.cpp
Source/LayoutEngine/CMakeLists.txt

Fix for [TIMOB-20201](https://jira.appcelerator.org/browse/TIMOB-20201)
- Enable `SAFESEH`([Safe Exception Handlers](https://msdn.microsoft.com/en-us/library/9a89h429.aspx)) for Windows Store/Phone x86 build
- Remove OutputDebugString from some examples
We have been disabling `SAFESEH` linker option just to suppress compiler warning message for simulator according to [HAL/CMakeLists.txt#L195](https://github.com/appcelerator/HAL/blob/master/CMakeLists.txt#L195) and [LayoutEngine/CMakeLists.txt#L57](https://github.com/appcelerator/titanium_mobile_windows/blob/master/Source/LayoutEngine/CMakeLists.txt#L57).
Since SAFESEH option is only available on x86 build, it has been a no problem before because it only affects on the simulator. But in the Windows 10 world, we could have x86 app for the …

[TIMOB-20201] Enable SAFESEH for Windows Store/Phone x86 build

---

Examples/NMocha/src/Assets/ti.database.test.js
Source/TitaniumKit/src/Database/ResultSet.cpp

https://jira.appcelerator.org/browse/TIMOB-20190
- Call `sqlite3_column_name`, not `sqlite3_column_text` to get the column name by index.
- Add some assertions to our mocha test for this method. (Probably should add a test for aliased column name, like `select name as full_name from contacts;`)

[TIMOB-20190] Ti.Database.ResultSet.fieldName([index]) is not returning the correct value

---

Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

- Implement missing ```ScrollView``` events
- ```dragend``` ```dragEnd``` ```dragstart``` ```dragStart``` ```scale``` ```scroll``` ```scrollend``` ```scrollEnd```
```Javascript
var win = Ti.UI.createWindow({}),
scrollView = Ti.UI.createScrollView({layout: 'vertical'});
for (var i = 0; i <= 20; i++) {
var row = Ti.UI.createView({height: 70}),
label = Ti.UI.createLabel({ text: 'ROW #' + i });
row.add(label);
scrollView.add(row);
}
// modify to test additional events
scrollView.addEventListener('scroll', function (e) {
Ti.API.info('scroll: ' + JSON.stringify(e, null, ' '));
});
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19959)

[TIMOB-19959] Implement missing ScrollView events

---

Source/UI/src/TableView.cpp

Fix for [TIMOB-20191](https://jira.appcelerator.org/browse/TIMOB-20191)
```javascript
var tableData = [{ title: 'Apples' }, { title: 'Bananas' }, { title: 'Carrots' }, { title: 'Potatoes' }];
data: tableData
});
table.addEventListener('click', function (e) {
Ti.API.info(e.source != table); // should be true
Ti.API.info(e.source == e.row); // should be true
Ti.API.info(e.source.title == e.row.title); // should be true
});
win.open();
```

[TIMOB-20191] e.source of a table click event should return table row

---

Examples/NMocha/src/Assets/ti.platform.test.js
Source/Ti/src/Platform.cpp

- Use the ```deviceClass``` to determin correct device to obtain the version from
```Javascript
lbl = Ti.UI.createLabel({ text: Ti.Platform.version });
win.add(lbl);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20167)

[TIMOB-20167] Fix Ti.Platform.version for Windows 10

---

Tools/Scripts/generate_project.js

- Fix ```msdev``` typo with ```msbuild```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20246)

[TIMOB-20246] Fix generate_project.js MSBuild parameter

---

Source/Titanium/include/TitaniumWindows/File.hpp

Fix for [TIMOB-20288](https://jira.appcelerator.org/browse/TIMOB-20288).
```javascript
var filePath = Ti.Filesystem.applicationDataDirectory + "test.txt";
var file = Ti.Filesystem.getFile(filePath);
file.write("日本語 : Japanese");
alert(file.read().text);
```

Fix: File.write can't handle UTF-8 string

---

Tools/Scripts/build/build.js

- Disable the reuse of MSBuild nodes; preventing the locking of resources
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20300)

[TIMOB-20300] Disable reuse of MSBuild in build.js

---

Source/UI/include/TitaniumWindows/UI/ProgressBar.hpp
Source/UI/src/ProgressBar.cpp

Fix for [TIMOB-20282](https://jira.appcelerator.org/browse/TIMOB-20282)
According to [Transitioning to the New UI Layout System](http://docs.appcelerator.com/platform/latest/#!/guide/Transitioning_to_the_New_UI_Layout_System), the default layout of `ProgressBar` should be `Ti.UI.SIZE`, not `Ti.UI.FILL`. For instance following example should show green background only under the progress bar & text, and it should not fill parent view.
```javascript
var pb = Ti.UI.createProgressBar({
min: 0,
max: 10,
value: 5,
color: 'blue',
backgroundDisabledColor: 'gray',
message: 'Downloading 0 of 10'
});
var win = Ti.UI.createWindow({backgroundColor:'yellow'});
win.add(pb);
win.open();
pb.show();
```

Fix: ProgressBar default layout should be SIZE, not FILL

---

Tools/Scripts/setup.js

Part of [TIMOB-20197](https://jira.appcelerator.org/browse/TIMOB-20197)
For me combination of fixing JavaScriptCore RAM size and [reducing memory consumption ion TitaniumKit](https://jira.appcelerator.org/browse/TIMOB-20256) fixes the crash at startup.

Revert JavaScriptCore RAM size config

---

Tools/Scripts/setup.js

Cherry-Pick #550
Part of [TIMOB-20197](https://jira.appcelerator.org/browse/TIMOB-20197)
For me combination of fixing JavaScriptCore RAM size and [reducing memory consumption ion TitaniumKit](https://jira.appcelerator.org/browse/TIMOB-20256) fixes the crash at startup.

[5_2_X] Cherry-Pick #550 Revert JavaScriptCore RAM size config

---

Examples/NMocha/src/Assets/ti.blob.test.js
Source/Titanium/include/TitaniumWindows/Blob.hpp
Source/Titanium/src/Blob.cpp
Source/TitaniumKit/include/Titanium/Blob.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/Blob.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

First cut for [TIMOB-20257](https://jira.appcelerator.org/browse/TIMOB-20257)
```javascript
var blob = Ti.Filesystem.getFile(Ti.Filesystem.applicationDirectory, 'Square150x150Logo.png').read();
var cropped   = blob.imageAsCropped({width:100, height:100, x:50, y:50});
var resized   = blob.imageAsResized(100, 100);
var thumbnail = blob.imageAsThumbnail(50);
```
`imageAsThumbnail` with `borderSize` and `cornerRaidus` is not implemented.

Implement Blob imageAs* methods

---

Tools/Scripts/build/test.js
Tools/Scripts/win10.bat

- Allow ```test.js``` ```-s``` to support a suffix that can be used to select a specific emulator version
- Set ```win10.bat``` to use ```10.0.10586```
- Fixed deployment issues with Windows 10 Jenkins server
```
node test.js -s 10.0.10586
```

Windows 10 Jenkins: Use 10.010586 emulator to resolve failing builds

---

Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp
Source/Utility/src/Utility.cpp

[TIMOB-20236](https://jira.appcelerator.org/browse/TIMOB-20236) 
Taking over #540 
- Fixed ```GetUriFromPath``` to handle local file paths
- Fix: ImageView default layout should be SIZE, not FILL
- Fix: GetUriFromPath with native path
```Javascript
var win = Ti.UI.createWindow({backgroundColor:'black'}),
img = Ti.UI.createImageView({height:'50%'}),
http = Titanium.Network.createHTTPClient({
onload: function () {
var f = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'win.png');
f.write(this.responseData);
Ti.App.fireEvent('downloaded', { path: f.nativePath });
},
timeout: 3000
});
http.open('GET', 'http://tinyurl.com/TIMOB-20236');
http.send();
Ti.App.addEventListener('downloaded', function (e) {
// img.image = e.path;
img.image = Ti.Filesystem.applicationDataDirectory + …
```

 [TIMOB-20236] Fix GetUriFromPath to handle local paths 

---

Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Implement ```Titanium.View.enabled``` functionality
- ```Windows::UI::Xaml::Controls::Canvas``` cannot be _enabled/disabled_, this had to be done manually
- ```backgroundDisabledColor``` of components has no effect, Windows uses a darker color of the parents ```backgroundColor```
```Javascript
view = Ti.UI.createView({ enabled: false, width: '80%', height: '50%', backgroundColor: 'blue', backgroundDisabledColor: 'red' }),
btn = Ti.UI.createButton({ title: 'BUTTON', backgroundColor: 'red' });
view.add(btn);
win.add(view);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20281)

[TIMOB-20281] Implement Titanium.View.enabled

---

Source/Map/src/View.cpp

The values from Ti.App.Properties are boost::optionals. That means they may contain a value or may not. In this case we always treated them like they had a value, which is bad because if there's no value and you call .get() or * on it, it'll barf/crash. So we check if there's a value and if so, set the MapServiceToken. If not we log an error message and move on.

Fix for trying to access mapservicetoken value when not present in ti.app.properties

---

templates/build/include/OutputDebugStringBuf.hpp
templates/build/src/main.cpp

Cherry-Pick #521 .
Should have been back-ported to 5_2_X.
Disable debug log on Release build which causes certification error described in [TIMOB-20192](https://jira.appcelerator.org/browse/TIMOB-20192).

[5_2_X]  Fix: Disable OutputDebugString on Release build

---

Source/UI/include/TitaniumWindows/UI/WindowsModule.hpp
Source/UI/include/TitaniumWindows/UIModule.hpp
Source/UI/src/UIModule.cpp
Source/UI/src/WindowsModule.cpp

Implement "lazy loading" for `Ti.UI.Windows` to reduce memory consumption when it's never used.
FYI  `Ti.UI.Windows` navigation sample code:
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' });
// Windows command bar
var commandBar = Ti.UI.Windows.createCommandBar();
// create buttons for the command bar
var backButton = Ti.UI.Windows.createAppBarButton({ icon: Ti.UI.Windows.SystemIcon.BACK, touchEnabled: false });
var nextButton = Ti.UI.Windows.createAppBarButton({ icon: Ti.UI.Windows.SystemIcon.FORWARD });
var separator = Ti.UI.Windows.createAppBarSeparator();
var acceptButton = Ti.UI.Windows.createAppBarToggleButton({ icon: Ti.UI.Windows.SystemIcon.ACCEPT });
backButton.addEventListener('click', function () {
win.close();
});
acceptButton.addEventListener('click', …
```

Lazy load Ti.UI.Windows

---

Source/Filesystem/CMakeLists.txt
Source/Filesystem/src/TitaniumEntryPoint.cpp
Source/Global/CMakeLists.txt
Source/Global/src/TitaniumEntryPoint.cpp
Source/Map/CMakeLists.txt
Source/Map/src/TitaniumEntryPoint.cpp
Source/Media/CMakeLists.txt
Source/Media/src/TitaniumEntryPoint.cpp
Source/Network/CMakeLists.txt
Source/Network/src/TitaniumEntryPoint.cpp
Source/Sensors/CMakeLists.txt
Source/Sensors/src/TitaniumEntryPoint.cpp
Source/Ti/CMakeLists.txt
Source/Ti/src/TitaniumEntryPoint.cpp
Source/UI/CMakeLists.txt
Source/UI/src/TitaniumEntryPoint.cpp
Source/Utility/CMakeLists.txt
Source/Utility/src/TitaniumEntryPoint.cpp

[TIMOB-20192](https://jira.appcelerator.org/browse/TIMOB-20192)
Attempt to fix "submission error 2001" described in https://msdn.microsoft.com/en-us/library/windows/apps/mt445539.aspx.
This PR just tries to make sure each `.winmd` file has at least one entry point (`ref class`). To test this, use [Ildasm.exe](https://msdn.microsoft.com/en-us/library/aa309387%28v=vs.71%29.aspx) to find a entry point in each `winmd` files. The other way to test is that usually `winmd` files are nearly `1KB` when it has no entry but it should be over `3KB` or so when it has an entry. Note that from what I saw only `TitaniumWindows_*.DLL` has its `winmd`, and `HAL`, `LayoutEngine` and `TitaniumKit` doesn't have it. (I expect it's because they do not use any Windows API?)
FYI `Ildasm.exe` is located under …

Make sure .winmd has at least one public entry point

---

cli/commands/_build/config/winPublisherId.js

- Added ```verifyIfRequired``` to ```winPublisherId.js``` config
```
appc run -p windows -T wp-device --deploy-type production --build-only
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18531)

[TIMOB-18531] Verify --win-publisher-id requirement for production builds

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

Fix for [TIMOB-20385](https://jira.appcelerator.org/browse/TIMOB-20385)
ScrollView does not respect `top` property on child views.
```javascript
backgroundColor: "#7B6700",
layout: "vertical"
});
var NavBarView = Ti.UI.createView({
height: "25",
top: 0,
backgroundColor: "green",
width: "100%"
});
var scrollView = Ti.UI.createScrollView({
height: '50%',
scrollType: "vertical",
layout: "vertical",
backgroundColor: "gray"
});
title: "Click",
width: "100",
height: "50",
top: 20, left: 20
});
scrollView.add(button);
win.add(NavBarView);
scrollView.addEventListener("postlayout", function (e) {
Ti.API.info(JSON.stringify(button.rect));
});
win.open();
```

[TIMOB-20385] Fix: ScrollView does not respect `top` property on views

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.app.windows.backgroundservice.test.js
Source/Network/include/TitaniumWindows/Network/HTTPClient.hpp
Source/Network/src/HTTPClient.cpp
Source/Sensors/src/Geolocation.cpp
Source/Ti/CMakeLists.txt
Source/Ti/include/TitaniumWindows/App/BackgroundService.hpp
Source/Ti/include/TitaniumWindows/App/BackgroundServiceTask.hpp
Source/Ti/include/TitaniumWindows/App/WindowsModule.hpp
Source/Ti/include/TitaniumWindows/AppModule.hpp
Source/Ti/src/App/BackgroundService.cpp
Source/Ti/src/App/BackgroundServiceTask.cpp
Source/Ti/src/App/WindowsModule.cpp
Source/Ti/src/AppModule.cpp
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/GeolocationModule.hpp
Source/TitaniumKit/src/GeolocationModule.cpp
Tools/Scripts/build/test.js

First cut for background service implementation. [TIMOB-18952](https://jira.appcelerator.org/browse/TIMOB-18952)
Initial goal is to enable HTTP access and geolocation in background.
Here's a sample code:
```javascript
});
var view = Ti.UI.createView({ layout: 'vertical' });
//
// Enable location tracking in background
//
Ti.App.Windows.BackgroundService.locationServiceEnabled = true;
//
// Callback for background task
// Note that you can't use setTimeout/setInterval in background, as well as any UI interaction (of course).
// Also, note that Ti.Geolocation events does not work in background. Use locationServiceEnabled instead.
//
var callback = function (e) {
//
// e.source ... task object that invokes this event
// e.cancel ... …
```

Implement Background Service

---

Source/Media/src/Media/AudioPlayer.cpp

- State changes need to happen on the main thread
- Although the ```Executable``` should only be defined for ```Control Channel``` or ```Push notification```, ```Audio``` does not work without it
- Updated [wiki](https://wiki.appcelerator.org/display/guides2/tiapp.xml+and+timodule.xml+Reference#tiapp.xmlandtimodule.xmlReference-BackgroundAudioCapability)
```XML
<windows>
<manifest>
<Extensions>
<Extension Category="windows.backgroundTasks" Executable="$targetnametoken$.exe" EntryPoint="TitaniumWindows_Media.AudioBackground">
<BackgroundTasks>
<Task Type="audio" />
</BackgroundTasks>
</Extension>
</Extensions>
</manifest>
</windows>
```
```Javascript
var audioPlayer = Ti.Media.createAudioPlayer({url: 'http://media-the.musicradio.com:80/SmoothExtraMP3'}),
win = …
```

[TIMOB-20080] Implement Ti.Media.AudioPlayer.allowBackground for Windows 10

---

cli/commands/_build/copy.js
templates/build/Package.store.appxmanifest.in.ejs
templates/build/Package.win10.appxmanifest.in.ejs

[TIMOB-20496](https://jira.appcelerator.org/browse/TIMOB-20496)
Enabling background task requires "badge icon" when building for Windows Store. It is required to package the app even when badge is not actually used.
```
> appc ti build -T dist-winstore -p windows
error APPX1675: App manifest declares background task of type timer, control channel, 
push notification, or location without enabling lock screen notifications. 
```
FYI: Enabling background task (tiapp.xml)
```xml
<windows>
<manifest>
<Extensions>
<Extension Category="windows.backgroundTasks" EntryPoint="TitaniumWindows_Ti.BackgroundServiceTask">
<BackgroundTasks>
<Task Type="timer" />
</BackgroundTasks>
</Extension>
</Extensions>
</manifest>
</windows>
```

[TIMOB-20496] Badge icon needed with background task for Store

---

cli/commands/_build/generate.js
templates/build/Package.phone.appxmanifest.in.ejs
templates/build/Package.store.appxmanifest.in.ejs
templates/build/Package.win10.appxmanifest.in.ejs

[TIMOB-20481](https://jira.appcelerator.org/browse/TIMOB-20481)
Add localization support for application name. You can use Titanium's [string localization resources](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Locale-method-getString) to localize application name. You need to use `app_name` for application name, and `app_description` for application description. These entries are optional. Note that you may need to uninstall existing app in order to see updated application name.
```xml
<resources>
<string name="app_name">Titanium Test App</string>
<string name="app_description">This is awesome app</string>
</resources>
```
```xml
<resources>
<string name="app_name">Titanium テスト</string> …
```

[TIMOB-20481] Support l10n application name

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Button.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-20386](https://jira.appcelerator.org/browse/TIMOB-20386).
This PR improves response rate of`Ti.UI.Button` `click` event significantly. It looks like the issue is because Xaml `Tapped` event is not so responsive, and on the Button we have `Click` event which works much better.
Sample code: Try clicking the button fast, for instance 3 clicks at one second.
```javascript
width: Ti.UI.FILL, height: Ti.UI.FILL,
});
var count = 0;
width: Ti.UI.FILL, height: '10%',
text: '0',
textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
font: { fontSize: 48 }
});
width: Ti.UI.FILL, height: '10%',
title: 'PUSH'
}); …
```

[TIMOB-20386] Fix: View based click event is not responsive

---

cli/commands/_build/generate.js

Related to #572
Fix: Duplicate `app_name` entry build error happens when you build app with i18n application name. Default `app_name/description` should be added only when there's no locale strings.
```xml
<resources>
<string name="app_name">Titanium Test App</string>
<string name="app_description">This is awesome app</string>
</resources>
```

Fix: default app_name/description should be added only when there's no locale strings

---

cli/commands/_build/generate.js

[5_3_X] Fix: default app_name/description should be added only when there's no locale strings

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Button.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Backport of https://github.com/appcelerator/titanium_mobile_windows/pull/578
- Previous https://github.com/appcelerator/titanium_mobile_windows/pull/581 was accidentally merged to ```master```

[TIMOB-20386][5_3_X] Fix: View based click event is not responsive

---

cli/commands/_build/config/deviceID.js

- Pass ```wp-sdk``` to windowslib so it can determine the correct tool to use [wptool.js#L397](https://github.com/appcelerator/windowslib/blob/master/lib/wptool.js#L397)
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20566)

[TIMOB-20566] Pass wp-sdk to windowslib during connect()

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-20612](https://jira.appcelerator.org/browse/TIMOB-20612)
```javascript
var win = Titanium.UI.createWindow({backgroundColor:'green'});
var view = Titanium.UI.createView({
width: 200,
height: 200
});
var view2 = Titanium.UI.createView({
width: '80%',
height: '80%',
});
width: '80%',
height: '80%'
});
view2.add(view3);
view.add(view2);
view.addEventListener('postlayout', function () {
Ti.API.info('view postlayout');
});
view.width  = view.width  * 0.9;
view.height = view.height * 0.9;
});
view2.addEventListener('postlayout', function () {
Ti.API.info('view2 postlayout');
});
view3.addEventListener('postlayout', function () { …
```

[TIMOB-20612] postlayout events not firing

---

Source/Network/src/HTTPClient.cpp

- Fix ``cancellationToken`` in ``configureTimeout``
- In some cases the ``cancellationTokenSource__`` would become invalid after the timeout period
- This should hopefully fix the unit tests

Fix HTTPClient configureTimeout()

---

Source/Network/include/TitaniumWindows/Network/HTTPClient.hpp
Source/Network/src/HTTPClient.cpp

Attempt to stabilize `HTTPClient`, basically reverts `HTTPClient` to the state before #566.

Revert HTTPClient

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-20605](https://jira.appcelerator.org/browse/TIMOB-20605)
```javascript
var win = Titanium.UI.createWindow({ backgroundColor: 'green' });
var view = Titanium.UI.createView({
width: 200,
height: 200
});
var view2 = Titanium.UI.createView({
width: '80%',
height: '80%',
});
width: '80%',
height: '80%'
});
view2.add(view3);
view.add(view2);
view.center = { x: e.x, y: e.y };
})
win.add(view);
win.open();
```

[TIMOB-20605] Fix: view.center not working

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Fix for [TIMOB-20569](https://jira.appcelerator.org/browse/TIMOB-20569)
```javascript
var win = Titanium.UI.createWindow({backgroundColor:'green'});
var view = Titanium.UI.createView({
width: 200,
height: 200
});
var view2 = Titanium.UI.createView({
borderRadius: 10,
width: 150,
height: 150
});
text: 'TEST',
visible: false /* hidden */
});
view2.add(label);
view.add(view2);
label.visible = !label.visible;
})
win.add(view);
win.open();
```
```javascript
var win = Titanium.UI.createWindow({backgroundColor:'green'});
var view = Titanium.UI.createView({
width: 200,
height: 200
});
var view2 = Titanium.UI.createView({ …
```

[TIMOB-20569] Fix: View visible property doesn't seem to work

---

Source/TitaniumKit/include/Titanium/UI/ImageView.hpp
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/UI/ImageView.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/include/TitaniumWindows/UI/View.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/ImageView.cpp
Source/UI/src/View.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp
Source/Utility/include/TitaniumWindows/Utility.hpp
Source/Utility/src/Utility.cpp

- Implement ``Titanium.View.toImage()`` into ``ViewLayoutDelegate``
- Fixed use of ``JSValue`` for callbacks
- Fixed ``Titanium.ImageView.toBlob()``
- Fixed ``Titanium.ImageView.toImage()``
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'red'}),
lbl = Ti.UI.createLabel({text: 'TEST TEXT'});
img = Ti.UI.createImageView({width: '80%', height: '80%'});
win.toImage(function(image) {
img.image = image;
win.backgroundColor = 'blue';
});
win.add(lbl);
win.add(img);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19988)

[TIMOB-19988] Implement Titanium.View.toImage()

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Source/TitaniumKit/include/Titanium/UI/ImageView.hpp
Source/TitaniumKit/src/UI/ImageView.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp

Fix for [TIMOB-23115](https://jira.appcelerator.org/browse/TIMOB-23115)
```javascript
var file0 = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "Logo.png");
var file1 = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "SmallLogo.png");
var file2 = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "StoreLogo.png");
var imageview = Ti.UI.createImageView({
width: Ti.UI.FILL, height: Ti.UI.FILL,
duration: 1000
});
var url0 = "http://api.randomuser.me/portraits/women/0.jpg",
url1 = "http://api.randomuser.me/portraits/women/1.jpg",
url2 = "http://api.randomuser.me/portraits/women/2.jpg";
imageview.images = [ file0, file1, file2 ]; // File
// imageview.images = [ file0.read(), file1.read(), file2.read() ]; // Blob …
```

[TIMOB-23115] ImageView.image doesn't handle Ti.File/Blob

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Source/Network/include/TitaniumWindows/Network/HTTPClient.hpp

Fix for [TIMOB-23127](https://jira.appcelerator.org/browse/TIMOB-23127)
```javascript
win.addEventListener('open', function() {
var http = Ti.Network.createHTTPClient({
onload: function() {
Ti.API.info('API: step onload');
var res = JSON.parse(this.responseText);
},
onerror: function(error) {
Ti.API.info('API: step onerror');
},
timeout: 90000
});
http.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
http.open('POST', 'http://www.appcelerator.com/');
http.send('TIMOB-23127');
});
win.open();
```

[TIMOB-23127] HTTPClient.setRequestHeader should be case-insensitive

---

Source/UI/include/TitaniumWindows/UI/PickerColumn.hpp
Source/UI/src/Picker.cpp
Source/UI/src/PickerColumn.cpp
Source/UI/src/PickerRow.cpp

Small RP to fix runtime error on plain picker. Note that this does not fix rendering issue on Windows Phone 8.1.
```javascript
});
var picker = Ti.UI.createPicker({
backgroundColor:'blue',
top: 50, height: '20%'
});
var fruit = ['Bananas', 'Strawberries', 'Mangos', 'Grapes'];
var color = ['red', 'green', 'blue', 'orange'];
var column1 = Ti.UI.createPickerColumn();
for (var i = 0, ilen = fruit.length; i < ilen; i++) {
var row = Ti.UI.createPickerRow({
title: fruit[i]
});
column1.addRow(row);
}
var column2 = Ti.UI.createPickerColumn();
for (var i = 0, ilen = color.length; i < ilen; i++) {
var row = Ti.UI.createPickerRow({ title: color[i] });
column2.addRow(row);
}
picker.add([column1, column2]);
picker.addEventListener('change', function (e) …
```

Fix Picker runtime error

---

Source/UI/src/ListView.cpp
Source/UI/src/TabGroup.cpp
Source/UI/src/TableView.cpp
Source/Utility/src/Utility.cpp

Fix logical error.
The `boolean` return value from `UIElementCollection.IndexOf` should be used to check if element has been found. `index` parameter for `IndexOf` never be negative because it's unsigned int.

Use return value from Collection.IndexOf to check if it's found

---

Examples/NMocha/src/Assets/ti.ui.view.test.js
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/src/UI/View.cpp
Source/UI/src/Window.cpp

[TIMOB-20580](https://jira.appcelerator.org/browse/TIMOB-20580)
- `View.parent`
- `View.getParent`
- `View.setParent`
Added `getParent` as well as `setParent`, because they're implemented on iOS.
```javascript
title: 'test', backgroundColor: '#fff'
});
width: '100%',
height: '100%'
});
view.add(Ti.UI.createButton({
title: 'color change',
}));
view.children[0].addEventListener('click', function () {
this.parent.setBackgroundColor('red');
});
Ti.API.info(view.children[0].parent == view);
Ti.API.info(view.parent == win);
});
win.add(view);
win.open();
```

[TIMOB-20580] Implement View.parent

---

templates/module/default/template/windows/include/{{moduleIdAsIdentifier}}.hpp.ejs
templates/module/default/template/windows/src/{{moduleIdAsIdentifier}}.cpp.ejs

Add example method and property for Windows module template to align with iOS/Android templates.
See also: [iOS Module Quick Start ](http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Module_Quick_Start)
```javascript
var test = require('com.example.test');
Ti.API.info("module is => " + test);
Ti.API.info("module example() method returns => " + test.example());
Ti.API.info("module exampleProp is => " + test.exampleProp);
test.exampleProp = "This is a test value";
```

Add example method/propery in module template

---

cli/commands/_build/config/wpSDK.js

- Add ability to filter unsupported Windows SDKs ``8.0``
```
appc run -p windows --wp-sdk 8.0
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23192)

[TIMOB-23192] Filter unsupported Windows SDK 8.0

---

templates/build/Package.store.appxmanifest.in.ejs

Cherry-pick of #629:
This is an "experimental" fix. From https://social.msdn.microsoft.com/Forums/vstudio/en-US/f0339531-123d-4764-927d-8ed9251ce65a/why-do-i-have-to-specify-a-background-task?forum=csharpgeneral it appears if you set a badge logo, it thinks you have must intend to do notifications and must have a background service defined.
https://jira.appcelerator.org/browse/TIMOB-23217

Fix TIMOB-23217 Windows: Packaging for dist-winstore with 8.1 SDK fails - remove badge logo

---

templates/build/Package.store.appxmanifest.in.ejs

This is an "experimental" fix. From https://social.msdn.microsoft.com/Forums/vstudio/en-US/f0339531-123d-4764-927d-8ed9251ce65a/why-do-i-have-to-specify-a-background-task?forum=csharpgeneral it appears if you set a badge logo, it thinks you have must intend to do notifications and must have a background service defined.
https://jira.appcelerator.org/browse/TIMOB-23217

[5_3_X] Fix TIMOB-23217 Windows: Packaging for dist-winstore with 8.1 SDK fails - remove badge logo

---

Source/UI/include/TitaniumWindows/UI/ActivityIndicator.hpp
Source/UI/src/ActivityIndicator.cpp

[TIMOB-19945](https://jira.appcelerator.org/browse/TIMOB-19945)
- Ti.UI.ActivityIndicator.color
- Ti.UI.ActivityIndicator.font
- Ti.UI.ActivityIndicator.indicatorColor
```javascript
var win1 = Ti.UI.createWindow({
});
var win2 = Ti.UI.createWindow({
fullscreen: true
});
var activityIndicator = Ti.UI.createActivityIndicator({
color: 'green',
indicatorColor:'red',
font: { fontSize: 26, fontWeight: 'bold' },
message: 'Loading...',
top: 10,
left: 10,
width: Ti.UI.SIZE
});
win2.add(activityIndicator);
win2.addEventListener('open', function (e) {
activityIndicator.show();
e.source.close();
activityIndicator.hide();
}, 6000);
});
win1.open();
win2.open();
```

[TIMOB-19945] Implement Ti.UI.ActivityIndicator properties

---

Source/Ti/src/Codec.cpp
Source/TitaniumKit/include/Titanium/Buffer.hpp
Source/TitaniumKit/src/Buffer.cpp

Additional commit on top of #631

[TIMOB-23222] Fix crash at Ti.Codec.decodeNumber - variable length of bytes to read

---

Source/Ti/src/Codec.cpp
Source/TitaniumKit/include/Titanium/Buffer.hpp
Source/TitaniumKit/src/Buffer.cpp

Fix for [TIMOB-23222](https://jira.appcelerator.org/browse/TIMOB-23222)
```javascript
var win = Ti.UI.createWindow({backgroundColor:'blue'});
var file = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "data.bin");
Ti.API.info('File meta:' + file.size);
var blob = file.read();
var length = blob.length;
// Convert Ti.Blob to Ti.Buffer
var stream = Ti.Stream.createStream({ source: blob, mode: Ti.Stream.MODE_READ });
var buffer = Ti.createBuffer({ length: length });
stream.read(buffer);
Ti.API.info("file loaded. size=" + buffer.length);
// Read and parse the data
var index = Ti.Codec.decodeNumber({ source: buffer, position: 0, type: Ti.Codec.TYPE_INT });
Ti.API.info('Checkpoint');
var myArray = [];
for (var i = 0; i < 2048; i++) { …
```

[TIMOB-23222] Fix crash at Ti.Codec.decodeNumber

---

templates/module/default/template/windows/include/{{moduleIdAsIdentifier}}.hpp.ejs
templates/module/default/template/windows/src/{{moduleIdAsIdentifier}}.cpp.ejs

Update module template to support Ti event methods, to align with other platforms:
- Module should extend `Titanium::Module` to support event mechanics (`fireEvent`, `addEventListener` etc)

Template: Module should extend Titanium::Module

---

cli/commands/_buildModule.js

- Use correct build events for module build process
```
appc new -t timodule -n module --id com.win.module
cd module\windows
appc run -p windows --build-only
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23251)

[TIMOB-23251] Fix module build process for appc run

---

Source/TitaniumKit/include/Titanium/UI/ListSection.hpp
Source/TitaniumKit/src/UI/ListSection.cpp
Source/TitaniumKit/src/UI/ListView.cpp

[TIMOB-23187](https://jira.appcelerator.org/browse/TIMOB-23187)
- Fix: `ListView.searchText` doesn't work with `searchableText`
- Fix: `ListView.caseInsensitiveSearch` is ignored
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' });
var searchText = Ti.UI.createTextField({width:Ti.UI.FILL, height: '10%'});
var listView = Ti.UI.createListView({width:Ti.UI.FILL, height: '90%', caseInsensitiveSearch: false});
var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits' });
{ properties: { title: 'Apple', searchableText: 'Manzana' } },
{ properties: { title: 'Banana', searchableText: 'Plátano' } },
];
var vegSection = Ti.UI.createListSection({ …
```

[TIMOB-23187] Fix: ListView.searchText doesn't work with searchableText

---

Source/Ti/include/TitaniumWindows/API.hpp
Source/Ti/src/API.cpp
Source/Utility/CMakeLists.txt
Source/Utility/include/TitaniumWindows/LogForwarder.hpp
Source/Utility/src/LogForwarder.cpp
templates/module/default/hooks/windows-module.js
templates/module/default/template/windows/CMakeLists.txt.ejs
templates/module/default/template/windows/src/{{moduleIdAsIdentifier}}.cpp.ejs

[TIMOB-23241](https://jira.appcelerator.org/browse/TIMOB-23241)
Logging macros for native module debugging. 
```c++
// Logging macro for module debugging: 
TITANIUM_MODULE_LOG_TRACE("value: " << value);
// Logging macro for background module debugging: 
TITANIUM_MODULE_LOG_INFO_BACKGROUND("value: " << value);
```
Background service classes needs special macro because it's independent from app.

[TIMOB-23241] Logging macros for native module

---

cli/commands/_build/config/deviceID.js
cli/commands/_build/config/wpSDK.js
cli/hooks/wp-run.js

Requires appcelerator/windowslib#41 and then we'll need to bump the version and update packaged windowslib on titanium_mobile 5_3_X branch.
- don't connect to device as part of deviceId validation. Seems good enough if the udid can be found in our listing. Connecting slows down the start of the build by a good amount.
- Don't report the build time twice
- Don't try to launch the apps on Windows 10 mobile as this always fails now. Instead spit out a warning message asking user to launch manually. This actually fixes https://jira.appcelerator.org/browse/TIMOB-20611
- log when we start installing dependencies and the app itself to give a little better indicator of progress

[TIMOB-23253] Windows: Build errors when building to device and selecting second option in device prompt

---

Source/TitaniumKit/include/Titanium/API.hpp
Source/TitaniumKit/src/API.cpp

[TIMOB-23237](https://jira.appcelerator.org/browse/TIMOB-23237)
`Ti.API.log('meh','I am default log');` should show custom log level with upper case in `DEBUG` log, to align with iOS behavior.
```
[DEBUG] [MEH] I am default log
```

[TIMOB-23237] Show custom log level in DEBUG

---

Source/TitaniumKit/src/UI/Constants.cpp
Source/UI/src/ScrollView.cpp

[TIMOB-23293](https://jira.appcelerator.org/browse/TIMOB-23293)
Corporate Directory App had layout issue. Pushing some improvements:
- ScrollView should fill views
- Label.textAlign should accept "center","left","right"
It still doesn't look very beautiful but pushing since that's not a regression for 5.3.x.

[TIMOB-23293] Fix layout issue on Corporate Directory App

---

apidoc/Titanium/UI/Tab.yml
apidoc/Titanium/UI/TabGroup.yml

[TIMOB-19960](https://jira.appcelerator.org/browse/TIMOB-19960)
Fix yaml doc for `Tab` and `TabGroup`.
- `Focused` and `Disabled` color doesn't work because of platform limitations.

[5_3_X] [TIMOB-19960] Update docs for Tab/TabGroup bg color

---

Source/UI/src/ImageView.cpp

- Add initialization for ``imageAsBlob()`` and ``imageAsFile``
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'black' }),
file = Ti.Filesystem.getFile('Logo.png'),
imgA = Ti.UI.createImageView({ image: file.read(), top:'33%', width: 200, height: 200 }),
imgB = Ti.UI.createImageView({ image: 'Logo.png', top:'66%', width: 200, height: 200 });
win.add(imgA);
win.add(imgB);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23273)

[TIMOB-23273] Fix initialization of Ti.UI.ImageView imageAsBlob() and imageAsFile()

---

Source/Ti/include/TitaniumWindows/API.hpp
Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/API.hpp
Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/include/Titanium/detail/TiLogger.hpp
Source/TitaniumKit/include/Titanium/detail/TiLoggerPolicyAPI.hpp
Source/TitaniumKit/include/Titanium/detail/TiLoggerPolicyConsole.hpp
Source/TitaniumKit/src/App/Properties.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/TitaniumKit/src/detail/TiLoggerPolicyAPI.cpp
Source/UI/include/TitaniumWindows/UI/View.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp
Source/Utility/include/TitaniumWindows/LogForwarder.hpp

#666 + Add `TITANIUM_API_LOG` to enable output to log relay from TitaniumKit. Note that `TITANIUM_API_LOG` is available only where `get_context()` can be used.

[TIMOB-23275] Windows: Deprecate Ti.UI.View.enabled, rename to touchEnabled

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

I have experienced `no matching function to call std::transform` compile error for UWP 10.0 app project on freshly-installed Windows 10 + Visual Studio 2015. It looks like we have a workaround (See thread in [stackoverflow](http://stackoverflow.com/questions/7131858/stdtransform-and-toupper-no-matching-function) for details) and see how it goes.

Fix: "no matching function to call transform" on VS 2015

---

Source/Map/src/View.cpp

https://jira.appcelerator.org/browse/TIMOB-23278
Once merged, this needs to be cherry-picked over to master

[5_3_X][TIMOB-23278] Windows: Ti.Map does not use the region when specified on Windows 10

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp
Source/TitaniumKit/include/Titanium/Media/CameraMediaItemType.hpp
Source/TitaniumKit/include/Titanium/Media/CameraOptionsType.hpp
Source/TitaniumKit/include/Titanium/UI/Constants.hpp
Source/TitaniumKit/src/Media/CameraMediaItemType.cpp
Source/TitaniumKit/src/Media/CameraOptionsType.cpp
Source/TitaniumKit/src/UI/Constants.cpp
Source/TitaniumKit/src/UIModule.cpp
Source/Utility/include/TitaniumWindows/Utility.hpp
Source/Utility/src/Utility.cpp

Fix [TIMOB-23262](https://jira.appcelerator.org/browse/TIMOB-23262)
- Camera preview should launch in full screen
- Camera preview should be placed at the bottom of the screen z order to accept overlaying view
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' });
var overlay = Ti.UI.createView({ backgroundColor: 'blue', layout: 'vertical', height:'20%', width:Ti.UI.FILL }),
hideButton = Ti.UI.createButton({ title:'HIDE PREVIEW' , backgroundColor:'red'});
});
hideButton.addEventListener('click', function () {
Ti.Media.hideCamera();
});
overlay.add(takeButton);
overlay.add(hideButton); …
```

[TIMOB-23262] Fix: Ti.Media.showCamera() doesn't launch in full screen

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-23357](https://jira.appcelerator.org/browse/TIMOB-23357)
Suppress warning log message for `blur` and `focus`.

[TIMOB-23357] Suppress warning log for blur and focus

---

Source/Network/CMakeLists.txt
Source/Ti/include/TitaniumWindows/App/Properties.hpp
Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/src/App/Properties.cpp
Source/TitaniumKit/src/UI/Tab.cpp
Source/TitaniumKit/src/UI/Window.cpp
Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Tab.cpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Cherry-pick #680 for 5_3_X.
This also includes fix for compile error on Windows 10.

[5_3_X] [TIMOB-23349] Fix: Closing Windows via Ti.UI.Tab.open() does not work

---

Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/src/UI/Tab.cpp
Source/TitaniumKit/src/UI/Window.cpp
Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Tab.cpp
Source/UI/src/Window.cpp

[TIMOB-23349](https://jira.appcelerator.org/browse/TIMOB-23349)
```javascript
var colors = ['blue', 'gray', 'red'];
function createWindow(depth) {
backgroundColor: colors[depth % colors.length]
});
win.add(Ti.UI.createLabel({
text: 'Depth ' + depth
}));
var openBtn = Ti.UI.createButton({
top: 20,
title: 'Open Child'
});
openBtn.addEventListener('click', function () {
tabA.open(createWindow(depth + 1));
});
win.add(openBtn);
if (depth > 0) {
var closeViaWinBtn = Ti.UI.createButton({
top: 20,
title: 'Close via Window'
});
closeViaWinBtn.addEventListener('click', function () {
win.close();
});
win.add(closeViaWinBtn);
var closeViaTabBtn = Ti.UI.createButton({
top: 20,
title: 'Close via Tab'
});
closeViaTabBtn.addEventListener('click', …
```

[TIMOB-23349] Fix: Closing Windows via Ti.UI.Tab.open() does not work

---

Source/UI/include/TitaniumWindows/UI/ProgressBar.hpp
Source/UI/src/ProgressBar.cpp

[TIMOB-23283](https://jira.appcelerator.org/browse/TIMOB-23283)
```javascript
var pb = Ti.UI.createProgressBar({
min: 0,
max: 10,
value: 0,
color: 'blue',
backgroundDisabledColor: 'gray',
message: 'Downloading 0 of 10',
});
win.add(pb);
win.open();
pb.show();
```

[TIMOB-23283] Fix ProgressBar with FILL should fill the view

---

Source/UI/src/PickerRow.cpp

- Set the ``WindowsViewLayoutDelegate`` for ``Titanium.UI.PickerRow`` allowing properties such as ``backgroundColor`` to be set
```Javascript
picker = Ti.UI.createPicker({top: 10});
picker.add(Ti.UI.createPickerRow({ title: 'Bananas', backgroundColor: 'yellow'}));
picker.add(Ti.UI.createPickerRow({ title: 'Strawberries', backgroundColor: 'red' }));
picker.add(Ti.UI.createPickerRow({ title: 'Grapes', backgroundColor: 'purple' }));
win.add(picker);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23294)

[TIMOB-23294] Set Ti.UI.PickerRow ViewLayoutDelegate

---

Examples/Corporate/src/Assets/alloy/controllers/profile.js
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/src/Label.cpp

- [[TIMOB-23372]](https://jira.appcelerator.org/browse/TIMOB-23372) Fix: layout with left & right breaks layout
- [[TIMOB-23373]](https://jira.appcelerator.org/browse/TIMOB-23373) Fix: Label with height should render text vertically centered
*TIMOB-23372*
```javascript
layout: "horizontal",
top: 10,
left: 10,
width: Ti.UI.SIZE,
});
left: 10,
right: 10,
color: "blue",
text: "this is test text"
});
view.add(label);
win.add(view);
win.open();
```
*TIMOB-23373*
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'white' });
var view = Ti.UI.createLabel({
text: "A",
height: 100,
width: 100,
color: "#C41230", …
```

[TIMOB-23372]  [TIMOB-23373] Fix resize issue with Label

---

Source/UI/include/TitaniumWindows/UI/Button.hpp
Source/UI/src/Button.cpp

https://jira.appcelerator.org/browse/TIMOB-23363
Note that this also fixes an incorrect implementation of verticalAlign property.
For certain controls, like Button, they are subclasses of ContentControl - meaning they have a Content property which can typically take a simple String or an actual complex UI as the value. For these controls, to be able to manage their content they have special properties:
- HorizontalContentAlignment
- VerticalContentAlignment
We just need to use those to set textAlign/verticalAlign on the internal text.

[TIMOB-23363] Windows: textAlign property of Button does not work in 8.1 or 10

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

https://jira.appcelerator.org/browse/TIMOB-23374
This simply applies background brushes (color/image/gradient) to the wrapping Border object when we have a non-null border__ (and don't have an underlying_control__).
I have no idea the ordering of when this should apply: I stuck it before the is_panel and is_control checks, but honestly I don't know under what circumstance we should move the background to the wrapping border and when we shouldn't.
When merged, this needs to be cherry-picked to master.

[5_3_X][TIMOB-23374] Windows: Label backgroundColor cut through border with radius

---

Source/UI/src/Label.cpp

[TIMOB-23293](https://jira.appcelerator.org/browse/TIMOB-23293)
[TIMOB-23377](https://jira.appcelerator.org/browse/TIMOB-23377)

[5_3_X] Fix: Workaround to make corporate app look right

---

Source/Network/src/HTTPClient.cpp

[TIMOB-23400](https://jira.appcelerator.org/browse/TIMOB-23400)
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' });
Ti.Analytics.featureEvent('featureEvent', {
'féátúréEvéntVálúé': 'féátúréEvéntKéy'
});
});
win.open();
```
Expected characters to send:
```
f\u00e9\u00e1t\u00far\u00e9Ev\u00e9ntV\u00e1l\u00fa\u00e9: "f\u00e9\u00e1t\u00far\u00e9Ev\u00e9ntK\u00e9y”
```

[5_3_X] [TIMOB-23400] Fix: Analytics sends wrong UTF8 characters

---

Source/TitaniumKit/src/analytics.js

https://jira.appcelerator.org/browse/TIMOB-23392
Basically it boils down to us using the ISO string format and the other platforms using a "+0000" timezone offset instead of "Z" at the end. So I generate our ISO string and replace "Z" with "+0000".

[TIMOB-23392] Analytics: Timestamp for Windows payloads are inconsistent with other platforms

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/LayoutEngine/src/Composite.cpp
Source/LayoutEngine/src/Horizontal.cpp
Source/LayoutEngine/src/Vertical.cpp
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Label.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-23372](https://jira.appcelerator.org/browse/TIMOB-23372)
#690 + unit tests + fixes on Label
- Fix ``right`` and ``bottom`` margins in ``Composite`` ``Horizontal`` and ``Vertical`` of LayoutEngine
- The layout engine did not take into account the ``right`` offset when calculating the new width due to an incorrect ``if`` statement
- If a component is of width ``Ti.UI.SIZE`` and the ``right`` margin is specified, it should calculate the new width taking into account both ``left`` and ``right`` margins
- Made a workaround to match iOS and Android when percentage values of ``left`` and ``right`` are set inside a parent View
```javascript
top: 10,
left: 10,
right: 10,
height: …
```

[TIMOB-23372] Fix: right margin breaks layout

---

Source/TitaniumKit/src/analytics.js

https://jira.appcelerator.org/browse/TIMOB-23398
We need to prefix sdkver value with "ti." and trim the version down to the first three segments (drop the timestamp qualifier).

[TIMOB-23398] Analytics: SDK version format on Windows phone should match other platforms

---

Source/UI/src/ScrollView.cpp

- Default ``Titanium.UI.ScrollView`` ``width height`` to ``Titanium.UI.FILL``
```Javascript
scrollView = Ti.UI.createScrollView({
layout: "vertical",
}),
top: 10,
left: 10,
width: Ti.UI.SIZE
}),
label = Ti.UI.createLabel({
left: 10,
right: 10,
color: "green",
text: "this is test text"
});
view.add(label);
scrollView.add(view);
win.open();
```
[JIRA Ticket](TIMOB-23350)

[TIMOB-23350] Default ScrollView width and height to Ti.UI.FILL

---

Source/TitaniumKit/include/Titanium/Locale.hpp
Source/TitaniumKit/src/Locale.cpp

[TIMOB-23307](https://jira.appcelerator.org/browse/TIMOB-23307)
I observed that not all escape characters in localized strings are actually escaped on iOS, and so we try to simulate what iOS does on Windows.
character | actual
------------ | -------------
\r | new line
\n | new line
\f | new line
\t | tab
\\ | \
\" | "
\' | '
\b| ignored
\uxxx (unicode characters) | uxxx
```xml
<resources>
<string name="phrase">"\t"A l\bon\'g l\"abel w\\ith\r\n a few l\rine bre\faks\n and unicode (UTF8)\n symbols such as\n a white chess piece \u2655\nand the euro symbol \u20ac\nlooks like this!\n</string>
</resources>
```
```javascript
top: 10,
left: 10,
width: …
```

[TIMOB-23307] Localized strings in strings.xml don't handle \n newlines

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/src/Module.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/ImageView.cpp
Source/UI/src/Label.cpp

[TIMOB-23305](https://jira.appcelerator.org/browse/TIMOB-23305)
Attempt to update width when setting new text. Currently it's blocked because Xaml `TextBlock` does not shrink its size with shorter text.
* `TextBlock` does not change its size when `TextWrapping` is `Wrap`.
* `TextBlock` expands its size when `TextWrapping` is `NoWrap`.
* `TextBlock` does not shrink its size in every cases of text wrapping.
* ~~We might need to find a way to calculate its size for the given text and font manually.~~ <- `Measure()` works good for it
```javascript
});
var update = true;
var topView = Ti.UI.createView({ backgroundColor: 'blue', width: Ti.UI.FILL, height: '10%' });
var button = Ti.UI.createButton({ title: 'Change Text' …
```

[TIMOB-23305] Ti.UI.Label width is not updated when setting new text

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Examples/NMocha/src/Assets/ti.network.test.js
Source/Network/include/TitaniumWindows/Network/HTTPClient.hpp
Source/Network/src/HTTPClient.cpp
Source/TitaniumKit/include/Titanium/Network/HTTPClient.hpp
Source/TitaniumKit/src/Network/HTTPClient.cpp

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-23422
Looks like we're mangling the post data we send as multi-part form data. I'm not sure we can properly convert everything to `std::vector<std::uint8_t>` like we currently do. So this PR goes back to keep the values as JSValue and letting the Windows implementation look for Blobs and when found basically just copy their data as a buffer passthrough, otherwise cast to std::string and convert to Platform::String as normal string content.
I created a new requestbin used below, and tested with the following code. I still need to hit it with iOS/Android to compare the exact data from the PNG file matches, but the request looks closer. (Note that Android actually writes a blob as a file to disk and then uses Apache's FileBody to attach it …

[TIMOB-23422] Try and fix HTTPClient post with Blob and string data

---

Source/Sensors/src/Geolocation.cpp
Source/Titanium/include/TitaniumWindows/TitaniumWindows.hpp
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp
Source/TitaniumKit/src/GlobalObject.cpp
Source/TitaniumKit/src/Module.cpp
Source/Utility/CMakeLists.txt
Source/Utility/include/TitaniumWindows/WindowsTiImpl.hpp

*PROOF OF CONCEPT*
[TIMOB-23439](https://jira.appcelerator.org/browse/TIMOB-23439)
Introduce new unified way to catch exception inspired by #715 
* `TITANIUM_EXCEPTION_CATCH_START` indicates you starts to catch the exception 
* `TITANIUM_EXCEPTION_CATCH_END` indicates you catches the exception and show "red screen of death". Used in TitaniumKit.
* `TITANIUMWINDOWS_EXCEPTION_CATCH_START` is Windows-specific version of `TITANIUM_EXCEPTION_CATCH_END`. It catches `Platform::COMException` and show "red screen of death" with exception detail. 
```c++
TITANIUM_EXCEPTION_CATCH_START {
throw ref new Platform::COMException(0, "TEST EXCEPTION");
}  TITANIUMWINDOWS_EXCEPTION_CATCH_END
```
In asyc functions, you need to use `concurrency::task` along with `concurrency::task::get()` to catch exception, …

PoC: [TIMOB-23439] Unified way to catch exception

---

Source/Map/include/TitaniumWindows/Map/View.hpp
Source/Map/src/Annotation.cpp
Source/Map/src/View.cpp
Source/TitaniumKit/src/Map/Annotation.cpp
Source/TitaniumKit/src/Map/View.cpp

[TIMOB-23343](https://jira.appcelerator.org/browse/TIMOB-23343)
Supported properties:
- latitude
- longitude
- map
- clicksource (`pin` when annotation is clicked,`null` otherwise)
- annotation (only when annotation is clicked)
- title (only when annotation is clicked)
- subtitle (only when annotation is clicked)
- type, source
```javascript
var win = Titanium.UI.createWindow();
var mountainView = Titanium.Map.createAnnotation({
latitude: 37.390749,
longitude: -122.081651,
title: "Previous Appcelerator HQ",
subtitle: 'Mountain View, CA',
pincolor: Titanium.Map.ANNOTATION_RED,
myid: 1 // Custom property to uniquely identify this annotation.
});
var mapview = Titanium.Map.createView({
mapType: Titanium.Map.STANDARD_TYPE,
region: {
latitude: 37.390749, longitude: -122.081651,
latitudeDelta: …
```

[TIMOB-23343] Fix: Map annotations do not handle click events

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[5_3_X] [TIMOB-23461](https://jira.appcelerator.org/browse/TIMOB-23461)
Fix: `Ti.UI.View` ignores `click` event. This issue has been introduced by [TIMOB-23374](https://jira.appcelerator.org/browse/TIMOB-23374).
*Test code*
```javascript
﻿var window = Ti.UI.createWindow({ backgroundColor: 'green' });
borderRadius: 5,
borderColor: 'orange',
borderWidth: 10,
width: '90%',
height: '90%',
});
text: "ABC",
color: "#C41230",
borderRadius: 30,
borderWidth: 2,
borderColor: "#C41230",
backgroundColor: "#F2D0D6",
textAlign: "center",
width: 100, height: 50
});
view.add(label);
label.addEventListener('click', function () {
Ti.API.info('Label clicked');
}); …
```

[5_3_X] [TIMOB-23461] Fix: Ti.UI.View ignores click event

---

Source/UI/src/Window.cpp

Per Fokke at [TIMOB-23366](https://jira.appcelerator.org/browse/TIMOB-23366?focusedCommentId=387171&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-387171)
Move warning message at `Windows.close` to internal. This log should have been kept internal because this does not mean actually a issue.

move Window log to internal

---

Source/TitaniumKit/include/Titanium/UI/Animation.hpp
Source/TitaniumKit/src/UI/Animation.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Add support for ``% cm mm cm em pt pc in px dp dip`` in ``width`` ``height`` ``top`` ``left`` (``bottom`` and ``right`` are not implemented)
- Fixed crash when animating ``width`` or ``height`` from ``0``
- Fixed ``width`` and ``height`` not being retained after animation
``Scale height from 0 to 100%``
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'black'}),
view = Ti.UI.createView({backgroundColor: 'red', top: 0, left: 0, width:'10%', height: 0}),
animation = Ti.UI.createAnimation({height: "100%", curve: Ti.UI.ANIMATION_CURVE_EASE_OUT, duration: 2000});
view.animate(animation);
win.add(view);
win.open();
```
``Scale width from 0 to 100%``
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'black'}),
view = Ti.UI.createView({backgroundColor: 'red', top: 0, …
```

[TIMOB-19351] Support unit values for Ti.UI.createAnimation()

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js

- ``ti.network.httpclient.test.js`` consistently fails on the build server
- However, the test passes locally on both my machine and device
- The test seems to timeout and never reaches the ``onload`` callback
- For now, I have skipped the test until it can be investigated further

Skip failing httpclient Ti.Blob test

---

Examples/NMocha/src/Assets/ti.network.test.js
Source/TitaniumKit/src/NetworkModule.cpp

- Implement ``Titanium.Network.networkTypeName`` property getter
```Javascript
Ti.API.info(Ti.Network.networkTypeName);
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23399)

[TIMOB-23399] Implement getter for Ti.Network.networkTypeName

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/LayoutEngine/src/Composite.cpp

[TIMOB-23225](https://jira.appcelerator.org/browse/TIMOB-23225)
```javascript
width: Ti.UI.SIZE,
backgroundColor: 'orange'
});
var img1 = Ti.UI.createView({
height: 100, width: Ti.UI.FILL,
backgroundColor:'gray'
});
var img2 = Ti.UI.createView({
height: 50, width: 50,
top: 0, right: 0,
});
view.add(img1);
view.add(img2);
win.add(view);
win.open();
```

[TIMOB-23225] Fix: wrong size for child view with Ti.UI.SIZE

---

Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

[TIMOB-23352](https://jira.appcelerator.org/browse/TIMOB-23352)
```javascript
var scrollView = Ti.UI.createScrollView({
});
scrollView.addEventListener('click', function (e) {
alert('e.source.apiName: ' + e.source.apiName + (e.source.id ? "\ne.source.id: " + e.source.id : ""));
});
scrollView.add(Ti.UI.createView({
width: 100,
height: 100,
backgroundGradient: {
type: 'linear',
startPoint: { x: '0%', y: '50%' },
endPoint: { x: '100%', y: '50%' },
colors: [{ color: 'red', offset: 0.0 }, { color: 'blue', offset: 0.25 }, { color: 'red', offset: 1.0 }],
},
id: 'my_scrollview_content'
}));
win.open();
```

[TIMOB-23352] ScrollView click should have actual view as source

---

Examples/NG/CMakeLists.txt
Examples/NG/src/Assets/WebViewIndexPage.htm
Examples/NG/src/Assets/WebViewNextPage.htm
Source/UI/include/TitaniumWindows/UI/WebView.hpp
Source/UI/src/WebView.cpp

[TIMOB-23503](https://jira.appcelerator.org/browse/TIMOB-23503)
Resources/app.js
```javascript
var view = Ti.UI.createView({backgroundColor:'blue'});
var webview = Ti.UI.createWebView({
url: 'WebViewTestPage.htm',
height: '80%',
bottom: 0
});
title: 'fromTitanium',
height: '10%',
top: 0, left: 0
});
Ti.App.fireEvent('app:fromTitanium', { message: 'event fired from Titanium, handled in WebView' });
});
Ti.App.addEventListener('app:fromWebView', function (e) {
alert(e.message);
});
view.add(webview);
view.add(button);
win.add(view);
win.open();
```
Resources/WebViewTestPage.htm
```html
<html>
<head>
<script> …
```

[TIMOB-23503] Fix: WebView local script doesn't work for hyperlink

---

Examples/NG/CMakeLists.txt

Remove wrong cmake link from ` Examples/NG/CMakeLists.txt `, seems like merged incorrectly in previous commit.

Remove missing asset from NG example

---

Source/Media/src/Media.cpp
Source/TitaniumKit/include/Titanium/Media/CameraMediaItemType.hpp
Source/TitaniumKit/src/Media/CameraMediaItemType.cpp

[TIMOB-23125](https://jira.appcelerator.org/browse/TIMOB-23125)
```javascript
var window = Ti.UI.createWindow({
exitOnClose: true,
});
var viewParent = Ti.UI.createView({
width: '60%',
height: '41%',
top: '1%'
});
var imageTaken = Ti.UI.createImageView({
height: Ti.UI.FILL,
});
var cameraImage = Ti.UI.createButton({
title: "Choose Photos",
bottom: '0%',
height: '20%',
font: {
fontSize: 15,
fontWeight: "bold"
},
});
viewParent.add(imageTaken);
viewParent.add(cameraImage);
window.add(viewParent);
cameraImage.addEventListener('click', function (e) {
Ti.Media.openPhotoGallery({
autoHide: true,
mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
success: function (e) {
if (e.mediaType === Ti.Media.MEDIA_TYPE_PHOTO) {
imageTaken.image = e.media;
}
},
cancel: function …
```

[5_4_X] [TIMOB-23125] Fix: Getting photo from photo gallery fails

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp

[TIMOB-23427](https://jira.appcelerator.org/browse/TIMOB-23427)
Show default camera UI when no `overlay` is specified. Note that _default camera UI won't be available for Windows Phone 8.1_.
```javascript
imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '80%' });
openButton.addEventListener('click', function () {
Ti.Media.showCamera({
mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
success: function (e) {
Ti.API.info('showCamera() success');
imageView.image = e.media;
},
alert('showCamera() error: ' + JSON.stringify(e));
}
});
});
win.add(openButton);
win.add(imageView);
win.open();
```
Default …

[TIMOB-23427] Default camera control for Windows 10 apps

---

Source/UI/include/TitaniumWindows/UI/Tab.hpp
Source/UI/src/Tab.cpp

[TIMOB-23531](https://jira.appcelerator.org/browse/TIMOB-23531)
* Try to get "default color" from current theme if no Tab title color is specified.
```javascript
// create tab group
var tabGroup = Titanium.UI.createTabGroup();
//
// create base UI tab and root window
//
title: 'Tab 1',
});
var tab1 = Titanium.UI.createTab({
title: 'Tab 1',
window: win1,
// titleColor: 'blue',
// activeColor: 'orange'
});
var label1 = Titanium.UI.createLabel({
color: '#999',
text: 'I am Window 1',
font: { fontSize: 20, fontFamily: 'Helvetica Neue' },
textAlign: 'center',
width: 'auto'
});
win1.add(label1);
//
// create controls tab and root window
//
var win2 = Titanium.UI.createWindow({
title: 'Tab 2',
});
var tab2 = …
```

[TIMOB-23531] Fix: Tab title color is not changed on selection

---

Examples/NG/CMakeLists.txt
Examples/NG/modules/commonjs/commonjs.legacy.package/1.0.0/commonjs.legacy.package.js
Examples/NG/modules/commonjs/commonjs.legacy.package/1.0.0/index.js
Examples/NG/modules/commonjs/commonjs.legacy.package/1.0.0/index.json
Examples/NG/modules/commonjs/commonjs.legacy.package/1.0.0/main.js
Examples/NG/modules/commonjs/commonjs.legacy.package/1.0.0/manifest
Examples/NG/modules/commonjs/commonjs.legacy.package/1.0.0/package.json
Examples/NG/src/Assets/require_test.js
Examples/NG/src/Assets/with_index_js/index.js
Examples/NG/src/Assets/with_index_js/index.json
Examples/NG/src/Assets/with_index_js/sub.js
Examples/NMocha/src/Assets/ti.require.test.js
Examples/NMocha/src/Assets/with_index_js/sub1.js
Examples/NMocha/src/Assets/with_index_js/sub2.js
Source/TitaniumKit/src/GlobalObject.cpp
Source/TitaniumKit/test/GlobalObjectTests.cpp

[TIMOB-23512](https://jira.appcelerator.org/browse/TIMOB-23512) and [TIMOB-23543](https://jira.appcelerator.org/browse/TIMOB-23543)
```javascript
var test = require('subdir/index');
should(test.filename).eql('/subdir/index.js');
should(test.name).eql('index.js');
should(test.sub).eql('sub.js');
```
```javascript
var sub = require('./sub')
module.exports = {
filename: __filename,
name: 'index.js',
sub: sub.name
};
```
```javascript
module.exports = {
name: 'sub.js',
};
```
Note: In  order to retrieve current file name from requiring object, I ended up adding new hidden variable `__TI_REQUIRED__` in global object, which is only available while evaluating required module. This is tricky but needed because `JSObject parent` in `GlobalObject::requestResolveModule(parent, moduleId)` is always …

[TIMOB-23512] [TIMOB-23543] Relative require() from sub-directory fails

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Source/TitaniumKit/src/UI/ImageView.cpp
Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp

[TIMOB-23560](https://jira.appcelerator.org/browse/TIMOB-23560)
```javascript
var images = [];
for (var i = 0; i < 31; i++) {
images.push('Roamler_app_loader_' + ( '0' + i ).slice( -2 ) + '.png');
}
var image = Ti.UI.createImageView({
images: images,
width: 75,
height: 75,
duration: 67
});
image.start();
});
win.add(image);
win.open();
```
Images: [loader.zip](https://jira.appcelerator.org/secure/attachment/59655/loader.zip)

[5_4_X] [TIMOB-23560] Fix: Setting images on ImageView will crash the app

---

Examples/NMocha/src/Assets/ti.require.test.js
Examples/NMocha/src/Assets/with_index_js/sub1.js
Examples/NMocha/src/Assets/with_index_js/sub3.js
Source/TitaniumKit/include/Titanium/GlobalObject.hpp
Source/TitaniumKit/src/GlobalObject.cpp

Follow-on to #750 
The common mocha suite was still broken because it had two relative requires in the same file. The use of the __TI_REQUIRED__ hack would only work for a single require because the property lived off the global, so after the first require it got removed and we lost state. It needed to be able to be dealt with recursively. I instead move it to a currentDir__ field on GlobalObject in the C++ code, mimicking what we do for iOS.
Note that this is a hack that works for now, but a real proper Node-style require implementation requires more than what we're doing now. They generate a Module object after the path is resolved holding the resolved filename and a pointer to the parent Module. They then generate a require function that is hooked within the context of that module. …

Fix another broken require case where multiple relative requires in same file failed.

---

Source/TitaniumKit/src/Module.cpp

- Update ``event_listener_map__`` in ``removeEventListener()``
```Javascript
var win = Titanium.UI.createWindow({backgroundColor: 'red'}),
img = Ti.UI.createImageView({image: 'Logo.png'});
function clickListener(e) {
alert("clicked");
img.removeEventListener('click', clickListener);
img.addEventListener('click', clickListener);
}
img.addEventListener('click', clickListener);
win.add(imgview);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23615)

[TIMOB-23615] removeEventListener() should update event_listener_map__

---

cli/commands/_buildModule.js

[TIMOB-23563](https://jira.appcelerator.org/browse/TIMOB-23563)
Suppress `possible EventEmitter memory leak detected` warnings from on packaging module by using [EventEmitter.defaultMaxListeners](https://nodejs.org/api/events.html#events_eventemitter_defaultmaxlisteners). I assume this is safe because these warnings are from Node.js Streams and they properly removes listeners on finish.

[TIMOB-23563] Suppress 'possible EventEmitter memory leak detected'

---

Examples/NMocha/src/Assets/ti.ui.view.test.js
Source/LayoutEngine/src/ParseProperty.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Fix ``Titanium.UI.animate()`` where ``right`` and ``bottom`` properties would not be retained after the animation
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' }),
top: 0,
left: 0,
height: '100',
width: '100'
});
view.animate(Ti.UI.createAnimation({
right: '50%',
bottom: '50%',
duration: 2000
}));
});
win.add(view);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23607)

[TIMOB-23607] Fix Ti.UI.animate() for right and bottom properties

---

cli/commands/_build/generate.js

Follow up on https://github.com/appcelerator/titanium_mobile_windows/pull/761#discussion_r69987108
Basically revert https://github.com/appcelerator/titanium_mobile_windows/pull/771/commits/c963430484aca4fa5e36ebcd1c2f3262cded8e5c to recover CI build asap.

generate capabilities only when none are defined in the tiapp.xml

---

cli/commands/_build/generate.js
cli/commands/_build/run.js

Force "en" instead of "en-US" for the default language.
```
> appc ti build -p windows --build-only
[WARN]  MakePRI : warning 0xdef00522: no resources found for default language(s): 'en-US'.
Change the default language or qualify resources with the default language.
http://go.microsoft.com/fwlink/?LinkId=231899
```
Introduced by #737.

Force "en" instead of "en-US" for the default language

---

cli/commands/_build/copy.js

- Amend missing icons directory to validate ``Resources\Windows`` folder
```
appc run -p windows --build-only
appc run -p windows --build-only
...
[INFO]  Missing 0 app icons, generating missing icons
...
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23575)

[TIMOB-23575] Amend missing icons directory

---

Source/TitaniumKit/include/Titanium/GlobalObject.hpp
Source/TitaniumKit/src/GlobalObject.cpp

Attempt to improve "require" performance & log.
- Cache require path search results
- Log nested require count for debug
The final resolved path for`GlobalObject::requestResolveModule` was not cached. It improves performance of `require` significantly when it is called multiple times (e.g. in the loop) with same name like below.
```javascript
for (var i = 0; i < 100; i++) {
var b = require('some_other_module');
}
```
I also add nested require count for debugging purpose. It is handy to check how deep `require` call is nested.
```
[DEBUG] - require(./app) from /
[DEBUG] -- require(./ti.require.test) from /
[DEBUG] --- require(./sub) from /with_index_js
```

Attempt to improve "require" performance

---

Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

- Implement ``TableView`` ``headerTitle`` ``headerView`` ``footerTitle`` and ``footerView`` functionality
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'orange' }),
sectionView = Ti.UI.createTableViewSection({
headerTitle: 'sectionView.headerTitle',
footerView: Ti.UI.createLabel({ text: 'sectionView.footerView' })
}),
tableView = Ti.UI.createTableView({
headerTitle: 'tableView.headerTitle',
footerView: Ti.UI.createLabel({ text: 'tableView.footerView' }),
data: [sectionView]
});
for (i = 0; i < 3; i++) sectionView.add(Ti.UI.createTableViewRow({ title: 'Row #' + i }));
tableView.addEventListener('click', function (e) {
Ti.API.info(e.sectionIndex + ' : ' + e.index);
});
win.add(tableView);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19962)

[TIMOB-19962] Fix TableView header and footer

---

Source/UI/src/TableView.cpp

- ``deleteSection`` should remove the section instead of removing the section rows
```Javascript
sections = [],
table = Ti.UI.createTableView(),
createSection = function (title) {
return section = Ti.UI.createTableViewSection({headerTitle: title});
}
for (var i = 0; i < 3; i++) {
sections[i] = createSection('Section #' + i);
}
table.data = sections;
table.deleteSection(1);
table.updateSection(1, createSection('Section #1'));
win.open();
```
```
Section #0
Section #1
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23639)

[TIMOB-23639] Fix Ti.UI.TableView.deleteSection()

---

Source/TitaniumKit/src/UI/ListSection.cpp
Source/UI/src/ListView.cpp

- Fix ``Titanium.UI.ListSection.insertItemsAt()`` to ``insert`` and not ``append`` items
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'orange'}),
list = Ti.UI.createListView(),
items = [];
for (var i = 1; i < 3; i++) {
items.push({properties: {title: 'Item #'+i}});
}
list.sections = [Ti.UI.createListSection({ items: items })];
list.sections[0].insertItemsAt(0, [{properties: {title: 'Item #0'}}]);
win.add(list);
win.open();
```
```
Item #0
Item #1
Item #2
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23641)

[TIMOB-23641] Fix Ti.UI.ListSection.insertItemsAt()

---

Examples/NMocha/src/Assets/ti.ui.view.test.js
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Retain ``opacity`` after animation
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'red'}),
img = Ti.UI.createImageView({image: 'Logo.png', opacity: 0.1}),
ani = Ti.UI.createAnimation({opacity: 1, duration: 3000});
win.add(img);
img.animate(ani);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23653)

[TIMOB-23653] Retain opacity after animation

---

Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

- Add a ``parent__`` for ``tableview__`` allowing ``borderRadius`` to work correctly
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'red'}),
tableView = Ti.UI.createTableView({
borderWidth: 5,
borderColor: 'yellow',
borderRadius: 5,
data: [{title: 'Apples'}, {title: 'Bananas'}, {title: 'Carrots'}, {title: 'Potatoes'}]
});
win.add(tableView);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23329)

[TIMOB-23329] Fix Titanium.UI.TableView.borderRadius property

---

Examples/NMocha/src/Assets/ti.ui.label.test.js
Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Label.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- ``Windows::UI::Xaml::Controls::Border^`` can be used as a parent for components, offering border controls over ``Windows::UI::Xaml::Controls::Grid^``
- Use ``Border`` as a parent for ``Label`` allowing ``Titanium.UI.Label.border*`` properties to function correctly
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'red' }),
lbl = Ti.UI.createLabel({
borderWidth: 5,
borderColor: 'yellow',
borderRadius: 5,
text: 'TEST TEXT'
});
win.add(lbl);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23658)

[TIMOB-23658] Fix Ti.UI.Label.border* properties

---

Source/Sensors/include/TitaniumWindows/Geolocation.hpp
Source/Sensors/src/Geolocation.cpp
Source/TitaniumKit/include/Titanium/GeolocationModule.hpp
Source/TitaniumKit/src/GeolocationModule.cpp

- Implement ``requestLocationPermissions()`` and ``hasLocationPermissions`` for ``Titanium.Geolocation``
```Javascript
btn_a = Ti.UI.createButton({top: '33%', title:'hasLocationPermissions()'}),
btn_b = Ti.UI.createButton({top: '66%', title:'requestLocationPermissions()'});
btn_a.addEventListener('click', function () {
alert('hasLocationPermissions() : ' + Ti.Geolocation.hasLocationPermissions(null));
});
btn_b.addEventListener('click', function () {
Ti.Geolocation.requestLocationPermissions(null, function (res) {
alert(JSON.stringify(res, null, ' '));
});
});
win.add(btn_a);
win.add(btn_b);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23655)

[TIMOB-23655] Implement Ti.Geolocation requestLocationPermissions() and hasLocationPermissions()

---

Source/Utility/CMakeLists.txt

- Disable inline function expansion optimisation for `TitaniumWindows_Utility`
- Prevents Visual Studio Update 3 Release mode internal compile error

Prevent Release mode C1001 error on Visual Studio Update 3

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp
Source/TitaniumKit/include/Titanium/MediaModule.hpp
Source/TitaniumKit/src/MediaModule.cpp

- Implement ``requestCameraPermissions()`` and ``hasCameraPermissions`` for ``Titanium.Media``
```Javascript
btn_a = Ti.UI.createButton({top: '33%', title:'hasCameraPermissions()'}),
btn_b = Ti.UI.createButton({top: '66%', title:'requestCameraPermissions()'});
btn_a.addEventListener('click', function () {
alert('hasCameraPermissions() : ' + Ti.Media.hasCameraPermissions());
});
btn_b.addEventListener('click', function () {
Ti.Media.requestCameraPermissions(function (res) {
alert(JSON.stringify(res, null, ' '));
});
});
win.add(btn_a);
win.add(btn_b);
win.open();
```
- ``webcam`` capability must be present in ``tiapp.xml``
- ``requestLocationPermissions()`` is unsupported on both Windows 8.1 and 10
[JIRA …

[TIMOB-23656] Implement Ti.Media requestCameraPermissions() and hasCameraPermissions()

---

Tools/Scripts/setup.js

Make sure to check if `SOURCE_FILE` exists before reading its contents.
```
21:02:24 C:\Jenkins\workspace\titanium_mobile_windows_10_prs\Tools\Scripts>call npm install . 
21:02:26 npm WARN package.json windowssdksetup@0.0.1 license should be a valid SPDX license expression
21:02:26 Installing JSC built for Windows 10
21:02:26 Setting up Boost libraries...
21:02:26 [32mâˆš BOOST_ROOT set[39m
21:02:26 Setting up GTest...
21:02:26 [32mâˆš GTEST_ROOT set[39m
21:02:26 Setting up JavaScriptCore pre-built libraries...
21:02:26 Downloading [36mhttp://timobile.appcelerator.com.s3.amazonaws.com/jscore/JavaScriptCore-Windows-1469754731-win10.zip[39m
21:02:54 fs.js:549
21:02:54   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
21:02:54                  ^
21:02:54 …
```

Attempt to fix Win10 Jenkins build

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp
Source/TitaniumKit/include/Titanium/Media/CameraOptionsType.hpp
Source/TitaniumKit/src/Media/CameraOptionsType.cpp

- Always use default camera of the device or rear camera if a default is not specified
- Implemented ``CameraOptionsType.whichCamera`` to specify either front or rear camera to use
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'green', layout: 'vertical'}),
imageView = Ti.UI.createImageView({width: Ti.UI.FILL, height: '70%'});
Ti.Media.showCamera({
whichCamera: Titanium.Media.CAMERA_FRONT, // Titanium.Media.CAMERA_REAR
mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO],
overlay: Ti.UI.createView(), // dont use Windows capture UI
success: function (e) {
imageView.image = e.media;
},
alert('showCamera() error: ' + JSON.stringify(e));
}
});
win.add(imageView);
win.open();
```
[TIMOB-23687](https://jira.appcelerator.org/browse/TIMOB-23687) …

[TIMOB-23686][TIMOB-23687] Fix default camera, implement CameraOptionsType.whichCamera

---

Source/Ti/include/TitaniumWindows/AppModule.hpp
Source/Ti/src/AppModule.cpp
Source/TitaniumKit/include/Titanium/GlobalObject.hpp
Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/src/App.cpp
Source/TitaniumKit/src/GlobalObject.cpp
Source/TitaniumKit/src/UI/Window.cpp
Source/UI/include/TitaniumWindows/UI/Window.hpp
Source/UI/src/Window.cpp

Take over #794
- Remove `_restart()` from `TitaniumWindows_Ti`
- Implement `Ti.App._restart()` in `TitaniumKit`
Note: This implementation is simple, but good enough for now I think.
This does not actually reset all application state but
- Close all existing `Window` but do not exit the app
- After all `Window` is closed, then reload the app using `require('app')`
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' }),
btn = Ti.UI.createButton({ title: 'Ti.App._restart()' });
win.backgroundColor = 'red';
}, 2000);
Ti.App._restart();
});
win.add(btn);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23696)

[TIMOB-23696] Fix Ti.App._restart() functionality

---

Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp

- Queue up `toImage` calls before an image is loaded
- Currently the windows `toImage` method only supports retrieving a `Blob` from the callback
```Javascript
img = Ti.UI.createImageView({image: 'Logo.png'});
img.toImage(function (blob) {
Ti.API.info('success');
});
win.add(img);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23717)

[TIMOB-23717] Execute Ti.UI.ImageView.toImage() only after an image has loaded

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/804
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23723)

[5_4_X][TIMOB-23723] Top and bottom, left and right should not override a set width and height

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

- When `top`, `bottom` and `height` or `left`, `right` and `width` are set. The `height` or `width` should have priority
```Javascript
img = Ti.UI.createImageView({
image: 'Logo.png',
left: 0,
top: 0,
bottom: 0,
width: Ti.UI.SIZE,
height: Ti.UI.SIZE
});
win.add(img);
win.open();
```
```
Image should be visible
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23723)

[TIMOB-23723] Top and bottom, left and right should not override a set width and height

---

Source/UI/src/ListView.cpp

- Fix `fireListSectionEvent()` index calculation when `ListSection` has no header
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' }),
section = Ti.UI.createListSection({
items: [
{ properties: { title: '0: A' } },
{ properties: { title: '1: A' } },
{ properties: { title: '2: C' } },
{ properties: { title: '3: D' } }
]
}),
listView = Ti.UI.createListView({ sections: [section] });
listView.addEventListener('click', function (e) {
section.updateItemAt(1, { properties: { title: '1: B' } });
});
win.add(listView);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23734)

[TIMOB-23734] Fix ListSection events index when without a header

---

Source/Network/src/HTTPClient.cpp
Source/TitaniumKit/include/Titanium/Network/HTTPClient.hpp

#791 + Workaround for Windows 10 desktop. We've been seeing intermittent crash on Windows 10 desktop with async HTTPClient.

[TIMOB-23678] Fix Ti.Network.HTTPClient.send() concurrency

---

cli/commands/_build/config/target.js

- Default to `10.0` otherwise default to `8.1` if not on Windows 10
```
appc run -p windows -T wp-local
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23683)

[TIMOB-23683] Select appropriate wp-sdk for platform when targeting ws-local

---

Examples/NMocha/src/Assets/ti.ui.listview.test.js
Source/TitaniumKit/src/UI/ListSection.cpp
Source/UI/src/ListView.cpp

- Fixed `fireListSectionEvent()` handling of `ListView` item indexes
- Fixed `Titanium.ListSection.deleteItemsAt()` erasing items before unregistering the layout node
- Added test cases to test all events of `fireListSectionEvent()` with and without a header and footer
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' }),
section = Ti.UI.createListSection({
//headerTitle: 'HEADER',
//footerTitle: 'FOOTER',
items: [
{ properties: { title: 'B' } },
{ properties: { title: 'A' } },
{ properties: { title: 'E' } },
{ properties: { title: 'G' } }
]
}),
listView = Ti.UI.createListView({ sections: [section] }),
items_a = [
{ properties: { title: 'A' } },
],
items_b = [
{ properties: { title: 'C' } },
{ properties: { title: 'D' } }
],
items_c = [
{ properties: { title: 'E' } },
{ …
```

[TIMOB-23734] Fix ListView fireListSectionEvent()

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.network.socket.tcp.test.js
Source/Network/CMakeLists.txt
Source/Network/include/TitaniumWindows/Network/Socket/TCP.hpp
Source/Network/src/Socket/TCP.cpp
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/Network/Socket/TCP.hpp
Source/TitaniumKit/include/Titanium/Network/Socket/UDP.hpp
Source/TitaniumKit/src/Network/Socket/TCP.cpp
Source/TitaniumKit/src/Network/Socket/UDP.cpp

- Set `Titanium::Network::Socket` `TCP` and `UDP` to inherit `IOSocket`
- Implemented `Titanium.Network.Socket.TCP` functionality
```Javascript
var socket = Ti.Network.Socket.createTCP({
host: 'pastebin.com', port: 80,
connected: function (e) {
Ti.API.info('socket connected');
// receive callback
Ti.Stream.pump(e.socket, function (e) {
alert(e.buffer.toString());
}, 1024, true);
// send GET request
Ti.Stream.write(socket, Ti.createBuffer({
value: 'GET /raw/eF5dK0xU HTTP/1.1\r\nHost: pastebin.com\r\nConnection: close\r\n\r\n'
}), function (e) {
Ti.API.info('socket sent GET');
});
}
});
socket.connect();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-19935)

[TIMOB-19935] Implement Titanium.Network.Socket.TCP

---

Examples/NG/CMakeLists.txt
Examples/NMocha/CMakeLists.txt
cli/commands/_build/config/deviceID.js
cli/commands/_build/config/wpSDK.js
cli/commands/_build/generate.js
cli/commands/_build/run.js
templates/build/CMakeLists.txt.ejs
templates/build/Native/CMakeLists.txt.ejs
templates/build/cmake/FindHAL.cmake
templates/build/cmake/FindLayoutEngine.cmake
templates/build/cmake/FindNativeModule.cmake.ejs
templates/build/cmake/FindTitaniumKit.cmake
templates/build/cmake/FindTitaniumWindows.cmake
templates/build/cmake/FindTitaniumWindows_Filesystem.cmake
templates/build/cmake/FindTitaniumWindows_Global.cmake
templates/build/cmake/FindTitaniumWindows_Map.cmake
templates/build/cmake/FindTitaniumWindows_Media.cmake
templates/build/cmake/FindTitaniumWindows_Network.cmake
templates/build/cmake/FindTitaniumWindows_Sensors.cmake
templates/build/cmake/FindTitaniumWindows_Ti.cmake
templates/build/cmake/FindTitaniumWindows_UI.cmake
templates/build/cmake/FindTitaniumWindows_Utility.cmake

Note: ~~This needs [windowslib 0.4.17](https://github.com/appcelerator/windowslib/pull/52) merged for [titanium_mobile](https://github.com/appcelerator/titanium_mobile)~~ -> *Merged*.
[TIMOB-23760](https://jira.appcelerator.org/browse/TIMOB-23760)
[TIMOB-23758](https://jira.appcelerator.org/browse/TIMOB-23758)
[TIMOB-23759](https://jira.appcelerator.org/browse/TIMOB-23759)
```
appc run -p windows --wp-sdk 10.0.10586.0 --target wp-device -l trace
```

[TIMOB-23760] --wp-sdk option should handle actual Windows SDK versions

---

cli/commands/_build/compile.js

- Provide a clear indication of the Windows SDK being used to build the project
```
appc run -p windows -S 10.0 -- build-only
```
```
[INFO]  Targeting Windows SDK: 10.0
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23370)

[TIMOB-23370] Log target Windows SDK

---

Examples/NMocha/src/Assets/ti.blob.test.js
Examples/NMocha/src/Assets/ti.geolocation.test.js
Examples/NMocha/src/Assets/ti.network.httpclient.test.js
Examples/NMocha/src/Assets/ti.ui.button.test.js
Examples/NMocha/src/Assets/ti.ui.label.test.js
Examples/NMocha/src/Assets/ti.ui.layout.test.js
Examples/NMocha/src/Assets/ti.ui.listview.test.js
Examples/NMocha/src/Assets/ti.ui.tableview.test.js
Examples/NMocha/src/Assets/ti.ui.textfield.test.js
Examples/NMocha/src/Assets/ti.ui.view.test.js
Examples/NMocha/src/Assets/ti.ui.window.test.js
Source/TitaniumKit/src/Analytics.cpp

We've been learning that use of `focus` event to trigger `finish` callback on `NMocha` tests does not actually work well on desktop environment. Avoid use of it when possible.

[TIMOB-23776] Avoid use of 'focus' event on mocha

---

Examples/NMocha/src/Assets/app.js

Investigate failing mocha tests on Jenkins
[TIMOB-23776](https://jira.appcelerator.org/browse/TIMOB-23776)
Skip UI tests on Windows 8.1 desktop to make nightly build pass.

Skip UI tests temporary on Windows 8.1 desktop

---

Examples/NMocha/src/Assets/app.js
Examples/NMocha/src/Assets/ti.geolocation.test.js

Skip reverse/forward geocoder on desktop because of intermittent network issue

[6_0_X] Skip reverse/forward geocoder on desktop 

---

Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

- Implement `Titanium.UI.TableView.separatorColor` property
- Windows `ListView` does not natively support an item divider
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'green'}),
tableView = Ti.UI.createTableView({
data: [
{title: 'A'},
{title: 'B'},
{title: 'C'},
{title: 'D'}
],
separatorColor: 'red'
});
tableView.addEventListener('click', function (e) {
tableView.separatorColor = 'blue';
});
win.add(tableView);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23660)

[TIMOB-23660] Implement Ti.UI.TableView separatorColor

---

Source/UI/include/TitaniumWindows/UI/ProgressBar.hpp
Source/UI/src/ProgressBar.cpp

[TIMOB-23682](https://jira.appcelerator.org/browse/TIMOB-23682)
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'purple' }),
progressBar = Ti.UI.createProgressBar({
borderWidth: 5,
borderColor: 'yellow',
borderRadius: 5,
min: 0,
max: 10,
value: 5,
message: 'Downloading 5 of 10',
});
win.add(progressBar)
win.open();
```
Side note: On iOS, `borderRadius` doesn't work well for `ProgressBar`

[TIMOB-23682] borderRadius for ProgressBar

---

Source/TitaniumKit/src/UI/ListSection.cpp

- Display warnings for out of range index when using `ListSection` functions
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'blue' }),
section = Ti.UI.createListSection({
items: [
{ properties: { title: 'A' } },
{ properties: { title: 'B' } },
{ properties: { title: 'C' } },
{ properties: { title: 'D' } }
]
}),
listView = Ti.UI.createListView({ sections: [section] });
section.updateItemAt(4, { properties: { title: 'E' } });
win.add(listView);
win.open();
```
```
[WARN] ListView::updateItemAt() index is out of range
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23785)

[TIMOB-23785] Log warnings for out of range index in ListSection

---

Source/Network/src/HTTPClient.cpp
Tools/Scripts/setup.js

[TIMOB-23752](https://jira.appcelerator.org/browse/TIMOB-23752)
Async HTTPClient introduced crash at NMocha test on Windows 10 Desktop. Reducing temporary memory for JavaScriptCore seems to be fixing this.

[TIMOB-23752] Async HTTPClient crashes on Win10 Desktop

---

Source/TitaniumKit/src/UI/AttributedString.cpp
apidoc/whitelist.txt

- Fix missing `Titanium.UI.AttributedString`
- Whitelist `Titanium.UI.ListItem`
NOTE: Do we need to include all `Module.Cloud` entries? [Parity Report](http://builds.appcelerator.com/mobile/master/mobilesdk-6.1.0.v20160831204323-parity.html)
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23728)

[TIMOB-23728] Fix missing parity report entries

---

Examples/NMocha/src/Assets/app.js
Source/Global/src/GlobalObject.cpp
Source/TitaniumKit/include/Titanium/GlobalObject.hpp
Source/TitaniumKit/src/GlobalObject.cpp
Tools/Scripts/setup.js

Part of [TIMOB-23776](https://jira.appcelerator.org/browse/TIMOB-23776)
- Avoid use of JSObject for storing Timer callback because it is heavy weight operation with few benefits. Trying to see how it works on Jenkins.
- Avoid using `0` interval for `setTimeout`. It intermittently freezes `DispatcherTimer`.
- Update JavaScriptCore, it fixes the intermittent crash issue on Windows 10. We are able to re-enable failing UI tests too. 👍 
Note that it does not fix the issue on Windows 8.1. It's because Windows 8.1 and Windows Phone 8.1 is missing required function ([GetThreadContext](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679362(v=vs.85).aspx)) and currently I don't have a workaround for it.

Test: Avoid use of JSObject for storing Timer callback

---

cli/commands/_build/compile.js
cli/commands/_build/config.js

- Only detect devices when targeting a windows device
- Saves time when building for `ws-local` or `--build-only`
- Remove unnecessary `windowslib.detect()`
- https://github.com/appcelerator/windowslib/pull/56
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23834)

[TIMOB-23834] Optimize windowslib usage

---

cli/commands/_build/generate.js

- Fixes for auto-capability generation need backporting to `6_0_X`
- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/842, https://github.com/appcelerator/titanium_mobile_windows/pull/840, https://github.com/appcelerator/titanium_mobile_windows/pull/853
[TIMOB-23156](https://jira.appcelerator.org/browse/TIMOB-23156)
[TIMOB-23869](https://jira.appcelerator.org/browse/TIMOB-23869)

[6_0_X][TIMOB-23156] Auto-generate capabilities

---

Examples/NMocha/src/Assets/app.js

Currently Win 8.1 Jenkins build is failing due to crash at JavaScriptCore. I'm pretty convinced why (see comments in [TIMOB-23776](https://jira.appcelerator.org/browse/TIMOB-23776)). Since we don't have a "right" fix for it, we don't want nightly build blocked because of it.

[6_0_X] Make nightly build pass

---

Examples/NMocha/src/Assets/app.js
Source/Global/src/GlobalObject.cpp
Source/TitaniumKit/include/Titanium/GlobalObject.hpp
Source/TitaniumKit/src/GlobalObject.cpp
Tools/Scripts/setup.js

Part of [TIMOB-23776](https://jira.appcelerator.org/browse/TIMOB-23776)
Pushing this to 6_0_X because it's critical.
- Avoid use of JSObject for storing Timer callback because it is heavy weight operation with few benefits. Trying to see how it works on Jenkins.
- Avoid using 0 interval for setTimeout. It intermittently freezes DispatcherTimer.
- Update JavaScriptCore, it fixes the intermittent crash issue on Windows 10. We are able to re-enable failing UI tests too.
- Update HAL

[6_0_X] Update JavaScriptCore and HAL

---

cli/commands/_build/utils.js
cli/lib/info.js

[TIMOB-23371](https://jira.appcelerator.org/browse/TIMOB-23371)
**Steps to reproduce**
1. Connect no devie
2. `appc ti info -p windows -o json`
**Expected**
Placeholder device (see below) should not be shown
```
{
"name": "Device",
"udid": 0,
"index": 0,
"wpsdk": null
},
```
1. Connect multiple devices
2. Build using appc run -p windows -T wp-device
**Expected**
Placeholder deivce `   1)  Device                    (udid: 0)` should not be shown
The reason because we still let `windowslib` outputs empty placeholder device is to keep backward compatibility as a library. (See discussions in https://github.com/appcelerator/windowslib/pull/49)

[6_0_X] [TIMOB-23371] Only report a device when one has been detected

---

Examples/NMocha/src/Assets/ti.network.httpclient.test.js

[TIMOB-23874](https://jira.appcelerator.org/browse/TIMOB-23874)
Unskip `POST multipart/form-data containing Ti.Blob` test now that [TIMOB-23575](https://jira.appcelerator.org/browse/TIMOB-23575) is fixed.

[TIMOB-23874] unskip httpclient POST multipart Blob test

---

Examples/NMocha/src/Assets/ti.require.test.js
Examples/NMocha/src/Assets/with_index_js/sub1.js
Source/TitaniumKit/src/GlobalObject.cpp

[TIMOB-23875](https://jira.appcelerator.org/browse/TIMOB-23875)
app.js
```javascript
var test = require('./index');
console.log(test.filename);
```
index.js
```javascript
var sub = require('./sub');
module.exports = {
filename: __filename,
name: 'index.js',
sub: sub.name
};
```
sub.js
```javascript
module.exports = {
name: 'sub.js',
};
```

[6_0_X] [TIMOB-23875] __filename should not be messed with nested require

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp

[TIMOB-23870](https://jira.appcelerator.org/browse/TIMOB-23870)
Stop firing `onerror` callback on tap-to-focus when camera does not support focus operation.
```javascript
imageView = Ti.UI.createImageView({ width: Ti.UI.FILL, height: '70%' });
var overlay = Ti.UI.createView({
height: '20%', width: Ti.UI.FILL,
bottom: 0
}),
hideButton = Ti.UI.createButton({ title: 'HIDE PREVIEW', backgroundColor: 'red' });
});
hideButton.addEventListener('click', …
```

[TIMOB-23870] Don't fire onerror callback on tap-to-focus

---

Source/Media/include/TitaniumWindows/Media.hpp
Source/Media/src/Media.cpp

[6_0_X] [TIMOB-23870] Don't fire onerror callback on tap-to-focus

---

cli/commands/_build/config.js
cli/lib/info.js

Related to [TIMOB-23661](https://jira.appcelerator.org/browse/TIMOB-23661)
This needs https://github.com/appcelerator/windowslib/pull/57 to be merged and bumped into https://github.com/appcelerator/titanium_mobile .
*windows.wpsdk.selectedVersion*
1. `appc ti info -p windows -json` and see which Windows Phone SDK is marked `selected`
2. `appc ti config windows.wpsdk.selectedVersion 10.0` 
3. `appc ti info -p windows -json` and see if Windows 10.0 Phone SDK is marked `selected`
*windows.sdk.selectedVersion*
1. `appc ti info -p windows -json` and see which Windows SDK is marked `selected`
2. `appc ti config windows.sdk.selectedVersion 10.0` 
3. `appc ti info -p windows -json` and see if Windows 10.0 SDK is marked `selected`

Add config option to specify preferred Windows SDK

---

cli/commands/_build/config/deviceID.js
cli/commands/_buildModule.js

[TIMOB-23895](https://jira.appcelerator.org/browse/TIMOB-23895)
[TIMOB-23878](https://jira.appcelerator.org/browse/TIMOB-23878)
When target equals `wp-device` and no devices are connected,
- `--wpsdk 8.1` ... `Unable to find any devices. Please plug in an Windows Phone device, then try again.`
- `--wpsdk 10.0` ...  `Unable to find any devices. Please plug in an Windows 10 Mobile device, then try again.`
When building module,
- Log confirmation of all of the architectures being built rather than just the ones being skipped
- Log the architectures in an easier to understand format, such as `Building <solution> for Windows10.ARM Release`
- If the timodule specifies a certain SDK version, log information regarding that such as `targetSdkVersion: 10.0.10586.0`
- Log the zip location so a user …

TIMOB-23895 TIMOB-23878 Improve CLI log message

---

Source/TitaniumKit/src/analytics.js

[TIMOB-23965](https://jira.appcelerator.org/browse/TIMOB-23965)
Exclude `eventName` property from feature event validation.

[TIMOB-23965] Add eventName after feature event validation

---

Source/UI/src/ScrollView.cpp

[TIMOB-23930](https://jira.appcelerator.org/browse/TIMOB-23930)
ScrollView content should `FILL` the ScrollView view, but it should extend its size when child components needs larger size.
```javascript
});
function createRow(i) {
var row = Ti.UI.createView({
borderColor: '#bbb',
borderWidth: 1,
width: '100%', height: 70,
top: 0, left: 0
});
var inputTextField = Ti.UI.createTextField({
hintText: 'Enter value ' + i,
keyboardType: Ti.UI.KEYBOARD_NUMBERS_PUNCTUATION,
top: 10, left: '10%',
width: '80%', height: 60
});
row.add(inputTextField);
return row;
}
var scrollView = Ti.UI.createScrollView({
bottom: 120,
});
for (var i = 0; i <= 20; i++) {
var row = createRow(i);
scrollView.add(row);
} …
```

[TIMOB-23930] ScrollView content size should be SIZE

---

Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/src/Module.cpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp
apidoc/Titanium/UI/TableView.yml

[TIMOB-23998](https://jira.appcelerator.org/browse/TIMOB-23998)
Note that some callback properties are not available on Windows due to platform component spec.
- `scroll` callback supports `type`, `source`, `size` and `totalItemCount` property
- `scrollend` callback supports `type`, `source`  and `size` property
```javascript
var tableData = [];
var data = [{ title: 'Apples' }, { title: 'Bananas' }, { title: 'Carrots' }, { title: 'Potatoes' }];
for (var i = 0; i < 5; i++) {
for (var j = 0; j < data.length; j++) {
tableData.push(data[j]);
}
}
data: tableData
});
table.addEventListener('scroll', function (e) {
Ti.API.info('---- ' + e.type + '----');
Ti.API.info(JSON.stringify(e.size)); …
```

[TIMOB-23998] Implement TableView scroll/scrollend event

---

Examples/NMocha/src/Assets/ti.ui.listview.test.js
Examples/NMocha/src/Assets/ti.ui.searchbar.test.js
Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/TitaniumKit/include/Titanium/UI/TableViewSection.hpp
Source/TitaniumKit/src/UI/ListView.cpp
Source/UI/src/ListView.cpp

[TIMOB-24019](https://jira.appcelerator.org/browse/TIMOB-24019)
- `ListView` `sections` and `sectionCount` should keep its original data even when it's filtered
- `ListView` `itemclick` event should return "original" position even when it's filtered
For instance when you search "p" on following app and then click on the second item (`Potatoes`), it should return its original position (`sectionIndex=1`, `itemIndex=1`).
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green', layout: 'vertical' });
var searchText = Ti.UI.createTextField({ width: Ti.UI.FILL, height: '10%' });
var listView = Ti.UI.createListView({ width: Ti.UI.FILL, height: '90%', caseInsensitiveSearch: true });
var fruitSection = Ti.UI.createListSection({ …
```

[6_0_X] [TIMOB-24019] ListView should keep "original" data even when filtered

---

Examples/NMocha/src/Assets/ti.ui.imageview.test.js
Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/src/ScrollView.cpp

Reopened ticket: [TIMOB-23930](https://jira.appcelerator.org/browse/TIMOB-23930)
Setting `Ti.UI.FILL` explicitly to `ScrollView` should keep showing entire content.
```javascript
scrollView = Ti.UI.createScrollView({
layout: "vertical",
width: Ti.UI.FILL, height: Ti.UI.FILL,
});
function createRow(i) {
var row = Ti.UI.createView({
borderColor: '#bbb',
top: 10,
left: 10,
width: Ti.UI.SIZE
});
var inputTextField = Ti.UI.createTextField({
hintText: 'Enter value ' + i,
keyboardType: Ti.UI.KEYBOARD_NUMBERS_PUNCTUATION
});
row.add(inputTextField);
return row;
}
for (var i = 0; i <= 20; i++) {
var row = createRow(i);
scrollView.add(row);
}
win.open();
```
Also need to ensure …

[6_0_X] [TIMOB-23930] Reopened: Setting FILL for ScrollView should show all content

---

Source/TitaniumKit/src/analytics.js

[TIMOB-23952](https://jira.appcelerator.org/browse/TIMOB-23952)
`Ti.Analytics.featureEvent` should be able to send `undefined` data. Basically reverts what we have done in #875

[TIMOB-23952] Analytics.featureEvent should be able to send undefined

---

Examples/NMocha/src/Assets/ti.geolocation.test.js
Examples/NMocha/src/Assets/ti.ui.view.test.js
Examples/NMocha/src/Assets/utilities/utilities.js

Cherry-pick #892 for 6_0_X. Just meant to make 6_0_X build stable on Win10 Desktop.
* Skip geolocation tests because it may be blocking other tests due to permission dialog
* Skip animation tests on Win10 desktop

[6_0_X] Skip geolocation tests on Desktop (#892)

---

Source/UI/src/Window.cpp

[TIMOB-24103](https://jira.appcelerator.org/browse/TIMOB-24103)
```javascript
var win = Ti.UI.createWindow({ backgroundColor: 'green'});
var win2 = Ti.UI.createWindow({ backgroundColor: 'pink'});
var tabGroup = Ti.UI.createTabGroup();
var acceptanceTab = Titanium.UI.createTab({
title : 'Acceptance',
window : win
});
var aboutTab = Titanium.UI.createTab({
title : 'About'
});
tabGroup.addTab(acceptanceTab);
tabGroup.addTab(aboutTab);
var tableData = [ {title: 'Apples'}, {title: 'Bananas'}, {title: 'Carrots'}, {title: 'Potatoes'} ];
data: tableData
});
table.addEventListener('click', function(){
win2.open();
});
tabGroup.open();
```

[TIMOB-24103] TabGroup disappears on closing new Window

---

Source/UI/src/ScrollView.cpp
apidoc/Titanium/UI/ScrollView.yml

[TIMOB-24088](https://jira.appcelerator.org/browse/TIMOB-24088)
- `x` and `y` properties are missing in `ScrollView.scroll` event.
```js
var scrollView = Ti.UI.createScrollView({
showVerticalScrollIndicator: true,
showHorizontalScrollIndicator: true,
height: '80%',
width: '80%'
});
backgroundColor: '#336699',
borderRadius: 10,
top: 10,
height: 2000,
width: 1000
});
scrollView.add(view);
var offset_half = view.height * 0.5;
scrollView.addEventListener('scroll', function (e) {
Ti.API.info('x=' + e.x + ' y=' + e.y);
// let's change view color when 50% of the view is scrolled
if (e.y > offset_half) {
view.backgroundColor = 'blue';
}
});
win.open();
```

[TIMOB-24088] Missing coordinates for ScrollView.scroll

---

cli/commands/_build/copy.js
cli/lib/stub.js
templates/build/Native/src/RequireHook.cpp.ejs
templates/build/TitaniumWindows_Hyperloop/src/TypeHelper.cs.ejs

Fixes for Hyperloop.
- Fix compile error when you have multiple native `require` and events with same name
- Add some more builtin number types
```javascript
require('Windows.UI.Xaml.Input.TappedRoutedEventArgs');
require('Windows.UI.Xaml.Input.TappedRoutedEventArgs');
Button = require('Windows.UI.Xaml.Controls.Button'),
button = new Button();
button.Content = "PUSH";
button.addEventListener('Tapped', function (e) {
alert('Tapped');
});
button.addEventListener('Tapped', function (e) {
Ti.API.info('This should not cause compile error');
});
win.open();
```

Check duplication for native events and types

---

Source/TitaniumKit/include/Titanium/MediaModule.hpp
Source/TitaniumKit/src/MediaModule.cpp

[TIMOB-20544](https://jira.appcelerator.org/browse/TIMOB-20544)
- This defines `Ti.Media.requestRecorderPermission()` as alias of `Ti.Media.requestAuthorization()`
- On Windows, `requestRecorderPermission` basically does nothing because there's no equivalent function in WinRT and recorder permission should be defined in `tiapp.xml` instead.
```js
// Should show "function"
alert(typeof Ti.Media.requestRecorderPermission);
```

[TIMOB-20544] Align method name for Ti.Media.AudioRecorder

---

Source/TitaniumKit/include/Titanium/UI/View.hpp
Source/TitaniumKit/src/UI/View.cpp

[TIMOB-20286](https://jira.appcelerator.org/browse/TIMOB-20286)
Expose `Ti.UI.View.getViewById` to find a child view by its `id`
Basically based on a logic done in https://github.com/appcelerator/titanium_mobile/pull/8677
```js
});
var container = Ti.UI.createView({
width: 300,
height: 300,
});
var btn = Ti.UI.createButton({
title: 'Get view by ID',
id: 'myButton'
});
var myButton = win.getViewById('myButton');
// If no button is found, it will return null
if (myButton) {
myButton.setTitle('Worked! ');
}
});
container.add(btn);
win.add(container);
win.open();
```

[TIMOB-20286] Expose Ti.UI.View.getViewById method

---

cli/commands/_build/config.js

[JIRA](https://jira.appcelerator.org/browse/TIMOB-24285)
When building without the --target option it will be undefined, so check don't set skipWpTool if it's undefined

[TIMOB-24285] Windows: Build fails when no target is specified

---

Examples/NMocha/src/Assets/app.js

Skip network tests on Jenkins Windows 10 node because it's behind firewall.

Skip network tests on Windows 10

---

templates/module/default/template/windows/README.md
templates/module/default/template/windows/plugins/hooks/windows.js

[TIMOB-24331](https://jira.appcelerator.org/browse/TIMOB-24331)
Currently CMake configuration file (CMakeLists.txt) and Visual Studio project is created only when you create Titanium Windows module project (`appc new`), but sometimes you need to update the VS project based on CMakeLists and re-run `cmake` manually in order to change project configuration (add files, add dependencies etc). Titanium CLI should be able to re-run `cmake` when `--run-cmake` is specificed behind the scenes.

[TIMOB-24331] Ability to re-run cmake for module project

---

Source/UI/src/Button.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Set `Titanium.UI.Button` `underlying_control__` for `WindowsViewLayoutDelegate`
```Javascript
var win = Ti.UI.createWindow({ backgroundColor: 'grey' }),
btn = Ti.UI.createButton({ title: 'BUTTON', touchEnabled: false });
alert('CLICK');
});
win.add(btn);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24328)

[TIMOB-24328] Set Ti.UI.Button underlying control for WindowsViewLayoutDelegate

---

Source/Network/src/Socket/TCP.cpp

- Always detach data stream after read/write
```Javascript
var net = require('net'),
port = 6262;
net.createServer(function (socket) {
console.log('client ' + socket.remoteAddress + ' connected');
socket.on('data', function (data) {
console.log('recv: ' + data);
});
socket.on('end', function () {
console.log('client ' + socket.remoteAddress + ' disconnected');
});
}).listen(port);
console.log('server listening on port ' + port);
```
```Javascript
var socket = Ti.Network.Socket.createTCP({
host: '127.0.0.1',
port: 6262,
timeout: 3000,
connected: function (e) {
Ti.API.info("connected to server");
var i = setInterval(function () {
if (!socket) {
clearInterval(i);
return;
}
Ti.API.info('sending data...');
Ti.Stream.write(socket, Ti.createBuffer({value: 'test'}), function () { …
```

[TIMOB-24266] Detach TCP stream after read/write

---

Source/UI/include/TitaniumWindows/UI/View.hpp
Source/UI/src/View.cpp

- Replace internal Javascript with native functions
- Allow font file to be specified in `fontFamily` (Windows limitation) [FontFamily](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.media.fontfamily)
```Javascript
});
win.add(Ti.UI.createLabel({
text: 'Hello World, Bold',
font: {
fontSize: 36,
fontFamily: 'segoeuib.ttf#Segoe UI 8'
}
}));
win.add(Ti.UI.createLabel({
text: 'Hello World, Italic',
font: {
fontSize: 36,
fontFamily: 'segoeuii.ttf#Segoe UI 8'
}
}));
win.add(Ti.UI.createLabel({
text: 'Hello World, Light',
font: {
fontSize: 36,
fontFamily: 'segoeuil.ttf#Segoe UI 8'
}
}));
win.open();
```
[fonts.zip](https://jira.appcelerator.org/secure/attachment/61303/fonts.zip)
- Update docs …

[TIMOB-24299] Allow font file to be specified when declaring fontFamily

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24223](https://jira.appcelerator.org/browse/TIMOB-24223)
```js
id: 'win',
layout:'vertical'
});
id: 'view1'
}),
view2 = Ti.UI.createView({
backgroundColor: 'black',
id: 'view2'
}),
view3 = Ti.UI.createView({
id: 'view3'
}),
view4 = Ti.UI.createView({
id: 'view4'
});
alert(e.source.id);
});
win.add(view3);
win.add(view4);
win.open();
```

[TIMOB-24223] Titanium event does not return correct source

---

Source/TitaniumKit/src/API.cpp

[TIMOB-24185](https://jira.appcelerator.org/browse/TIMOB-24185)
Logging APIs (`console.log`, `Ti.API.info` etc) should join argument strings.
```js
console.log('TEST');
console.log('TEST1', 'TEST2', 'TEST3');
```
should print
```
[INFO] TEST
[INFO] TEST1 TEST2 TEST3
```

[TIMOB-24185] Join arguments on logging

---

Source/Network/include/TitaniumWindows/Network/Socket/TCP.hpp
Source/Network/src/Socket/TCP.cpp

- Remove `HAL::RuntimeError` and call `error` callback
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'gray'});
var socket = Ti.Network.Socket.createTCP({
host: '192.168.255.255',
port: 6262,
timeout: 3000,
connected: function (e) {
console.log('[TEST] connected');
},
socket = null;
alert('[TEST] error: ' + e.error);
}
});
console.log('[TEST] connecting...');
socket.connect();
});
win.open();
```

[TIMOB-24336] Improve Ti.Network.TCP error handling

---

Source/TitaniumKit/src/UI/ListView.cpp
Source/TitaniumKit/src/UI/TableView.cpp
Source/UI/include/TitaniumWindows/UI/ListView.hpp
Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/ListView.cpp
Source/UI/src/TableView.cpp

[TIMOB-24126](https://jira.appcelerator.org/browse/TIMOB-24126)
Basically you don't need to add `SearchBar` explicitly to `Window`, `ListView`/`TableView` should take care of adding it.
ListView
```js
var _window = Ti.UI.createWindow({backgroundColor:'green'});
var searchBar = Ti.UI.createSearchBar();
var listView = Ti.UI.createListView({
searchView: searchBar
});
var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits' });
{ properties: { title: 'Apple' } },
{ properties: { title: 'Banana' } },
];
var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables' });
var vegDataSet = [
{ properties: { title: 'Carrots' } },
{ properties: { title: 'Potatoes' } },
]; …
```

[TIMOB-24126] Adding SearchBar to ListView/TableView should also add to window

---

Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/UI/TableViewRow.hpp
Source/TitaniumKit/include/Titanium/UI/TableViewSection.hpp
Source/TitaniumKit/src/Module.cpp
Source/TitaniumKit/src/UI/TableViewSection.cpp

[TIMOB-24125](https://jira.appcelerator.org/browse/TIMOB-24125)
To keep parity with iOS, `TableView` should create new `TableViewRow` on inserting existing row.
```js
top: 0,
bottom: 0
});
var tableData = [];
for (var i = 0; i < 10; i++) {
tableData.push(Ti.UI.createTableViewRow({
title: "Row " + (i + 1)
}));
}
table.setData(tableData);
_window.add(table);
table.addEventListener("click", function (e) {
var row = e.row;
Ti.API.info('index');
Ti.API.info(e.index);
Ti.API.info(row.title);
table.insertRowBefore(0, row);
});
```

[TIMOB-24125] TableView should create new row on inserting existing row

---

Source/TitaniumKit/include/Titanium/UI/TableView.hpp
Source/TitaniumKit/src/UI/TableView.cpp

[TIMOB-24134](https://jira.appcelerator.org/browse/TIMOB-24134)
`TableView.data` should return `TableViewSection[]`. As far as I can see from the source, `data` always returns `TableViewSection[]` on [iOS](https://github.com/appcelerator/titanium_mobile/blob/master/iphone/Classes/TiUITableViewProxy.m#L782) and [Android](https://github.com/appcelerator/titanium_mobile/blob/master/android/modules/ui/src/java/ti/modules/titanium/ui/TableViewProxy.java#L697). The reason why type of `Ti.UI.TableView.data` is marked both `Titanium.UI.TableViewRow[]/Titanium.UI.TableViewSection[]` in [API doc](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.TableView-property-data) I think is that it _accepts_ `Titanium.UI.TableViewRow[]` as well as `Titanium.UI.TableViewSection[]` whereas `data` …

[TIMOB-24134] TableView.data should return TableViewSection[]

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Revised PR for [TIMOB-24223](https://jira.appcelerator.org/browse/TIMOB-24223) because #924 does not support nested Views.
```js
id: 'win',
});
backgroundColor: 'white',
width: '80%', height: '80%',
id: 'view',
});
width: '80%', height: 100,
id: 'view1'
}),
view2 = Ti.UI.createView({
backgroundColor: 'black',
width: '80%', height: 100,
id: 'view2'
}),
view3 = Ti.UI.createView({
width: '80%', height: 100,
id: 'view3'
}),
view4 = Ti.UI.createView({
width: '80%', height: 100,
id: 'view4'
});
var view1_1 = Ti.UI.createView({
width: '70%', …
```

[TIMOB-24223] Support event source for nested views

---

Examples/NMocha/src/Assets/app.js

Skip network tests, which prevents from building nightly build. Seems like we have issues with networking codes, we should continue looking into this.

Skip network tests

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24252](https://jira.appcelerator.org/browse/TIMOB-24252)
Similar to #944, `touchEnabled` did not work well with Xaml `Border` and `Grid` etc. We should have propagated enabled status onto child components too. 
```js
});
touchEnabled: false
}),
view2 = Ti.UI.createButton({
top: 110, left: 110,
touchEnabled: false
}),
view3 = Ti.UI.createLabel({
top: 120, left: 120,
touchEnabled: false
}),
view4 = Ti.UI.createImageView({
backgroundColor: 'pink',
top: 130, left: 130,
touchEnabled: false
}),
view5 = …
```

[TIMOB-24252] touchEnabled with border/panel components

---

Examples/NMocha/src/Assets/app.js

Cherry-pick #949 for 6_0_X
Skip network tests, which prevented from building nightly build. Seems like we have issues with networking codes, we should continue looking into this.

[6_0_X] Skip network tests

---

Source/Network/src/Socket/TCP.cpp

- Fixed continuous output from `readAsync()`
- Improved error/exception handling for both `read` and `write` callbacks
```Javascript
var socket = Ti.Network.Socket.createTCP({
host: '127.0.0.1',
port: 6262,
timeout: 3000,
connected: function (e) {
console.log('connected to server');
// recieve data
Ti.Stream.pump(e.socket, function (e) {
if (!e.success) {
console.error('recv: ' + e.error);
return;
}
console.log('recv: ' + e.buffer.toString());
}, 1024, true);
// send data
var i = setInterval(function () {
if (!socket) {
clearInterval(i);
return;
}
console.log('sending data...');
Ti.Stream.write(socket, Ti.createBuffer({ value: 'test' }), function (e) {
if (!e.success) {
socket = null;
console.error('send: ' + e.error);
return;
}
console.log('sent');
});
}, 5000);
}, …
```

[TIMOB-24385] Fix Ti.Network.Socket.TCP.readAsync() to be continuous

---

Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24382](https://jira.appcelerator.org/browse/TIMOB-24382)
Adding same component multiple times should not cause error to align with iOS behavior.
```js
var label = Ti.UI.createLabel({ text: 'Test' });
win.open();
```

[TIMOB-24382] Adding same component should not cause error

---

Source/UI/src/TextField.cpp

[TIMOB-24371](https://jira.appcelerator.org/browse/TIMOB-24371)
Xaml `TextBox` fires `Enter` event twice. Microsoft is still ["investigating" this since 2012](https://social.msdn.microsoft.com/Forums/en-US/734d6c7a-8da2-48c6-9b3d-fa868b4dfb1d/c-textbox-keydown-triggered-twice-in-metro-applications?forum=winappswithcsharp). :|
```js
layout:'vertical'
});
var textField = Ti.UI.createTextField({
width: 250, height: 60
});
textField.addEventListener('return', function () {
alert('return event');
});
win.add(Ti.UI.createLabel({ text: 'type enter' }))
win.add(textField);
win.open();
```

[TIMOB-24371] TextField/TextArea return event fired twice

---

cli/commands/_buildModule.js

[TIMOB-24402](https://jira.appcelerator.org/browse/TIMOB-24402)
There was no way to limit target platform for module. You should have a way to limit them by updating configuration files now.
Steps:
1. Create your module project
```
appc new -n test --id com.example.test
```
2. Limit for "Windows 10 only"
Edit **YOUR_MODULE_PROJECT/windows/timodule.xml**
```xml
<windows>
<manifest>
<uses-sdk targetSdkVersion="10.0"/>
</manifest>
</windows>
```
3. Limit for"ARM only"
Edit **YOUR_MODULE_PROJECT/windows/manifest**
BEFORE
```
architectures: ARM x86
```
AFTER (Remove **ARM**)
```
architectures: x86
```
4. Build it
```
appc ti build -p windows --build-only
```
This should create module zip that targets Windows 10 only. You can see there is `win10` folder and there's no `phone` and `store` …

[TIMOB-24402] Ability to limit target platform for module

---

cli/commands/_build/generate.js
templates/build/Package.phone.appxmanifest.in.ejs
templates/build/Package.store.appxmanifest.in.ejs
templates/build/Package.win10.appxmanifest.in.ejs

[TIMOB-24455](https://jira.appcelerator.org/browse/TIMOB-24455)
Allow [Package/Extensions](https://msdn.microsoft.com/en-us/library/windows/apps/dn934749.aspx) for package manifest.
**tiapp.xml**
```xml
<windows>
<manifest>
<PackageExtensions>
<Extension Category="windows.publisherCacheFolders">
<PublisherCacheFolders>
<Folder Name="Folder1"/>
<Folder Name="Folder2"/>
</PublisherCacheFolders>
</Extension>
</PackageExtensions>
</manifest>
</windows>
```
`appc run -p windows --wp-sdk 10.0 --target ws-local -l trace --build-only` and then check if Extentions are there on your `YOUR_PROJECT_ROOT\build\windows\win10.x86\Package.appxmanifest`.

[TIMOB-24455] Allow Package Extensions

---

Source/UI/include/TitaniumWindows/UI/TableView.hpp
Source/UI/src/TableView.cpp

[TIMOB-24132](https://jira.appcelerator.org/browse/TIMOB-24132)
`touchmove` event for `TableView` did not work. We need to use Xaml `PointerMoved` event for TableView here because Xaml `ListView` doesn't fire `ManipulationDelta` event which is widely used in TitaniumKit, more lightweight version of `PointerMoved`.
```js
var data = [];
for (var i = 1; i <= 10; i++) {
data.push({
title: 'Row ' + i
});
}
var MyListbox = Ti.UI.createTableView({ data: data, top: 0, left: 0, width: Ti.UI.FILL, height: Ti.UI.FILL });
MyListbox.addEventListener('touchmove', TchMove);
function TchMove(evt) {
Ti.API.info('TchMove');
}
_window.add(MyListbox);
```

[TIMOB-24132] Implement TableView.touchmove event

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24239](https://jira.appcelerator.org/browse/TIMOB-24239)
`zIndex` did not work well with Xaml `Border` and `Grid`.
```js
});
zIndex: 140
}),
view2 = Ti.UI.createButton({
top: 110, left: 110,
zIndex: 130
}),
view3 = Ti.UI.createLabel({
top: 120, left: 120,
zIndex: 120
}),
view4 = Ti.UI.createImageView({
top: 130, left: 130,
zIndex: 110
}),
view5 = Ti.UI.createTextArea({
top: 140, left: 140,
zIndex: 100
}),
view6 = …
```

[TIMOB-24239] Implement zIndex

---

Source/UI/src/Label.cpp

[TIMOB-24554](https://jira.appcelerator.org/browse/TIMOB-24554)
Label size should not be resized on Ti.UI.FILL.
```js
}),
width_fill_label = Ti.UI.createLabel({
text: 'I have a width of Ti.UI.FILL',
textAlign: Titanium.UI.TEXT_ALIGNMENT_CENTER,
color: 'white',
backgroundColor: 'purple',
});
win.add(width_fill_label);
win.open();
```

[TIMOB-24554] Ti.UI.FILL resizes Label incorrectly

---

Source/Network/src/Network.cpp

[TIMOB-24561](https://jira.appcelerator.org/browse/TIMOB-24561)
Using `Ti.Network.change` event crashes app for Windows Store app.
1. Launch sample app (make sure you're online)
2. Turn the internet connection off.
3. Alert dialog should be shown accordingly
```js
});
Ti.Network.addEventListener('change', function (_evt) {
alert(JSON.stringify(_evt));
});
});
win.open();
```

[TIMOB-24561] Ti.Network change event crashes the app

---

cli/commands/_build/copy.js
cli/commands/_build/generate.js
cli/commands/_build/initialize.js
cli/commands/_build/run.js
cli/commands/_buildModule.js
cli/lib/stub.js
templates/build/CMakeLists.txt.ejs
templates/build/TitaniumWindows_Hyperloop/phone/TitaniumWindows_Hyperloop.csproj.ejs
templates/build/TitaniumWindows_Hyperloop/store/TitaniumWindows_Hyperloop.csproj.ejs
templates/build/TitaniumWindows_Hyperloop/win10/TitaniumWindows_Hyperloop.csproj.ejs
templates/module/default/template/windows/CMakeLists.txt.ejs
templates/module/default/template/windows/lib/README.md
templates/module/default/template/windows/platform/README.md
templates/module/default/template/windows/plugins/hooks/windows.js

[TIMOB-24101](https://jira.appcelerator.org/browse/TIMOB-24101)
Ability to use 3rd-party Windows Runtime component with hyperloop.
**This requires #961 to be merged.** This PR is actually created on top of #961 so this includes these changes too. Checkout individual commit https://github.com/appcelerator/titanium_mobile_windows/commit/404f3a4355f43308af2508400284ecda9b0e768b for code review. This requires latest Hyperloop module.
**Steps to test**
1. Create Windows Runtime Component
Create Windows Runtime Component named `WindowsRuntimeComponent1` from Visual Studio. Compile it and you should get `WindowsRuntimeComponent1.winmd` somewhere under in your Visual Studio project folder. You can skip this step by using prebuilt [WindowsRuntimeComponent1.winmd](https://jira.appcelerator.org/secur …

[TIMOB-24101] Ability to use 3rd-party native classes

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24583](https://jira.appcelerator.org/browse/TIMOB-24583)
```js
});
var Canvas = require('Windows.UI.Xaml.Controls.Canvas'),
SolidColorBrush = require('Windows.UI.Xaml.Media.SolidColorBrush'),
Colors = require('Windows.UI.Colors'),
TranslateTransform = require('Windows.UI.Xaml.Media.TranslateTransform');
var box = new Canvas();
box.Background = new SolidColorBrush(Colors.Red);
box.Width = 50;
box.Height = 50;
Canvas.SetLeft(box, 100);
Canvas.SetTop(box, 200);
win.add(box);
win.open();
```
**Expected**
Red box should be placed at position `left=100, top=200`
**Actual**
Red box is placed at center of the Window

[TIMOB-24583] Native view should use absolute position in Ti View

---

Source/Network/src/HTTPClient.cpp

[TIMOB-24615](https://jira.appcelerator.org/browse/TIMOB-24615)
Test Case
```js
var responseText = '';
var count = 0;
var client = Ti.Network.createHTTPClient();
client.onerror = function (e) {
};
client.onload = function (e) {
count = count + 1;
Ti.API.info((client.responseText == responseText) + ' should be false');
responseText = client.responseText;
if (count < 2) {
client.setRequestHeader('X-Request-Date', new Date().toString());
client.open("GET", "https://httpbin.org/get");
client.send();
}, 1000);
}
};
client.setTimeout(60000);
client.validatesSecureCertificate = false;
client.setRequestHeader('X-Request-Date', new Date().toString());
client.open("GET", "https://httpbin.org/get");
client.send();
```
should print
```
[INFO] false should be false
[INFO] …
```

[TIMOB-24615] HTTPClient.responseText is not cleared

---

cli/hooks/wp-run.js

[TIMOB-24656](https://jira.appcelerator.org/browse/TIMOB-24656)
App deployment failed while installing dependencies. I found that we can actually skip the step. I suspect deployment behavior has been changed at some point of SDK update. I would add new command line option `--skipInstallDependencies` to keep backward compatibility.
```
appc run -p windows --wp-sdk 10.0 --target wp-device -l trace --skipInstallDependencies
```
Expected: App deployment and launch should not fail.
I would like to push this to 6.1.x because it's critical.

[TIMOB-24656] Skip installing dependencies on deployment

---

Source/UI/include/TitaniumWindows/UI/WebView.hpp
Source/UI/src/ImageView.cpp
Source/UI/src/ScrollView.cpp
Source/UI/src/TableView.cpp
cli/commands/_build/copy.js
cli/lib/stub.js

[TIMOB-24644](https://jira.appcelerator.org/browse/TIMOB-24644)
Move Hyperloop-related code & logic to hyperloop plugin.
This PR doesn't actually remove existing Hyperloop logic and template files, but provides "compatibility mode" so we can run older version of Hyperloop module (< 2.2.0) in the newer version of Titanium SDK (>= 6.2.X).

[TIMOB-24644] Decouple Hyperloop logic and Ti SDK

---

Source/UI/src/ListView.cpp

Cherry-pick #1002 for 6_1_X.
I would like to backport this into `6.1.x` if QA time permits.

[6_1_X] [TIMOB-24714] ListView's scroll breaks if search bar added

---

cli/commands/_build/config/wpSDK.js

- Fix `wpSDK` when selecting `sdkTargets`
- When building without Windows SDK installed
```
appc run -p android --build-only
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24751)

[TIMOB-24751] Cannot build for Android if Windows SDK is not installed

---

Examples/NMocha/src/Assets/ti.ui.searchbar.test.js
Source/UI/include/TitaniumWindows/UI/SearchBar.hpp
Source/UI/src/SearchBar.cpp

JIRA: https://jira.appcelerator.org/browse/TIMOB-24795
Implement hintText for search bar
I had noticed that [in the docs](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.SearchBar) we show SearchBar as unimplemented on Windows, to fix this do I need to just add a SearchBar file [here](https://github.com/appcelerator/titanium_mobile_windows/tree/c6906ff2ecad57cc1942e6bec0c0a86e6912102a/apidoc/Titanium/UI)?
````
var searchWithHintText = Ti.UI.createSearchBar({
hintText: 'Search...',
color: "#333",
top: 250,
width: 300,
backgroundColor: "#fff"
});
var searchWithoutHintText = Ti.UI.createSearchBar({
color: "#333",
top: 300,
width: 300,
backgroundColor: "#fff"
});
var setMethBtn = Ti.UI.createButton({
title: 'Set the hintText via method',
top: …
```

[TIMOB-24795] Add hintText to search bar

---

Examples/NMocha/src/Assets/ti.ui.searchbar.test.js
Examples/NMocha/src/Assets/ti.ui.textfield.test.js
Source/TitaniumKit/include/Titanium/UI/TextField.hpp
Source/TitaniumKit/src/UI/SearchBar.cpp
Source/TitaniumKit/src/UI/TextField.cpp

JIRA: https://jira.appcelerator.org/browse/TIMOB-14410
Implement hinttextid for TextField and SearchBar
Verification:
i18n/en/strings.xml
````
<resources>
<string name="enter_email">Enter E-Mail ...</string>
<string name="enter_password">Enter Password ...</string>	
</resources>
````
app.js
````
backgroundColor : "#ccc"
}); 
win.add(Ti.UI.createTextField({
hinttextid: "enter_email",
width: 300,
height: 40,
color: "#333",
hintTextColor: "#f00",
backgroundColor: "#fff",
top: 50
}));
win.add(Ti.UI.createSearchBar({
hinttextid: "enter_email",
top: 100
}));
win.open();
````

[TIMOB-14410] Add hintTextid to all views

---

Source/UI/src/TableView.cpp

- Clear `collectionViewItems__` when unregistering sections
```JS
var win = Ti.UI.createWindow({layout: 'vertical'}),
btn = Ti.UI.createButton({title: 'setData()'}),
data = [
[{ title: 'A' }, { title: 'B' }, { title: 'C' }, { title: 'D' }],
[{ title: 'E' }, { title: 'F' }, { title: 'G' }, { title: 'H' }]
],
table = Ti.UI.createTableView({
data: data[0]
});
table.setData(data[1]);
});
win.add(btn);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24840)

[TIMOB-24840] Calling setData on a tableview that already has data errors out

---

Examples/NG/src/Assets/app.js

Building NG currently errors out, which I'm pretty sure is down to the hyperloop usage. So, I removed it, replacing with the default template code.
Is there any other parts I should remove?

Remove hyperloop usage from NG app

---

Examples/NMocha/src/Assets/ti.blob.test.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-24907
Failures have been observed when using app.js, it appears that ContentType for js files can be null on Desktop device families, this was reproduced using a native C# app also.
I rolled back to 5.5.1.GA and the test would fail for me there also, I am not sure why it appears intermittent on jenkins.
I guess this raises the question of what to do if the content type is null? I am yet to investigate what Android or iOS do here

[TIMOB-24907] Use Logo.png for mimetype test

---

Source/UI/src/TableView.cpp

[TIMOB-24833](https://jira.appcelerator.org/browse/TIMOB-24833)
Setting `TableView.height` (and `width`) to `auto` should act as `Ti.UI.FILL`.
```js
var tbl_data = [];
for (var i = 0; i < 50; i++) {
var row = Ti.UI.createTableViewRow();
left: 10,
text: 'Row ' + (i + 1)
});
row.add(label);
tbl_data.push(row);
}
var table = Titanium.UI.createTableView({
height: 'auto',
data: tbl_data,
borderWidth: 1,
borderColor: 'blue'
});
_window.add(table);
```

[TIMOB-24833] Setting TableView.height to auto breaks scrolling

---

cli/commands/_build/config.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-24936
1. Build an app with appc run -p windows -T notvalid
2. Select a target (exercise all possible targets, it does not have to build all the way through)
- The CLI should not error out when selecting wp-emulator or wp-device, ws-local and dist-* should work as normal

[TIMOB-24936] Windows: Build errors out when selecting wp-emulator or wp-device after being prompted for a target

---

cli/hooks/ws-run.js

JIRA: https://jira.appcelerator.org/browse/TIMOB-24938
appId must be set to the windows specific id for usage in the commands
1. Add the following to the windows section of your tiapp (creating if it doesnt exist) `<id>com.incrediblyuniqueappid</id>`
2. Build the app using appc run -p windows -T ws-local (windows local from Studio)
- The CLI should not error and the app should run as normal

[TIMOB-24938] CLI errors when using a Windows specific app id and building for ws-local

---

Source/UI/src/ListView.cpp

JIRA: https://jira.appcelerator.org/browse/TIMOB-24942
Same as #1032 but for ListView, setting height/width to auto will act as Ti.UI.FILL
````js
list = Ti.UI.createListView({
templates: {
template: {
{
type: 'Ti.UI.Label',
bindId: 'title',
properties: {
left: '5dp'
}
}
]
}
},
defaultItemTemplate: 'template',
height: 'auto'
}),
section = Ti.UI.createListSection(),
items = [];
for(var i = 0; i <100; i++) {
items.push({
title: { text: 'TEXT' }
});
}
section.setItems(items);
list.setSections([section]);
win.add(list);
win.open();
````
1. Add the above to an app.js and build for Windows
- Should be able to scroll the ListView

[TIMOB-24942] Fix scrolling of ListView with height set to auto

---

Examples/NMocha/src/Assets/ti.ui.webview.test.js
templates/build/Native/CMakeLists.txt.ejs

[TIMOB-24946](https://jira.appcelerator.org/browse/TIMOB-24946)
Ability to use 3rd party types in module header.
**Verification**
```js
var SAP = require('com.appc.module.test3'),
sap = new SAP();
win.addEventListener('open', function() {
alert(sap.testUsageInfo());
});
win.open();
```
* Download [com.appc.module.test3](https://jira.appcelerator.org/secure/attachment/62865/com.appc.module.test3-windows-1.0.0.zip) module zip and install in your Titanium SDK modules directory
* Create new app with `com.appc.module.test3` module enabled in your tiapp.xml (    `<module platform="windows">com.appc.module.test3</module>`) 
* Update app.js with the code described above
* `appc run -p windows --wp-sdk 10.0 --target ws-local -l trace`
* …

[TIMOB-24946] Ability to use 3rd party types as module member

---

Source/TitaniumKit/include/Titanium/detail/TiBase.hpp

[TIMOB-24925](https://jira.appcelerator.org/browse/TIMOB-24925)
Steps to reproduce
1. appc new -t timodule --name myawesomemodule --id com.foo
2. appc run -p windows --build-only
Verification
- If you have both VS2015 and VS2017 installed, it should build module libraries for Phone/Store/Win10. (Check folders inside module zip)
- If you have only VS2017 installed, it should build module libraries for Win10 only.
Developer note:
We should keep disableing `TITANIUM_MOVE_CTOR_AND_ASSIGN_DEFAULT_ENABLE` even on VS2017 to keep modules' backward compatibility.

[TIMOB-24925] Unable to build module with VS2017

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25044](https://jira.appcelerator.org/browse/TIMOB-25044)
[TIMOB-25023](https://jira.appcelerator.org/browse/TIMOB-25023)
View event delegation to children should take child's `touchEnabled` into account.
```js
id: 'win',
});
width: '40%', height: '40%',
id: 'view1',
touchEnabled: false
});
width: '40%', height: '40%',
id: 'view2'
});
alert(e.source.id);
});
win.open();
```
Expected: 
- When you click on `view1`, it should show the Window id `win`.
- When you click on `view2`, it should show view id `view2`. …

[TIMOB-25044][TIMOB-25023] Fix around touchEnabled

---

Source/UI/include/TitaniumWindows/UI/Picker.hpp
Source/UI/src/Picker.cpp

[TIMOB-25033](https://jira.appcelerator.org/browse/TIMOB-25033)
Expected:
- `classicPicker` - Setting `Ti.UI.SIZE` does not stretch its size (because of internal component spec, it does not stretch its size based on its content texts)
- `classicPicker2` - Setting number value to`Ti.UI.Picker.width` should adjust its size.
```js
var words = ['Bananas', 'Strawberries', 'Mangos', 'Electrocardiographically',
'October', 'November', 'September', 'Wednesday', 'Trinitrophenylmethylnitramine',
'Humor', 'Weekday', 'Balloon', 'Ornament', 'Strange', 'Disestablishmentarianism',
'Aeroplane', 'Aeroplane', 'Chess board', 'Floodlight', 'Rocket', 'Space Shuttle',
'Thermometer', ' Umbrella', 'Water', 'Tunnel', 'Treadmill', 'Lips', 'Brush',
'Subconstellation', 'Typewriter', 'Room', 'Money', 'Hieroglyph', …
```

[TIMOB-25033] Picker.width is ignored

---

Tools/Scripts/build/test.js

So I was checking out the failure for #1077 and was like huh it's using 6.2.0 `Error: ENOENT: no such file or directory, open 'C:\ProgramData\Titanium\mobilesdk\win32\6.2.0.v20170816173122\windows\lib\TitaniumKit\phone\x86\TitaniumKit.dll'` and was intrigued as to why, it's because if an SDK is already installed the `-d` flag in the sdk install command isn't respected 😱, that's a bug in titanium cli but for now we need to workaround it and this is how we do that

Ensure we select the SDK after installing it

---

Jenkinsfile

We've seen some failure where Jenkins has killed the builds because the tests ran over 20 minutes, this PR bumps that timeout from 20 to 25

Bump test timeout to 25 minutes

---

Examples/NMocha/src/Assets/ti.ui.button.test.js
Source/UI/src/ListView.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- [TIMOB-25175](https://jira.appcelerator.org/browse/TIMOB-25175) #1084
- [TIMOB-25014](https://jira.appcelerator.org/browse/TIMOB-25014) #1078
Cherry-pick for `6_2_X` because they are marked as regression.

[6_2_X][TIMOB-25014] [TIMOB-25175] regressions

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

Revert #1018 as it caused regression https://jira.appcelerator.org/browse/TIMOB-25261
```js
});
width: '40%', height: '40%',
id: 'view2'
});
view2.addEventListener('click', function (e) {
console.log(e.source.id);
});
var btn = Ti.UI.createButton({ title: 'I AM BUTTON' });
btn.addEventListener('click', function (e) {
console.log('YOU CLICKED THE BUTTON')
});
win.add(btn);
var lbl = Ti.UI.createLabel({ text: 'I AM LABEL' });
lbl.addEventListener('click', function (e) {
console.log('YOU CLICKED THE LABEL')
});
win.add(lbl)
win.open();
```
Should see the below when clicking the view
```
[INFO] view2
```

Revert timob 24867

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-24867] Fix panel components events when wrapped by border
Cherry-pick & squash #1103 for `6_3_X`.

[6_3_X][TIMOB-24867] Fix panel component events when wrapped by border 

---

Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Use border wrapper component when listening for panel component events
```JS
var win = Ti.UI.createWindow({backgroundColor: 'green'}),
borderRadius: 50,
borderColor: 'red',
borderWidth: 3,
width: '30%',
height: '30%'
});
view.addEventListener('dblclick', function (e) {
console.log('dblclick');
});
view.addEventListener('click', function (e) {
console.log('click');
});
win.add(view);
win.open();
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25261) and [TIMOB-24867](https://jira.appcelerator.org/browse/TIMOB-24867)

[TIMOB-24867] Fix panel component events when wrapped by border

---

Source/UI/src/Window.cpp

[TIMOB-25263](https://jira.appcelerator.org/browse/TIMOB-25263)
```js
var win1 = Ti.UI.createWindow({ backgroundColor: 'green' }),
win2 = Ti.UI.createWindow({ backgroundColor: 'lightblue'}),
win3 = Ti.UI.createWindow({ backgroundColor: 'pink' }),
button1 = Ti.UI.createButton({ title: 'open', borderWidth: 2, borderColor: 'red' }),
button2 = Ti.UI.createButton({ title: 'open', borderWidth: 2, borderColor: 'red', top: 100 }),
label2 = Ti.UI.createLabel({ text: '(Use back button to navigate back)', top: 150 }),
label3 = Ti.UI.createLabel({ text: '(Use back button to navigate back)' });
button1.addEventListener('click', function (e) {
win2.open();
});
button2.addEventListener('click', function (e) {
win3.open();
});
win1.add(button1);
win2.add(button2);
win2.add(label2);
win3.add(label3); …
```

[TIMOB-25263] Remove back button when there's no window left

---

Source/UI/include/TitaniumWindows/UI/PickerColumn.hpp
Source/UI/src/PickerColumn.cpp

[TIMOB-25247](https://jira.appcelerator.org/browse/TIMOB-25247)
Implement `Picker.setSelectedRow`.
```js
var picker = Ti.UI.createPicker({
type: Ti.UI.PICKER_TYPE_PLAIN,
selectionIndicator: true
});
var data = [];
var answerLoop = 0;
// add answers
for (answerLoop = 0; answerLoop < 11; answerLoop++) {
data.push(Ti.UI.createPickerRow({
title: 'Answer ' + answerLoop,
custom_item: answerLoop
}));
}
picker.add(data);
picker.setSelectedRow(0, 5, true);
var selectedButton = Ti.UI.createButton({
title: 'Select Answer 6',
width: 300,
height: 'auto',
top: 50
});
selectedButton.addEventListener('click', function (e) {
picker.setSelectedRow(0, 6, true);
console.log(picker.getSelectedRow(0).title);
});
_window.add(picker);
_window.add(selectedButton); …
```

[TIMOB-25247] Picker.setSelectedRow doesn't work

---

cli/hooks/wp-run.js

[TIMOB-24934](https://jira.appcelerator.org/browse/TIMOB-24934)
Skip installing dependencies when it is already installed.
**Steps to Test**
Please refer to the ticket description [TIMOB-24934](https://jira.appcelerator.org/browse/TIMOB-24934)

[TIMOB-24934] Skip installing dependencies when it is already installed

---

Source/TitaniumKit/include/Titanium/UI/PickerColumn.hpp
Source/TitaniumKit/src/UI/Picker.cpp
Source/TitaniumKit/src/UI/PickerColumn.cpp
Source/UI/include/TitaniumWindows/UI/PickerColumn.hpp
Source/UI/src/PickerColumn.cpp
Source/UI/src/Window.cpp
cli/hooks/wp-run.js

Backport #1096 #1108 #1111 #1110 for `6_3_X`
- [[TIMOB-25263](https://jira.appcelerator.org/browse/TIMOB-25263)] Remove back button when there's no window left
- [[TIMOB-25247](https://jira.appcelerator.org/browse/TIMOB-25247)] Picker.setSelectedRow doesn't work
- [[TIMOB-25245](https://jira.appcelerator.org/browse/TIMOB-25245)] picker.reloadColumn removes all other columns
- [[TIMOB-24934](https://jira.appcelerator.org/browse/TIMOB-24934)] Skip installing dependencies when it is already installed

[6_3_X] 6.3.X backports

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25325](https://jira.appcelerator.org/browse/TIMOB-25325)
```js
title: 'push',
height: 100,
width: 100
});
// This should always returns "50 : 50" (center coordinate of the button) on Windows
alert(e.x + ' : ' + e.y);
});
win.open();
```
Note: On Windows, `x` and `y` always returns center position of the Button because Windows Button does not actually provide the pointer coordinate information along with the event.

[TIMOB-25325] Click event of Button does not provide coordinates

---

Source/UI/src/ScrollableView.cpp

[TIMOB-25327](https://jira.appcelerator.org/browse/TIMOB-25327)
```js
var view1 = Ti.UI.createView({ backgroundColor: 'green' });
var view2 = Ti.UI.createView({ backgroundColor: 'red' });
var view3 = Ti.UI.createView({ backgroundColor: 'blue' });
var scrollableView = Ti.UI.createScrollableView({
views: [view1, view2, view3],
showPagingControl: true
});
scrollableView.addEventListener('scrollend', function (e) {
console.log(e.currentPage)
})
win.add(scrollableView);
win.open();
```
Expected: `currentPage` should be changed along with scroll event (tested on Windows & scrolled with mouse wheel)

[TIMOB-25327]  ScrollableViewer.currentPage not changed with scrollend

---

cli/commands/_build/validate.js

[TIMOB-25357](https://jira.appcelerator.org/browse/TIMOB-25357)
```
appc run -p windows --win-sdk 8.1 --target ws-local -l trace
```
Expected: The build went through, but should see `Support for Windows 8.1 and Windows Phone 8.1 SDKs has been dropped as of Titanium SDK 6.3.0.GA, and will be removed in Titanium SDK 7.0.0.GA` warning message.

[6_3_X][TIMOB-25357] Add deprecation warning when building using 8.1

---

Jenkinsfile
Tools/Scripts/build/setupSDK.js
cli/commands/_build/config/deviceID.js
cli/commands/_build/config/wpSDK.js
cli/commands/_buildModule.js
package.json
templates/module/default/hooks/windows-module.js

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24816
- drops Windows Desktop/Phone 8.1 support
- Uses the common mocha test suite from https://github.com/appcelerator/titanium-mobile-mocha-suite to run tests against builds on Jenkins
What this doesn't do:
- Remove/handle the `NMocha` test app under `Examples`. So we still have 2 separate test suites here in this repo. We should remove `Examples/NMocha` and use some tooling script to generate the app/sln that can be built/debugged under Visual Studio from our common test suite one-demand. It looks like we already have a script to generate the VS project: https://github.com/appcelerator/titanium_mobile_windows/blob/TIMOB-25019/Tools/Scripts/convert_project_to_example.js So I'm not sure if that's up to date or how much that'd …

[TIMOB-24816] Update the mocha suite in titanium_mobile_windows

---

Source/UI/src/ListView.cpp

[TIMOB-25175](https://jira.appcelerator.org/browse/TIMOB-25175)
Workaround. According to the studies from some environments ListView needs some more margins, otherwise unexpected scrollbar appears on the ListView. It seems it depends on device screen size (and default Window size at launch on desktop) but we needed more margins for the rows.
```js
var myTemplate = {
{
type: 'Ti.UI.View',
bindId: 'itemContainer',
properties: {
height: 50,
}
},
]
};
var listView = Ti.UI.createListView({
templates: { 'template': myTemplate },
});
var section = Ti.UI.createListSection();
var listItems = [];
for (var i = 0; i < 10; i++) {
listItems.push({
template: 'template', …
```

[TIMOB-25175] Unexpected scrollbar appears on ListView

---

Source/UI/src/Label.cpp

[TIMOB-25385](https://jira.appcelerator.org/browse/TIMOB-25385)
The first row in `TableView` is not displayed when using with `Label`. I'm pushing this to `6_3_X` too because it's critical.
```js
layout: "vertical",
});
var row1 = Ti.UI.createTableViewRow();
row1.add(Ti.UI.createLabel({
text: "THIS IS THE FIRST ROW",
}));
var row2 = Ti.UI.createTableViewRow();
row2.add(Ti.UI.createLabel({
text: "THIS IS THE SECOND ROW",
}));
data: [row1, row2],
});
text: "This label breaks first row",
});
win.open();
```
Note: This is only a workaround because I'm still not sure why table view row returns incorrect row size only for the first row.

[TIMOB-25385] TableViewRow with Label breaks layout

---

Source/TitaniumKit/include/Titanium/UI/TextField.hpp
Source/TitaniumKit/src/UI/TextField.cpp
Source/UI/include/TitaniumWindows/UI/TextField.hpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25235](https://jira.appcelerator.org/browse/TIMOB-25235)
```js
var textfield0 = Titanium.UI.createTextField({
top: 100
});
var textfield1 = Titanium.UI.createTextField({
top: 150
});
var textfield2 = Titanium.UI.createTextField({
top: 200
});
_window.addEventListener('open', function () {
textfield1.focus();
textfield1.blur();
Ti.API.info('lost focus?');
}, 3000);
}, 1000);
});
_window.add(textfield0);
_window.add(textfield1);
_window.add(textfield2);
_window.open()
```
Expected: second text field should gain focus after 1 sec passed, and then lost focus after 3 sec passed.

[TIMOB-25235] Implement TextField.blur()

---

Source/UI/src/TableViewRow.cpp

[TIMOB-24858](https://jira.appcelerator.org/browse/TIMOB-24858)
```js
var row = Ti.UI.createTableViewRow({
width: 300,
height: 40
});
var nameLabel = Titanium.UI.createLabel({
text: 'Title',
left: 10,
backgroundColor: 'pink'
});
row.add(nameLabel);
top: 100,
width: 300,
height: '60%',
data: [row],
borderWidth: 1,
borderColor: 'black'
});
var addButton = Ti.UI.createButton({
title: 'Add Label',
width: 200,
height: 100,
bottom: 0
});
addButton.addEventListener('click', function () {
var valueLabel1 = Ti.UI.createLabel({
text: 'New Label'
});
row.add(valueLabel1);
});
_window.add(tableView);
_window.add(addButton);
console.log(row.layout);
```
Expected: The label "Title" should be on position of …

[TIMOB-24858] TableViewRow defaults to horizontal layout

---

Source/UI/include/TitaniumWindows/UI/Label.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/Label.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25255](https://jira.appcelerator.org/browse/TIMOB-25255)
```js
var _window = Ti.UI.createWindow({ backgroundColor: 'gray' });
text: 'just a test label',
color: 'pink'
});
label.addEventListener('click', function (e) {
label.color = null;
});
_window.add(label);
```
Expected: Label color should be black when you click on the Label.

[TIMOB-25255] Fallback to default color on invalid Label.color name

---

Source/UI/src/TableView.cpp

[TIMOB-24124](https://jira.appcelerator.org/browse/TIMOB-24124)
```js
});
var header1 = Ti.UI.createView({ backgroundColor: 'red ' });
text: "That Section"
});
header1.add(label);
var section_0 = Ti.UI.createTableViewSection({ headerView: header1 });
section_0.add(Ti.UI.createTableViewRow({ title: 'Red' }));
var header2 = Ti.UI.createView();
var label2 = Ti.UI.createLabel({
text: "This Section"
});
header2.add(label2);
var section_2 = Ti.UI.createTableViewSection({ headerView: header2 });
section_2.add(Ti.UI.createTableViewRow({ title: 'Gray' }));;
data: [section_0]
});
tableView.updateSection(0, …
```

[TIMOB-24124] TableView.updateSection causes layout issue

---

Source/Network/src/HTTPClient.cpp

JIRA: https://jira.appcelerator.org/browse/TIMOB-25291
When performing a GET request and calling send with data the request used to be upgraded to a POST, this doesn't occur with other platforms.
<details>
<summary>Demo code</summary>
```js
title: 'stuff',
});
text: 'click me',
color: "#333",
font: {
fontSize: 20
}
});
label.addEventListener('click', function() {
var url = 'https://httpbin.org/anything';
var client = Ti.Network.createHTTPClient({
onload : function(e) {
alert("method was: " + JSON.parse(this.responseText).method);
Ti.API.info(this.responseText);
},
onerror : function(e) {
Ti.API.debug(e.error);
alert('error');
},
timeout : 5000
});
client.open("GET", url);
client.send({foo:'bar'});
}) …
```

[TIMOB-25291] Fix upgrade of GET with data to POST

---

Examples/NMocha/src/Assets/ti.ui.layout.test.js
Source/LayoutEngine/src/Node.cpp

[TIMOB-25257](https://jira.appcelerator.org/browse/TIMOB-25257)
It turns out this is layout engine issue and happens on all View subclasses.
```js
﻿﻿﻿var _window = Ti.UI.createWindow();
var view = Ti.UI.createTableView({
width: 50, height: 50
});
_window.addEventListener('open', function () {
_window.remove(view);
_window.add(view);
alert('passed');
}, 1000);
});
_window.add(view);
```
```js
﻿﻿﻿var _window = Ti.UI.createWindow();
width: 50, height: 50
});
_window.addEventListener('open', function () {
_window.remove(view);
_window.add(view);
alert('passed');
}, 1000);
});
_window.add(view);
```
Expected: App should not crash

[TIMOB-25257] Crash when adding view back

---

Source/TitaniumKit/src/UI/listview.js

[TIMOB-25326](https://jira.appcelerator.org/browse/TIMOB-25326)
```js
var listView = Ti.UI.createListView();
var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables' });
var vegDataSet = [
{ properties: { title: 'Carrots', image: 'http://api.randomuser.me/portraits/women/0.jpg', color: 'black' } },
{ properties: { title: 'Potatoes', color: 'black' } },
];
vegSection.setItems(vegDataSet);
sections.push(vegSection);
listView.sections = sections;
win.add(listView);
win.open();
```
Expected: image ListItem should not overlay text

[TIMOB-25326] image of ListItem should not overlay text

---

Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25325](https://jira.appcelerator.org/browse/TIMOB-25325)
Reopened ticket, it returned wrong Y-coordinate.
```js
title: 'push',
width: 100,
height: 50,
});
alert(e.x + ' : ' + e.y);
});
win.open();
```
Expected: This should return "50 : 25" (center coordinate of the button)

[TIMOB-25325] Wrong Y-coordinate for click event

---

Source/TitaniumKit/include/Titanium/UI/ListModel.hpp
Source/UI/src/TableView.cpp

[TIMOB-25275](https://jira.appcelerator.org/browse/TIMOB-25275)
The index property of a tableview click event should be in relation to the entirety of the tableview.
```js
var sectionFruit = Ti.UI.createTableViewSection({ headerTitle: 'Fruit' });
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Apples' }));
sectionFruit.add(Ti.UI.createTableViewRow({ title: 'Bananas' }));
var sectionVeg = Ti.UI.createTableViewSection({ headerTitle: 'Vegetables' });
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Carrots' }));
sectionVeg.add(Ti.UI.createTableViewRow({ title: 'Potatoes' }));
data: [sectionFruit, sectionVeg]
});
table.addEventListener('click', function (e) {
alert(e.index);
});
win.open();
```
Expected: …

[TIMOB-25275] index property of TableView click event

---

Source/UI/include/TitaniumWindows/UI/ActivityIndicator.hpp
Source/UI/src/ActivityIndicator.cpp

[TIMOB-25250](https://jira.appcelerator.org/browse/TIMOB-25250)
Implement `ActivityIndicator.indicatorDiameter` property. Without specifying `indicatorDiameter`, the progress ring goes to have a default size which tends to be small. You can resize size of the ring by changing `indicatorDiameter` property.
```js
﻿﻿var win = Ti.UI.createWindow({
backgroundColor: 'white',
});
var activityIndicator = Ti.UI.createActivityIndicator({
message: 'Loading...',
top: 10,
left: 10,
height: 120,
width: 120,
indicatorDiameter: 80,
});
win.add(activityIndicator);
win.addEventListener('open', function (e) {
activityIndicator.show();
});
win.open();
```

[TIMOB-25250] Implement ActivityIndicator.indicatorDiameter

---

Tools/Scripts/package.json

github recently alerted [potential security vulnerability in dependencies](https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/) in [moment package before 2.11.2](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4055). I believe this has to be small impact for us because it is only internal tools for development, but I would like to suppress the warning.

Fix potential security vulnerability in dependencies. (CVE-2016-4055)

---

Source/TitaniumKit/src/UI/TableView.cpp
Source/UI/src/TableView.cpp

[TIMOB-25274](https://jira.appcelerator.org/browse/TIMOB-25274)
```js
var data = [];
var row = Ti.UI.createTableViewRow();
var lbl = Ti.UI.createLabel({
text: 'LABEL'
})
row.add(lbl)
data.push(row);
var table = Titanium.UI.createTableView({
top: 100,
data: data
});
var btn = Ti.UI.createButton({
title: 'Add new data',
top: 5
});
var newData = [];
var newRow = Ti.UI.createTableViewRow();
var newLbl = Ti.UI.createLabel({
text: 'NEW LABEL'
})
newRow.add(newLbl)
newData.push(newRow);
table.setData(newData);
});
var oldbtn = Ti.UI.createButton({
title: 'Add old data',
top: 50
});
oldbtn.addEventListener('click', function () {
table.setData(data)
})
_window.add(btn);
_window.add(oldbtn) …
```

[TIMOB-25274] TableView.setData does not render UI elements

---

Source/LayoutEngine/src/Element.cpp
Source/LayoutEngine/src/Node.cpp
Source/TitaniumKit/src/UI/View.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/src/ListView.cpp
Source/UI/src/TableView.cpp
Source/UI/src/Window.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25641](https://jira.appcelerator.org/browse/TIMOB-25641)
TIMOB-25465 and TIMOB-25639 show that rendering issue happens when you try to add a view that is already added. According to the current code, we are not actually checking if the View is already added but just leaves the platform behavior how to render it in that case. We should just ignore the add operation when it is already added.
For test cases, just make sure nothing wrong happens when you add same view more than twice.
```js
width: 100, height: 100
});
win.add(view);
win.add(view);
win.open();
```

[TIMOB-25641] View.add should be ignored when it's ready added

---

Source/Filesystem/src/Filesystem.cpp

[TIMOB-25602](https://jira.appcelerator.org/browse/TIMOB-25602)
`Ti.Filesystem.isExternalStoragePresent()` returns true even when there's no external storage, and thus `Ti.Filesystem.applicationDataDirectory` returns wrong value (such as `\`). Following app failed because it tries to handle non-existing folders.
```js
var cDir;
if (Ti.Filesystem.isExternalStoragePresent()) {
cDir = Ti.Filesystem.externalStorageDirectory + "/Attachments";
} else {
cDir = Ti.Filesystem.applicationDataDirectory + "/Attachments";
}
var folder = Titanium.Filesystem.getFile(cDir);
if (!folder.exists()) {
folder.createDirectory();
}
Ti.API.info("folder exists:" + folder.exists());
var cDirTemp;
cDirTemp = cDir + "/Temp";
var folderTemp = Titanium.Filesystem.getFile(cDirTemp);
if (!folderTemp.exists()) { …
```

[TIMOB-25602] Wrong value for FileSystem external storage

---

Source/TitaniumKit/src/UI/View.cpp

[TIMOB-25794](https://jira.appcelerator.org/browse/TIMOB-25794)
```js
var Canvas = require('Windows.UI.Xaml.Controls.Canvas');
backgroundColor: 'white'
});
var SolidColorBrush = require('Windows.UI.Xaml.Media.SolidColorBrush');
var Colors = require('Windows.UI.Colors');
var box = new Canvas();
box.Background = new SolidColorBrush(Colors.Red);
box.Width = 50;
box.Height = 50;
win.addEventListener('click', function () {
view.add(box);
});
win.add(view);
win.open();
```
Expected: This should not crashes app.

[TIMOB-25794] Adding hyperloop view to a Titanium View crashes

---

Source/TitaniumKit/src/UI/View.cpp

Cherry-pick #1200 for 7_1_X
This is a regression from 7.0.2.GA.

[7_1_X][TIMOB-25794] Adding hyperloop view to a Titanium View crashes

---

cli/commands/_build/validate.js

Windows version of appcelerator/titanium_mobile/pull/9879
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24610 (do we need another one?)
Make babel transpilation an opt in process by using the `<transpile>true</transpile>` flag in the tiapp.xml
Test steps
1. Add the following to an app.js
```js
var undefined = 'This will error in strict mode as we are overwriting undefined';
```
2. Build for any target
3. Add `<transpile>true</transpile>` to your tiapp.xml
4. Build again
The app should throw an error similar to below the second time
```
[ERROR] Script Error {
[ERROR]     column = 16;
[ERROR]     line = 5;
[ERROR]     message = "Attempted to assign to readonly property.";
[ERROR]     sourceURL = "file:///Users/eharris/Library/Developer/CoreSimulator/Devices/19A348C6-7F86-4096-AEDE-90B …
```

[TIMOB-24610] Make transpiling off by default

---

Source/LayoutEngine/src/Node.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

[TIMOB-25814](https://jira.appcelerator.org/browse/TIMOB-25814)
UI rendering is broken when you add/remove/insert incorrectly. For instance:
- Add a view that is already added
- Insert a view that is already inserted
- Remove a view from wrong parent view

[TIMOB-25814] UI is not resized properly on incorrect operations

---

Source/UI/include/TitaniumWindows/UI/Picker.hpp
Source/UI/src/Picker.cpp

Cherry-pick #1174 for 7_1_X again, as #1196 was not actually merged to 7_1_X.

[7_1_X][TIMOB-25692] Pickers populated at run time do not fire change events

---

Tools/Scripts/package.json

github recently alerted [potential security vulnerability in dependencies](https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/) in [moment package before 2.19.3](https://nvd.nist.gov/vuln/detail/CVE-2017-18214). I believe this has to be small impact for us because it is only internal tools for development, but I would like to suppress the warning.

[CVE-2017-18214] Fix potential vulnerability in moment

---

cli/commands/_cleanModule.js

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23247
**Description:**
```
ti clean -p <platform>
```
This hooks up ti clean as a command that can be used for modules as we do with normal apps.
It's implemented in a single-platform at a time way, and isn't meant to yet support multi-platform modules like say hyperloop.
I took a best guess at the files we should be wiping out, but certainly open to suggestions/tweaks here.
Should be merged in conjunction with appcelerator/titanium_mobile#9807

[TIMOB-23247] CLI: Implement Native Module clean

---

Source/TitaniumKit/include/Titanium/Filesystem/File.hpp
Source/TitaniumKit/src/Filesystem/File.cpp
apidoc/Titanium/Filesystem/File.yml

[TIMOB-26028](https://jira.appcelerator.org/browse/TIMOB-26028)
- deprecate File.createTimestamp and modificationTimestamp
- add createdAt and modifiedAt that returns Date value
(See also https://github.com/appcelerator/titanium_mobile/pull/10019)
```js
var file = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, 'app.js');
Ti.API.info('createTimestamp: ' + file.createTimestamp());       // This should show warning message.
Ti.API.info('modificationTimestamp: ' + file.modificationTimestamp()); // This should show warning message.
var created   = file.createdAt();    // This should return Date value.
var modified = file.modifiedAt();  // This should return Date value.
Ti.API.info('createdAt: '  + (created instanceof Date)  + ' ' + created);
Ti.API.info('modifiedAt: ' + (modified …
```

[TIMOB-26028] Add parity for Ti.Filesystem.File

---

Tools/Scripts/setup.js

Fix path error in setup.js
```
Setting up JavaScriptCore pre-built libraries...
Downloading http://timobile.appcelerator.com.s3.amazonaws.com/jscore/dist/JavaScriptCore-Windows-1508145738839-win10.zip
path.js:28
throw new TypeError('Path must be a string. Received ' + inspect(path));
^
TypeError: Path must be a string. Received <Buffer 74 69 6d 6f 62 69 6c 65 2e 61 70 70 63 65 6c 65 72 61 74 6f 72 2e 63 6f 6d 2e 73 33 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 2f 6a 73 63 6f 72 65 2f ... >
at assertPath (path.js:28:11)
at Object.basename (path.js:820:5)
at C:\Jenkins\workspace\nium_mobile_windows_PR-1238-TJG2V7CJFECKF2R4R6MQDZUMJB37KCANAWXTHMLBIYLFQWZD4CMQ\Tools\Scripts\setup.js:239:22
```

Fix path error in setup.js

---

Source/Global/include/TitaniumWindows/GlobalObject.hpp
Source/Global/src/GlobalObject.cpp
cli/lib/stub.js
templates/build/Native/src/RequireHook.cpp.ejs

[TIMOB-25908](https://jira.appcelerator.org/browse/TIMOB-25908)
Add ability to require with namespace such as `require(package_name.*)`. This also enables ES6-style multiple imports such as `import { UICommand, MessageDialog } from 'Windows.UI.Popups.*';`.
This requires https://github.com/appcelerator/hyperloop.next/pull/281 to be merged together.
```js
// ES5-style require call with namespace
var System = require('System.*');
var Int32  = System.Int32;
// ES6-style import
import Button from 'Windows.UI.Xaml.Controls.Button';
import PropertyValue from 'Windows.Foundation.PropertyValue';
// ES6-style require with namespace
import { UICommand, MessageDialog } from 'Windows.UI.Popups.*';
let win = Ti.UI.createWindow({ backgroundColor: 'green' }),
button = new Button();
button.Content = …
```

[TIMOB-25908] Add ability to require with namespace 

---

Source/LayoutEngine/include/LayoutEngine/LayoutEngine.hpp
Source/LayoutEngine/src/ParseProperty.cpp
Source/Titanium/src/TitaniumWindows.cpp
Source/TitaniumKit/include/Titanium/App.hpp
Source/TitaniumKit/include/Titanium/UI/ViewLayoutDelegate.hpp
Source/TitaniumKit/src/App.cpp
Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp
Source/UI/src/ActivityIndicator.cpp
Source/UI/src/Label.cpp
Source/UI/src/ProgressBar.cpp
Source/UI/src/Window.cpp
Source/UI/src/Windows/ViewHelper.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

EXPERIMENTAL FEATURE
[TIMOB-25986](https://jira.appcelerator.org/browse/TIMOB-25986)
Introduce new unit specifier `ppx` to give ability to layout with physical pixels on Windows.
On Windows, the default unit specifier `px` is used as _effective pixels_, not actual physical pixels. Effective pixels are a virtual unit of measurement, and they're used to express layout dimensions and spacing, independent of screen density. (See [Introduction to UWP app design](https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro) for details). So when Microsoft uses the term "pixels" it doesn't mean actual physical pixels and that's why Titanium is using this effective pixels when you use "px" unit specifier. 
In order to support layout with actual physical pixels, we are …

[TIMOB-25986] Add physical pixels support 

---

Source/TitaniumKit/include/Titanium/Module.hpp
Source/TitaniumKit/include/Titanium/detail/TiImpl.hpp
Source/TitaniumKit/src/Application.cpp
Source/TitaniumKit/src/GeolocationModule.cpp
Source/TitaniumKit/src/Module.cpp
Source/Utility/include/TitaniumWindows/WindowsTiImpl.hpp
tests/Resources/error.test.js

[TIMOB-26048](https://jira.appcelerator.org/browse/TIMOB-26048)
- Refactor the red-screen of death (crash dialog) with stack traces to match the iOS/Android look and feel.
Note: On Windows we does not provide file name and file number where exception happens because Windows JavaScriptCore does not actually returns detailed information about where it happens. We are just providing the error message and stack traces.
```js
var win = Ti.UI.createWindow({ backgroundColor: 'gray' });
win.addEventListener('open', function (e) {
win.add(null);
});
win.open();
```
Expected:
- `add@[native code]` strings are the `stack` value that JavaScriptCore returns.
- `1  JSExportClass<class TitaniumWindows::UI::Window>::add` strings are the `nativeStack` values that represents Titanium module stack traces.

[TIMOB-26048] Refactor RSOD UI

---

cli/commands/_build/copy.js

https://jira.appcelerator.org/browse/TIMOB-26158
- `<buildDir>/bin/assets/Resources` does not exist on Windows. `<buildDir>/Assets` is I believe the correct path
Test steps
- Enable transpilation in your tiapp, `<transpile>true</transpile>`
- Build the project

[TIMOB-26158] Fix resourcesDir path

---

Source/UI/include/TitaniumWindows/UI/ScrollView.hpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/ScrollView.cpp

[TIMOB-26152](https://jira.appcelerator.org/browse/TIMOB-26152)
ScrollView doesn't return correct source when event listener is added to the scroll view's parent and there's no child view underneath of scroll view.
```js
width: 800,
height: 600
});
width: '80%',
height: '80%',
id: 'view'
}),
view2 = Ti.UI.createScrollView({
width: '70%', height: '70%', backgroundColor: 'blue', id: 'view2'
}),
view3 = Ti.UI.createView({
width: '70%', height: '70%', backgroundColor: 'pink', id: 'view3'
});
view2.add(view3);
view.add(view2);
view.addEventListener('click', function (e) {
alert(e.source.id);
});
win.add(view);
win.open();
```
Expected: Clicking blue view should show "view2". Clicking …

[TIMOB-26152] ScrollView doesn't return correct event source

---

Source/TitaniumKit/src/UI/listview.js

[TIMOB-26175](https://jira.appcelerator.org/browse/TIMOB-26175)
Label.text is ignored in ListView template
```js
var win = Ti.UI.createWindow({ backgroundColor: 'white' });
var myTemplate = {
{
type: 'Ti.UI.Label',
properties: {
color: 'blue',
left: 10, top: 0,
text: 'OMG :)'
}
},
{
type: 'Ti.UI.Label',
bindId: 'info',
properties: {
color: 'black',
left: 100, top: 0,
}
},
]
};
var listView = Ti.UI.createListView({
templates: { 'template': myTemplate },
defaultItemTemplate: 'template'
});
var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits / Frutas' });
{ info: { text: 'Apple' } },
{ info: { text: 'Banana' } }
];
var vegSection = …
```

[TIMOB-26175] Label.text is ignored in ListView template

---

Source/TitaniumKit/src/TiModule.cpp

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26115
Implement console.timeLog for Windows.
I've also cleaned up and aligned some of the code with Android as while looking to see if our JSCore version supported rest params (it does), that it supports default arguments.
Test:
```js
console.time('mytimer'); // Start timer
console.timeLog('mytimer'); // Log time taken so far
console.timeLog('mytimer', 'with', 'some', 'extra', 'info'); // Log time taken with extra logging
console.timeLog('mytimer', [ 'a', 'b', 'c' ], { objects: true }); // Should handle Arrays and Objects
console.timeEnd('mytimer');
```
Should log something like the below, there's some slight discrepancies between how Arrays/Objects are logged on platforms. Windows for example doesn't log an Objects properties, but logs …

[TIMOB-26115] Implement console.timeLog

---

package.json

[TIMOB-26139](https://jira.appcelerator.org/browse/TIMOB-26139)
I'm still not sure why Windows 10 SDK `10.0.15063.0` goes broken after installing latest Windows 10 SDK `10.0.17134.0`, but just bumping up the highest compatible target version fixes issue for me. I didn't have to uninstall `10.0.15063.0` SDK to make deployment work.

[TIMOB-26139] Fix build issue on phone device

---

templates/build/Package.win10.appxmanifest.in.ejs

[TIMOB-26311](https://jira.appcelerator.org/browse/TIMOB-26311)
Fix compile error when `rescap` Capabilities are set.
```xml
<windows>
<manifest>
<Capabilities>
<rescap:Capability Name="extendedBackgroundTaskTime"/>
<rescap:Capability Name="extendedExecutionUnconstrained"/>
</manifest>
</windows>
```
Expected: Defining `rescap` Capabilities in tiapp.xml (see above) should not fail.

[TIMOB-26311] Unable to define rescap Capability

---

cli/commands/_build/generate.js

Fix 'DOMParser' toString output that includes invalid string for `Capabilities`
```xml
<windows>
<manifest>
<Capabilities>
<rescap:Capability Name="extendedBackgroundTaskTime"/>
<rescap:Capability Name="extendedExecutionUnconstrained"/>
</manifest>
</windows>
```

[TIMOB-26311] Capability should have Name property only

---

Source/UI/include/TitaniumWindows/UI/TextArea.hpp
Source/UI/src/TextArea.cpp

[TIMOB-25983](https://jira.appcelerator.org/browse/TIMOB-25983)
`Ti.UI.TextArea` should resize its size when it is not specified. Revised #1230 because it did not consider `value` property.
```js
});
var parent = Ti.UI.createView({
width: '60%',
height: '60%',
backgroundColor: 'gray'
});
var textArea = Ti.UI.createTextArea({
backgroundColor: 'white',
color: 'black',
left: 40,
right: 40,
hintText: 'this is a long hint that is not wrapping in windows version. Not sure what is the problem. All text show in single line instead of multi line. please check',
value: 'this is a long text that is not wrapping in windows version. Not sure what is the problem. All text show in single line instead of multi line. please …
```

[TIMOB-25983] Ti.UI.TextArea is not resized when its size is not specified

---

Source/UI/src/TextArea.cpp

```js
it('value', function () {
var textArea = Ti.UI.createTextArea({
value: 'this is some text'
});
should(textArea.value).be.a.String;
should(textArea.getValue).be.a.Function;
should(textArea.value).eql('this is some text');
should(textArea.getValue()).eql('this is some text');
textArea.value = 'other text';
should(textArea.value).eql('other text');
should(textArea.getValue()).eql('other text');
});
```

[TIMOB-25983] Fix TextArea value until loaded

---

cli/commands/_build/copy.js

JIRA: jira.appcelerator.org/browse/TIMOB-26403
- Pass logger into to analyzeJs so we can log deprecation warning
To test:
Build kitchensink-v2 to device or simulator
You should see a warning log about "implicit global scope being deprecated
It should launch successfully

[TIMOB-26403] Pass logger to analyzeJs call

---

Source/UI/src/Label.cpp

Fix `Label.minimumFontSize` in 7.5.0 nightly build.
```js
width: 600, height: 200, backgroundColor: 'gray',
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
minimumFontSize: 2,
});
win.open();
```
Expected: Label texts decrease its size to fit Label content size.

Fix: Label.minimumFontSize does not work

---

Examples/kitchensink-v2/CMakeLists.txt
Source/UI/src/ScrollView.cpp

Seems like the [Layout cycle detected](https://jira.appcelerator.org/browse/TIMOB-26510) is something related to `ScrollView`. It is reported that Windows UWP `ScrollViewer` tends to crash with this error when its scroll bar is not visible for no reason.

[TIMOB-26510] Workaround "layout cycle" issue

---

cli/commands/_build/copy.js
cli/commands/_build/generate.js

[TIMOB-26531](https://jira.appcelerator.org/browse/TIMOB-26531)
Refer to the ticket for the test case.

[7_5_X][TIMOB-26531] Build fails when module resources has sub folders

---

Source/UI/src/WebView.cpp

[TIMOB-26540](https://jira.appcelerator.org/browse/TIMOB-26540)
```js
});
var webView = Titanium.UI.createWebView({
html: '<select name="selectBox"><option value="val1">Value 1</option><option value="val2">Value 2</option><option value="val3">Value 3</option></select>'
});
win.add(webView);
win.open();
```
Expected: Application should not crash

[7_5_X][TIMOB-26540] Fix crash when using html property

---

templates/build/CMakeLists.txt.ejs

[TIMOB-26524](https://jira.appcelerator.org/browse/TIMOB-26524)
- Create `folder with spaces` folder under `Resources`
- Place `test.js` (can be anything, content does not matter) under `folder with spaces` folder
- Run the app
```js
var win = Ti.UI.createWindow({backgroundColor: 'green'});
win.addEventListener('open', function() {
alert(Ti.Filesystem.getFile('folder with spaces/test.js').exists());
});
win.open();
```
Expected: The project compiles and app should launch, and should alert `true`.

[TIMOB-26524] Can not compile folder with spaces

---

Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp

[TIMOB-25582](https://jira.appcelerator.org/browse/TIMOB-25582)
Add support for `dp` in `ti.ui.defaultunit`. This will introduce breaking change on view sizes because our `tiapp.xml` default unit is set to `dp` usually but we've been using `px` for Windows default unit. In order to keep consistency between old versions, you need to set ` <property name="ti.ui.defaultunit" type="string">px</property>` explicitly in `tiapp.xml`.
```js
width: "100px", height: "100px",
});
width: "100dp", height: "100dp",
top: 200, left: 100,
});
width: "100", height: "100",
top: 300, left: 100,
backgroundColor: …
```

[TIMOB-25582] Add support for dp in ti.ui.defaultunit

---

Source/LayoutEngine/src/ParseProperty.cpp

[TIMOB-26508](https://jira.appcelerator.org/browse/TIMOB-26508)
Setting `undefined` to layout property should "clear" layout value. For instance, setting both `left` and `top` disables `center` property (expected behavior) but we should be able to enable `center` property again by setting `undefined` for `left` and `top` properties.
```js
});
view1.top  = undefined;
view1.left = undefined;
view1.center = { x: e.x, y:e.y };
});
win.open();
```
Expected: The blue view should move to where you click.

[TIMOB-26508] Setting undefined should clear layout value

---

Source/TitaniumKit/CMakeLists.txt
Source/TitaniumKit/include/Titanium/UI/ViewPadding.hpp
Source/TitaniumKit/include/Titanium/UI/Window.hpp
Source/TitaniumKit/src/UI/ViewPadding.cpp
Source/TitaniumKit/src/UI/Window.cpp

[TIMOB-26464](https://jira.appcelerator.org/browse/TIMOB-26464)
Add `safeAreaPadding` and `extendSafeArea` property for `Ti.UI.Window`.
On Windows, we just hard-code the padding to all zeros because safe are is just not supported on Windows. I wouldn't update the API doc to state these properties are "supported" because these properties only intend to be a placeholder on Windows just to make sure use of these properties doesn't cause runtime errors.
```js
Ti.API.info(JSON.stringify(win.safeAreaPadding));
Ti.API.info(win.extendSafeArea);
```
Expected: `safeAreaPadding` returns empty padding. `extendSafeArea` defaults to `false`.
```
[INFO] {"bottom":0,"left":0,"right":0,"top":0}
[INFO] false
```

[TIMOB-26464] Add Ti.UI.Window.safeAreaPadding and extendSafeArea

---

Tools/Scripts/build/test.js

#1300 introduces breaking change on `ti.ui.defaultunit`. We should explicitly declare to use `px` in order to keep consistency between previous versions.

Fix default unit to 'px' before unit tests

---

Jenkinsfile

Fixes https://jira.appcelerator.org/browse/TIMOB-26592.
This allows the Windows specific API namepsaces to be included in the api.jsca files (and similar).
Will test the process locally once the artifacts from this build are produced

chore(build): Archive WindowsOnly docs

---

Tools/Scripts/build/build.js

Relates to #1319
Jenkins master build is failing because of `TypeError: Cannot read property 'replace' of undefined` and turns out `await fs.readFile` returns undefined for some reason. Pushing a workaround.

await fs.readFile returns undefined for some reason.

---

Source/TitaniumKit/include/Titanium/UI/Constants.hpp
Source/TitaniumKit/src/UI/Constants.cpp
Source/UI/include/TitaniumWindows/UI/WindowsViewLayoutDelegate.hpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

Note: This requires #1300 to be merged in order to use `dp` in `tiapp.xml`.
[TIMOB-26503](https://jira.appcelerator.org/browse/TIMOB-26503)
```js
});
});
view1.left = e.x;
view1.top  = e.y;
});
win.open();
```
Expected: The blue view should move (based on upper-left corner) to where you click even when you set `ti.ui.defaultunit` to `dp`.

[TIMOB-26503] Touch coordinate should not ignore default unit

---

Source/UI/include/TitaniumWindows/UI/ImageView.hpp
Source/UI/src/ImageView.cpp

[TIMOB-26579](https://jira.appcelerator.org/browse/TIMOB-26579)
```js
var image = Ti.UI.createImageView();
image.addEventListener('load', function (e) {
Ti.API.info(e.state);
});
image.image = 'http://api.randomuser.me/portraits/women/0.jpg';
});
win.add(image);
win.open();
```
Expected: This should print `image` in console
```js
var image = Ti.UI.createImageView();
image.addEventListener('load', function (e) {
Ti.API.info(e.state);
});
image.images = [
'http://api.randomuser.me/portraits/women/0.jpg',
'http://api.randomuser.me/portraits/women/1.jpg',
];
});
win.add(image);
win.open();
```
Expected: This should print `images` in console

[TIMOB-26579] Ti.UI.ImageView's load event object has no state property

---

Source/TitaniumKit/src/GeolocationModule.cpp

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23496
**Description:**
- Spit out deprecation notices when Ti.Geolocation.reverseGeocode result is returned (with suggested replacements)
- Deprecate `country_code` and `zipcode` properties in favor of `countryCode` and `postalCode` (respectively)
Equivalent iOS/Android PR: appcelerator/titanium_mobile#10543

fix: unify properties of GeocodedAddress and deprecate old properties

---

Source/Ti/src/Locale.cpp
Source/TitaniumKit/src/Locale.cpp
tests/Resources/ti.locale.test.js

[TIMOB-26651](https://jira.appcelerator.org/browse/TIMOB-26651)
_**i18n/en/strings.xml**_
```xml
<resources>
<string name="this_is_my_key">this is my value</string>
</resources>
```
_**i18n/es/strings.xml**_
```xml
<resources>
<string name="this_is_my_key">este es mi valor</string>
</resources>
```
_**Resources/app.js**_
```js
Ti.Locale.setLanguage('en-US');
Ti.API.info(Ti.Locale.getCurrentLanguage() + '.eql(en)');
Ti.API.info(Ti.Locale.getString('this_is_my_key') + ' should be "this is my value"');
Ti.Locale.setLanguage('es');
Ti.API.info(Ti.Locale.getCurrentLanguage() + '.eql(es)');
Ti.API.info(Ti.Locale.getString('this_is_my_key') + ' should be "este es mi valor"');
Ti.Locale.setLanguage('en-US');
``` …

[TIMOB-26651][TIMOB-26667] Parity in Ti.Locale.setLangauge

---

Source/TitaniumKit/src/analytics.js

- Use V4 analytics endpoint
- Update default payload to include misc `data` properties
- Always send full payload with all events
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26748)

fix: always send full analytics payload

---

cli/hooks/wp-run.js

[TIMOB-26766](https://jira.appcelerator.org/browse/TIMOB-26766)
Increase timeout for wp-device.
Expected: Installing app with Hyperloop should go through

[TIMOB-26766] Timeout when installing to wp-device

---

cli/commands/_build/checks.js

[TIMOB-26776](https://jira.appcelerator.org/browse/TIMOB-26776)
This basically reverts part of changes we did in #1282 - [cli/commands/_build/checks.js](https://github.com/appcelerator/titanium_mobile_windows/pull/1282/files#diff-fd07e68df4675cca1ea553ba6a2128e5). This happens only when re-build with no changes made in JS source.

[8_0_X][TIMOB-26776]  App launch failed with "cyclic redundancy check"

---

Examples/NG/CMakeLists.txt
Tools/Scripts/generate_project.js

I noticed that the `Examples` projects not working with new CMake config.
In order to make `> node generate_project.js new NG` work, I needed to include `LayoutEngine` from `NG` config, and also I found I was actually forced to remove `ReferenceOutputAssembly` and `CopyToOutputDirectory` _manually_ from generated `NG.vcxproj`.
```diff
<ProjectReference Include="NG.Windows10.Win32\HAL\HAL.vcxproj">
<Project>{8C139CE2-A2D6-3C5E-A633-6E84C3CBB867}</Project>
<Name>HAL</Name>
-      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
-      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
</ProjectReference>
<ProjectReference Include="NG.Windows10.Win32\TitaniumKit\TitaniumKit.vcxproj">
<Project>{F5A9F106-E6FA-32B0-96B2-4179D219FE98}</Project>
<Name>TitaniumKit</Name>
- …
```

Fix examples to work with new cmake confg

---

Source/Network/src/Socket/TCP.cpp
Source/Network/src/Socket/UDP.cpp
Source/UI/src/WebView.cpp
tests/Resources/ti.ui.webview.test.js

Experimental.
Save object instance at callbacks around networking (e.g. Ti.Network/Ti.UI.WebView) to stablize Jenkins tests.

[TIMOB-26979] Save callback instances to stablize tests on Jenkins

---

Source/TitaniumKit/src/Database/ResultSet.cpp

An attempt to see if this fixes DB integer overflow issues exposed by new unit test in our suite that has fixed on Android.
Basically JS and C++/Java have mismatches on what the range of values an "integer" can hold. JS defines it as 2^53 - 1, while Java/C++ use 2^31 -1. So this tries to read the integer columns as 64-bit integers (then cast to double and wrap in JS Number).
See failed test here: https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium-mobile-mocha-suite/job/master/63/testReport/junit/windows.ws-local.Titanium/Database/Test___ws_local___db_read_write_integer_boundaries/

fix(database): avoid integer overflows

---

apidoc/Titanium/UI/Window.yml

Some events were marked as "not supported" because of this

docs(Window): Add Ti.UI.Window events

---

tests/Resources/app.js
tests/Resources/ti.filesystem.filestream.test.js

I've been trying to narrow down what makes the tests unstable. It seems JavaScriptCore becomes unstable probably because we loads too many tests that Titanium Windows can handle. So I ended up removing some suites that's not for Titanium APIs (for instance ES6 functions and JS builtins etc) then it makes the tests more stable. I also ended up skipping some tests that's still crashing, which might be related to accessing file systems. I'll raise separate ticket for them.

Attempt to stabilize Jenkins tests

---

Tools/Scripts/build/build.js

It seems some Jenkins build jobs have been failing to build for latest Windows 10 SDK because required sdk is not installed. We need to specify installed SDK version instead of using "10.0" as default value.

Force Win10 sdk 10.0.14393 for x86/ARM build

---

cli/commands/_build/copy.js

https://jira.appcelerator.org/browse/TIMOB-27452
Fixes TIMOB-27452
Requires appcelerator/titanium_mobile/pull/11269

fix: only copy windows ti.main.js file

---

cli/commands/_build/copy.js
cli/commands/_build/initialize.js

This aligns Windows with the same js processing code as Android and iOS, which handles all the knowledge like dont minify the internal common files, incremental builds etc
Fixes [TIMOB-27452](https://jira.appcelerator.org/browse/TIMOB-27452)
Pinging @janvennemann to just make sure I'm using the processjs stuff right

refactor(cli/build): move to using common processjstask

---

cli/commands/_build/copy.js
cli/commands/_build/initialize.js

* refactor(cli/build): move to using common processjstask
This aligns Windows with the same js processing code as Android and iOS, which handles all the knowledge like dont minify the internal common files, incremental builds etc
Fixes TIMOB-27452
* fix: correctly construct tasks array

refactor(cli/build): move to using common processjstask (#1435)

---

cli/commands/_build/generate.js

[TIMOB-24704](https://jira.appcelerator.org/browse/TIMOB-24704)
Fix CLI error when minor version number is not set for target platform versions.
**tiapp.xml**
```xml
<windows>
<TargetPlatformVersion>10.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0</TargetPlatformMinVersion>
<windows>
```
Compile with
```
appc run -p windows -l trace --target ws-local --build-only
```
Expected: App should be compiled without errors

[TIMOB-24704] CLI errors out when TargetPlatformVersion does not have minor version

---

Source/UI/src/Windows/ViewHelper.cpp
Source/UI/src/WindowsViewLayoutDelegate.cpp

- Cherry-pick of https://github.com/appcelerator/titanium_mobile_windows/pull/1440
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27638)

fix(8_3_X): unit specifier for fontSize should be ignored

---

Source/Network/src/HTTPClient.cpp

- Always fire HTTPClient status events on UI thread
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27748)

fix(windows)(8_3_X): fire HTTPClient events on UI thread
